<?php	
	$this->headTitle('Add Pawn'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	echo $this->frmpupopinfoclient;
?>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
			co_id = dijit.byId('co_id').get('value');
			client = dijit.byId('member').get('value');
           branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
			currency_type = dijit.byId('currency_type').get('value');
			if(currency_type==1){
				amount_loan = dijit.byId('total_amount').get('value');
				if(amount_loan<10000){
					alert('Loan Amount Must Than 10000 for Riel Currency!');
                }

            }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-10px;">
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("ព៌ត័មាន អតិថិជន​")?></strong></legend>
					<table cellspacing="10"  width="100%" style="margin-top: -10px;">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("PAWN_NO")?></td>
							<td><?php echo $frm->getElement('loan_code');?></td>
							<td><?php echo $tr->translate("LOAN_LEVEL")?></td>
							<td><?php echo $frm->getElement('level');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /></td>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><input id="member" /> </td>
							<td><?php echo $tr->translate("បង្កាន់ដៃទទួលប្រាក់")?></td>
							<td><?php echo $frm->getElement('receipt_num');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("ព៌ត័មាន ដាក់បញ្ចាំ​")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រភេទ​​ទ្រព្យដាក់បញ្ចាំ")?></td>
							<td><?php echo $frm->getElement('product_id');?></td>
							<td><?php echo $tr->translate("តម្លៃប៉ាន់ស្មាន ទ្រព្យដាក់បញ្ចាំ")?></td>
							<td><?php echo $frm->getElement('estimatevalue');?></td>
							<td></td>
							<td></td>
							
						</tr>
						<tr>
							<td align="center"><?php echo $tr->translate("ពត៍មានលម្អិត​​ ទ្រព្យដាក់បញ្ចាំ")?></td>
							<td colspan="5"><?php echo $frm->getElement('description');?></td>
						</tr>
						<tr>
					        <td><?php echo $tr->translate("ចំនួនប្រាក់កម្ចី")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("CURRENCY")?></td>
							<td align="left"><?php echo $frm->getElement('currency_type');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("រយៈពេល​បញ្ចំា")?></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("រយះពេលដាក់បញ្ចាំ(គិតជា)")?></td>
							<td><?php echo $frm->getElement('pay_every');?></td>
							<td><?php echo $tr->translate("អត្រាការប្រាក់​")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃដាក់បញ្ចាំ​")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
							<td><?php //echo $tr->translate("ថ្ងៃបង់ប្រាក់ដំបូង​")?></td>
							<td><?php //echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("ថ្ងៃបញ្ចប់ប្រាក់បញ្ចាំ")?></td>
							<td><?php echo $frm->getElement('date_line');?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បង្កាន់ដៃដាក់ទ្រពបញ្ចាំ ', onCancel:hideDialog" id="frm_client" style="width:24cm;">
	<div id="rpt_print" class="print">
		<style>
					.fontbig{
						font-size: 15px;	
					}
					.fonttel{
						font-size: 18px;	
					}
					.pleft{
						width: 110px;	
					}
					.label{ font-weight: bold;font-size: 22px;}
					.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
							margin-top: -25px; line-height: 25px;
						    text-align: center;
							}
					.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
							line-height: 25px;}
					.h{ margin-top: -8px;/*margin-left:4px;*/}
	​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
				   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
				   .khmer{font:12px 'Khmer OS Battambang';}
				   .one{white-space:nowrap;}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				</style>	
				<table class="print" bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="height: 12cm; font-size:12px; color:rgba(14, 0, 107, 1);  padding:25px 10px 0px 5px; margin: 0px;">
					<tr>
						<td colspan="6">
							<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="30%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
				                	<td valign="top" align="center">
				                		<div class="h" ><?php echo $tr->translate("បង្កាន់ដៃដាក់ទ្រពបញ្ចាំ");?></div> 
				                		<div class="h" ><?php echo $tr->translate("PAWN TICKET RECEIPT");?></div> 
				                	</td>
				                    <td width="30%">
				                    	<div class="h"><?php echo $tr->translate("BRAND_TITLE");?></div> 
				                    	<span style="font-family:'Khmer OS Battambang';font-size: 12px;;"><?php echo $tr->translate("ADDRESS_COMPANY");?>
													<br /><?php echo $tr->translate("TEL_COMPANY");?>
													</span>
				                    </td>
				                </tr> 
				                 
				            </table>
						</td>
					</tr>
					<tr>
					    <td class="one khmerbold" valign="middle">ប្រភេទទ្រព្យបានដាក់បញ្ចាំ<div class="h">Customer's Collateral </div> </td>
					    <td width="25%" colspan="3"><strong> &nbsp;<label id="lb_producttype" class="value one khmerbold"></label></strong></td>
					    <td class="one khmerbold">&nbsp;&nbsp;លេខបង្កាន់ដៃដាក់ទ្រពបញ្ចាំ<div class="h">&nbsp;&nbsp;Collateral Receipt No</div></td>
					    <td width="25%"><strong>&nbsp;<label id="lb_receipt_no" class="value"></label></strong></td>
					</tr>
					<tr>
					    <td class="one khmerbold" >ចំនួនប្រាក់ខ្ចី&nbsp;<div class="h">Amount of Loan</div> </td>
					    <td width="25%"><strong> &nbsp;<label id="lb_loanamount" class="value"></label></strong></td>
					    <td class="one khmerbold"  valign="middle">&nbsp;&nbsp;អាត្រាការប្រាក់&nbsp;<div class="h">&nbsp;&nbsp;Interest Rate</div> </td>
					    <td width="25%"><strong>&nbsp;<label id="lb_interest_rate" class="value"></label></strong></td>
						<td class="one khmerbold"  valign="middle">&nbsp;&nbsp;ការប្រាក់ត្រូវបង់សរុប&nbsp;&nbsp;<div class="h">&nbsp;&nbsp;Total Interest</div></td>
					    <td width="25%"><strong>&nbsp;<label id="lb_total_interest" class="value"></label></strong></td>
					
					</tr>
					<tr>
					    <td class="one khmerbold">កាលបរិច្ឋេទអោយខ្ចី <div class="h">Date of Loan</div></td><td width="25%"><strong> &nbsp;<label id="lb_start_date" class="value"></label></strong></td>
					    <td class="one khmerbold">&nbsp;&nbsp;រយះពេលរំលោះទ្រព <div class="h" style="margin-left:7px !important;">Redemption Period</div></td><td width="25%"><strong> &nbsp;<label id="lb_period" class="value" style="font-size: 11px;white-space:nowrap;"></label></strong></td>
					    <td class="one khmerbold" valign="middle">&nbsp;&nbsp;កាលបរិច្ឋេទផុតកំណត់ <div class="h" style="margin-left:7px !important;">DATE OF EXPIRY</div> </td><td width="25%"><strong>&nbsp;<label id="lb_end_date" class="value" style="font-size: 11px;white-space:nowrap;"></label></strong></td>
					</tr>
					<tr height="120px">
					    <td class="one khmerbold" colspan="2" align="center" valign="top" style="border:1px solid #000 !important;"><strong>អត្តសញ្ណាណប័ណ្ឌ ឈ្មោះ និងអាសយដ្ឋានអ្នកដាក់ទ្រព្យ  <div class="h">ID NAME ADDRESS OF PAWNER OF LOAN</div></strong><div></div><label id="lb_customername" style="font-size: 11px;"></label></div></td>
					    <td class="one khmerbold" colspan="2" align="center" valign="top" style="border:1px solid #000 !important;border-left: 1px solid #fff !important; border-right: 1px solid #fff !important;">&nbsp;&nbsp;ឈ្មោះនិង អាសយដ្ឋានអ្នកធានា <div class="h" style="margin-left:7px !important;">NAME ADDRESS OF GUARANTOR</div></td>
					    <td class="one khmerbold" colspan="2" align="center" valign="top" style="border:1px solid #000 !important;">&nbsp;&nbsp;ឈ្មោះនិង ហត្ថលេខាគណនេយ្យ  <div class="h" style="margin-left:7px !important;">NAME AND SIGNATUR OF ACCOUNTANT</div> </td>
					</tr>
					
					<tr>
					    <td colspan="3" class="khmerbold">&nbsp;</td>
					    <td  colspan="3" align="right" class="khmerbold" style="line-height: 16px;">
			
					        <h4 style="padding-right: 0px ! important;"> 
							        <?php 
									   $session_user=new Zend_Session_Namespace('auth');
							           $last_name=$session_user->last_name;
							           $username = $session_user->first_name;
									   echo " Official's Signature : ".$last_name." ".$username;
									?>
									<?php  $today = date("F j, Y, g:i a");echo $today; ?>
					        </h4>
					    </td>
					</tr>
					<tr><td colspan="6" style="height:50px;"></td></tr>
					
				</table>
	</div>
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
</div>
</div>
</form>
<?php echo $this->frmpupoploantype;?>
<script type="text/javascript">	
r=0;
var url_previewloan = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'index','action'=>'addpawnshoptest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			alert('Please Select Branch Name!');
			dijit.byId('branch_id').focus();
			return false;
		}
		
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}
		//rs = checkValidateDate();
		//if(rs==false){
         // return false;			
       // }
		
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				//alert(data);
				document.getElementsByClassName("overlay")[0].style.display="none";
				var d = dijit.byId("release_date").get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_start_date").innerHTML  = day+'-'+x+'-'+year;
				 var d = dijit.byId("date_line").get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_end_date").innerHTML  = day+'-'+x+'-'+year;
				 dojo.byId("lb_period").innerHTML = dijit.byId("period").get('value')+" "+dijit.byId('pay_every').attr('displayedValue');
				 dojo.byId("lb_loanamount").innerHTML = dijit.byId("total_amount").get('value')+' '+dijit.byId('currency_type').attr('displayedValue');
				 dojo.byId("lb_interest_rate").innerHTML = dijit.byId("interest_rate").get('value')+ ' %';
				 dojo.byId("lb_producttype").innerHTML = dijit.byId("product_id").attr('displayedValue')+" : "+$("#description").val();
				 dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt_num").get('value');
				 dojo.byId("lb_total_interest").innerHTML = data.total_interest;+' '+dijit.byId('currency_type').attr('displayedValue');
				 dojo.byId("lb_customername").innerHTML =dijit.byId('member').attr('displayedValue');
				 
						/*
				dojo.byId("lb_stu_id").innerHTML = dijit.byId("stu_id").value;
				dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value')+" - "+dijit.byId("en_name").get('value');
				dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
				dojo.byId("lb_session").innerHTML = dijit.byId('session').attr('displayedValue');
				dojo.byId("lb_hour").innerHTML = dijit.byId('study_hour').attr('displayedValue');
				dojo.byId("lb_dept").innerHTML = dijit.byId('dept').attr('displayedValue');
				dojo.byId("lb_grade").innerHTML = dijit.byId("grade").attr('displayedValue');
				dojo.byId("lb_tuitionfee").innerHTML ="$ "+dijit.byId('tuitionfee').get('value').toFixed(2);
				dojo.byId("lb_payment_term").innerHTML = dijit.byId("payment_term").attr('displayedValue');
				dojo.byId("lb_discount").innerHTML = dijit.byId("discount").get('value')+"%";
				dojo.byId("lb_remark").innerHTML ="$ "+ dijit.byId('remark').attr('value').toFixed(2);
				dojo.byId("lb_total").innerHTML ="$ "+dijit.byId('total').attr('value');
				dojo.byId("lb_books").innerHTML = "$ "+dijit.byId("books").get('value').toFixed(2);
				dojo.byId("lb_addmin_fee").innerHTML ="$ "+dijit.byId("addmin_fee").get('value').toFixed(2);
				dojo.byId("lb_remaining").innerHTML = "$ "+dijit.byId("remaining").get('value');
				
				 dojo.byId("lb_note").innerHTML = dijit.byId("not").get('value');
				 var d = dijit.byId("start_date").get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_start_date").innerHTML  = day+'-'+x+'-'+year;
				 var d = dijit.byId("end_date").get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_end_date").innerHTML  = day+'-'+x+'-'+year;*/
				//dijit.byId("terms").show();	
				
				//temp='';	
			      //fund_title=0;thead='';fund_title=0;
				 	/*	temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						temp+='<tr style="background:#ccc;"><th><?php //echo $tr->translate("NUM");?></th>';
						//temp+='<th><?php //echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						//temp+='<th><?php //echo $tr->translate("ចំនួន​ថ្ងៃ");?></th>';
						//temp+='<th><?php //echo $tr->translate("ការប្រាក់​ប្រចាំ​ថ្ងៃ");?></th>';
						//temp+='<th><?php //echo $tr->translate("ការប្រាក់​សរុប");?></th>';*/
				/*for(i=0;i<data.length;i++){
			        r++;
					    temp+='<tr><td align="center">'+r+'</td>';
						var myDate = new Date(data[i].date_payment);
						d = new Date(data[i].date_name);
						temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						temp+='<td>'+data[i].amount_day+'</td>';
						temp+='<td>'+dojo.number.format(data[i].dialy_amount,4)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].interest_amount,2)+'</td></tr>';
				 }*/
				//temp+='</table>';
				//dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("frm_client").show();
			},
			error: function(err) {
				alert(err);
			document.getElementsByClassName("overlay")[0].style.display="none";
			alert("You can not preview this loan number!");
			}
	   });
	}else{
		alert("You can not preview this loan numberssss!");
	}
}
    function checkValidateDate(){
    	/*debt_term = dijit.byId('pay_every').get('value');
		if(debt_term==1){
			term_d =1; 
		}else if(debt_term==2){
			term_d =7; 
		}else{
			term_d =30; 
		}
		
		collect_term = dijit.byId('collect_termtype').get('value');
		if(collect_term==1){
			term_c =1; 
		}else if(collect_term==2){
			term_c =7; 
		}else{
			term_c =30; 
		}
		debt_amount = dijit.byId('period').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if((collect_amount*term_c)>(debt_amount*term_d)){
			alert('<?php //echo $tr->translate("SMS_BORROW_FUND")?>');
			dijit.byId('collect_termtype').focus();
			return false;
		}
		return true;*/
     }
    function setDefaultPaymentAmount(){
    	/*amount_principal = dijit.byId('total_amount').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	
    	collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);
		interest_rate=dijit.byId('interest_rate').get('value')/100;
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		dijit.byId('amount_collect_pricipal').attr('value',amount_payment);*/
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		//saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', [] );
var client_number_store  = getDataStorefromJSON('id','name', [] );//getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->recieverlist));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		//changeCollectType();
	  });
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			//getLoanLevel(member);
			dijit.byId('customer_code').attr('value',member);
		}
}
	}, "member");

	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				popupcreditofficer();
			}else{
			}
	    }
		}, "co_id");
	 
	});
</script>
<script type="text/javascript">
function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
		dijit.byId('customer_code').reset();
		getLoanByBranch();
		getAllClientByBranch(branch_id);
		getAllClientNumberByBranch(branch_id);
}
var url_getclient = '<?php echo $this->url(array('module'=>'saving','controller'=>'customer','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
			//alert(err);
		}
	});
	
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'saving','controller'=>'customer','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('loan_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
function showloantype(){
}
function calCulateAdminFee(){
	/*p_income="<?php //echo $this->setting['adminfee']?>";
	t_admin=dijit.byId('total_amount').get('value');
	adminfee=(p_income*(t_admin/100));
	dijit.byId('loan_fee').attr('value',adminfee);*/
}
function CompareGraicePariod(){
	/*graice_pariod = dijit.byId('graice_pariod').get('value');
	period = dijit.byId('period').get('value');
	if(graice_pariod>=period){
		alert('<?php //echo $tr->translate("AMOUNT_GRAICEPARIOD_THEN_AMOUNT_LOAN")?>');
		dijit.byId('graice_pariod').attr('value',(period-1));
	}*/
}
function chechPaymentMethod(){
	/*method_id = dijit.byId('repayment_method').get('value');
	dojo.byId('lbl_payment').innerHTML="<?php //echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?>";
	/*dijit.byId('amount_collect_pricipal').attr('value',0);

	dijit.byId("amount_collect").set('readOnly',false);
	dijit.byId("collect_termtype").set('readOnly',false);
	if(method_id==6){
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
		dijit.byId('amount_collect').attr('value',1);
		dijit.byId('amount_collect').set('readOnly',true);
		
	}else if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId("amount_collect").set('readOnly',true);
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').attr('value',2);
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="<?php //echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
		dijit.byId('amount_collect_pricipal').attr('value','');
		dijit.byId('amount_collect_pricipal').focus();
		setDefaultPaymentAmount();
	}else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}*/
}
function changeGraicePeroid(){
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
	
}

var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add-newclient')); ?>';
function addNewClient(){
		dojo.xhrPost({
	    url: url_submit,	
		form: dojo.byId("form_client"),		    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('frm_client').reset(); 
			dijit.byId('frm_client').hide();
		},
		error: function() {
		alert("Your message could not be sent, please try again!.");
		}
	});
}

var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>
<?php 
// echo $this->frmpupopclient;
 //echo $this->frmPopupZone;
 //echo $this->frmPopupCommune;
 //echo $this->frmPopupDistrict;
 //echo $this->frmPopupVillage;
echo $this->frmpupoploantype;
?>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	date_release=dijit.byId("release_date").get('value');
	var a = new Date(date_release);
	
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	CalculateWidthdraw();
}
function calCulateEndDate(){
	
}

function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function CalculateWidthdraw(){
	acount_type = dijit.byId("account_type").get("value");
	dijit.byId("withdrawal").set("readOnly",false);
	if(acount_type==1){
      period_widthdraw = dijit.byId("period").get("value");
      dijit.byId("withdrawal").attr("value",period_widthdraw);
      dijit.byId("withdrawal").set("readOnly",true);
	}else{
	    dijit.byId("withdrawal").attr("value",1);
	    getFirstPayment();
	}
}

function getFirstPayment(){
	daterelease=dijit.byId("release_date").get('value');
	if(dijit.byId('account_type').get('value')==1){
		alert("value = 1");
		dijit.byId("first_payment").attr('value',dijit.byId('date_line').get('value'));
	}else{
		amount_date = dijit.byId('withdrawal').get("value");
		//alert("date_release"+date_release);
		var date = new Date(daterelease);
		mm = date.getMonth()+amount_date;
		 if(mm<10){
			 mm = "0"+mm;
		}
		 var dd = date.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 var y = date.getFullYear();
			var first_date = y + '-'+ mm + '-'+dd ;
         dijit.byId("first_payment").attr('value',first_date);
	}
}

////add preview loan

function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
}

function showPopupclient(){
	if(dijit.byId('branch_id')!=''){
		dijit.byId("frmpop_client").show();
	}else{
		alert('Please Select Branch First!');
		dijit.byId('branch_id').focus();
		}
}

var individual_client_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-client'));?>';
function addNewindividual(){
	if(dijit.byId('addclient').validate()){
	dojo.xhrPost({
		url:individual_client_url,	
		form:dojo.byId('addclient'),
		content:{
			'branch_id':dijit.byId('branch_id').get('value')
			},
		handleAs:"json",
		load: function(response) {
			dijit.byId('frmpop_client').hide();	
			var myNewItem = {					
					id: response.id,
					name: dijit.byId('name_en').get('value')+' - '+dijit.byId('name_kh').get('value'),
					branch_id: dijit.byId('branch_id').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);

			var myNewItem1 = {					
					id: response.id,
					name: response.client_code,
					branch_id: dijit.byId('branch_id').get('value'),
			};			
			addDataToSelectbox(dijit.byId('customer_code'), client_number_store, myNewItem1, response.id);		
			dijit.byId('addclient').reset();
	
		},
		error: function(err) {
		}
	});
 }	
}
function popupCheckCO(){
  
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>