<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_CO'));
?>	

<?php  $techer= $this->frm_co;?>
<script>
	dojo.require("dijit/form/DateTextBox");
	dojo.require("dijit/form/NumberTextBox");
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
					alert('Please Select Branch Name !!!');
					dijit.byId("branch_id").focus();
					return false;
	  			}
				if(dijit.byId("position").get("value")==""){
					alert("Please Select Position Name!!!");
					dijit.byId("position").focus();
					return false;
				}
				return true;
			} else {
				return false;
			}
</script>
<fieldset  style="background: #e0ebff">
<table width="100%" style="margin: 0 auto;">
	<legend class="mainblog"><strong><?php echo $tr->translate("EDIT_CO");?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CO_NAME")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("BRANCH")?></td>
							<td><?php  echo $techer->getElement('branch_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STAFF_CODE")?></td>
							<td><?php  echo $techer->getElement('co_id'); echo $techer->getElement('id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php  echo $techer->getElement('name_kh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN")?></td>
							<td><?php  echo $techer->getElement('first_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $techer->getElement('co_sex');?></td>
						</tr>
						
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("NATIONAL_ID")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("POSITION")?></td>
							<td><?php  echo $techer->getElement('position');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE")?></td>
							<td><?php  echo $techer->getElement('degree');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $techer->getElement('national_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("EMAIL")?></td>
							<td><?php  echo $techer->getElement('email');?></td>
						</tr> 
						<tr>
							<td><?php echo $tr->translate("FINGER_PRINT")?></td>
							<td><?php  echo $techer->getElement('figer_print_id');?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("ADDRESS")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
					  <tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $techer->getElement('tel');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("POB")?></td>
							<td><?php  echo $techer->getElement('pob');?></td>
						</tr>
					   <tr>
							<td><?php echo $tr->translate("CURRENT_ADDRESS")?></td>
							<td><?php  echo $techer->getElement('address');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEPARTMENT")?></td>
							<td><?php  echo $techer->getElement('department_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PICTURE")?></td>
							<td><?php  echo $techer->getElement('photo');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td colspan="6" style="border-bottom:1px solid #ccc;    background: none repeat scroll 0 0 #bbcff3;"><strong><?php echo $tr->translate("SALARY_INFO");?></strong></td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CONTRACT_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("CONTRACT_NO")?></td>
							<td><?php  echo $techer->getElement('contract_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE_START_WORK")?></td>
							<td><?php  echo $techer->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE_END_CONTRACT")?></td>
							<td><?php  echo $techer->getElement('end_date');?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("WORK_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("SHIFT")?></td>
							<td><?php  echo $techer->getElement('shift');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("WORKING_TIME")?></td>
							<td><?php  echo $techer->getElement('workingtime');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ANNUAL_LIVES")?></td>
							<td><?php  echo $techer->getElement('annual_lives');?></td>
						</tr>
						 
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("SALARY_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("BASIC_SALARY")?></td>
							<td><?php  echo $techer->getElement('basic_salary');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $techer->getElement('note');?></td>
						</tr>
						
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td colspan="3">
				<div style="text-align: center; margin: 10px 0px;">
						<input type="submit"  value="save_close" name="save_close" id="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						 
				</div>
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
	function calculateDay(){
		start_date = dijit.byId("start_date").get('value');
		var a=new Date(start_date);
		m=a.getMonth()+1;
		d=a.getDate();
		if(d<15){
			m=m-1;
		}
		t_day=18*(12-m)/12;
		dijit.byId('annual_lives').attr('value',t_day);
	}
	var url_staffcode = '<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'getstaffcode')); ?>';
	function getStaffCode(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('co_id').attr('value','');
		if(branch_id==''){
			alert('Please Select Branch');
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_staffcode,	
			content:{ 
			    'branch_id':branch_id,
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('co_id').attr('value',data);
			},
			error: function(err) {
			}
		});
	}
</script>