<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title> <?php echo $tr->translate("COLLECTERALL_TYPE")?></title>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'pawnproduct','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("COLLECTERALL_TYPE")?></strong></legend>
					<table cellspacing="2"  width="100%" >
						<tr>
							<td width="40%">
								<table width="100%">
									<tr>
										<td><?php echo $tr->translate("NAME_KH")?></td>
										<td><?php echo $frm->getElement('title_kh')?></td>	
									</tr>
									<tr>
									    <td><?php echo $tr->translate("NAME_ENG")?></td>
										<td><?php echo $frm->getElement('title_en')?></td>	
								   </tr>
								   <tr>
								        <td><?php echo $tr->translate("DATE")?></td>
										<td><?php echo $frm->getElement('date')?></td>
								   </tr>
								   <tr>
								   		<td><?php echo $tr->translate("STATUS")?></td>
										<td><?php echo $frm->getElement('status')?></td>
								   </tr>
								</table>							
							</td>
							<td width="60%">
								<table width="100%">
									<tr>					        
										<td style="white-space:nowrap;"><?php echo $tr->translate("ពត៍មានលម្អិត")?></td>
										<td><?php echo $frm->getElement('description')?></td>
									</tr>
								</table>
							</td>
						</tr>						
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="reset" iconClass="dijitIconClear" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button"/>
			<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />
			<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />
		</td>
	</tr>	
</table>
</form>