<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('DEPARMENT_INFO'));
?>	
<?php  $frm = $this->frm_department;?>
<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="50%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend class="mainblog" align="center"><strong><?php echo $tr->translate("EDIT_DEPARTMENT_INFO");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>
							<?php echo $frm->getElement('id');?>
							<?php echo $tr->translate("DEPARTMENT_KH")?></td>
							<td><?php  echo $frm->getElement('department_kh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEPARTMENT_EN")?></td>
							<td><?php  echo $frm->getElement('department_en');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
						     <td></td>
						     <td>
						     	<input type="submit" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
						     </td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>