<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DEPARMENT_INFO"));
$frm = $this->frm_department;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'department','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td><?php echo $frm->getElement('status_search');?></td>
		   <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	   </tr>
   </table>
   <?php echo $this->list;?>
</form>
