<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$CapitalCapital= $this->CapitalCapital;
$frm = $this->frm_search;
$db  = new Report_Model_DbTable_DbExchanges();
// print_r($this->list_search);exit();
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_LOAN_XCHANGE");?></title>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post" action="">
<table style="font-family: 'Khmer OS Content';width:28.2cm;margin:0 auto;" >
	<tr>
		<td>
			<select class="fullside" style="text-align: left;"  name="agent_id" id="agent_id" dojoType="dijit.form.FilteringSelect" required="true">
				<option value="-1"><?php echo $tr->translate("All Agent");?></option> 
				<?php foreach ($this->users as $key => $u) : ?>
					<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->list_end_date['agent_id'])?"selected":"";?>><?php echo  $u['name'];?></option>
				<?php endforeach;?> 
			</select><!-- onchange="document.frmlist_mt.submit();" -->
		</td>
		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<style>
.noneprint{
	display: table-cell !important; 
}
</style>
<div style=" width:26cm;min-height:20cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<div id="divPrint">
<style>
	.style{
		line-height: 20px;
		font-family: 'Khmer OS Battambang';
	}
	table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
	th{padding: 5px;}
		a.repLink.btn {
		    color: #008;
		    font-weight: 600;
		}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	     <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("CAPITAL SUMMARY");?></li>
                			<li style="text-align:center; font-size:13px; font-family: 'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                	</td>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 12px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
                 <thead>
				 <tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Times New Roman','Khmer OS Battambang';">
                    <td ><?php echo $tr->translate("NUM");?></td>
                    <td ><?php echo $tr->translate("DATE");?></td>
                    <td ><?php echo $tr->translate("Agent Name");?></td>
                    <td ><?php echo $tr->translate("Amount");?></td>
                    <td ><?php echo $tr->translate("Currency");?></td>
                </tr>
				</thead>
                <?php $i=0; foreach ($CapitalCapital as $row){ $i++;?>
               <tr style="font-size: 12px;" align="left">
               		<td style="text-align: center;"><?php echo $i;?></td>
               		<td align="center">&nbsp;<?php echo date("d/M/Y",strtotime($row['for_date']));?></td>
               		<td>&nbsp;<?php echo $row['agentName']?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($row['amount'],2);?>&nbsp;</td>
               		<td align="center">&nbsp;<?php echo $row['currencytitleKH']." (".$row['symbol'].")"?>&nbsp;</td>
               </tr>
               <?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Times New Roman','Khmer OS Battambang';">
                    <td ><?php //echo $tr->translate("NUM");?></td>
                    <td ><?php echo $tr->translate("ដើមទុនដាក់ចូល");?></td>
                    <td ><?php echo $tr->translate("ដើមទុនដកចេញ");?></td>
                    <td ><?php echo $tr->translate("ទិញចូល");?></td>
                    <td ><?php echo $tr->translate("លក់ចេញ");?></td>
                    <td ><?php echo $tr->translate("ដើមទុននៅសល់");?></td>
                </tr>
                <?php foreach ($this->currencyEx as $cur){ 
	                $totalbuy= $db->getTotalExchangeBuyCurrency($cur['symbol'], $this->list_end_date);
	                $totalSell = $db->getTotalExchangeSellCurrency($cur['symbol'], $this->list_end_date);
	                $totalWithDrawal = $db->getTotalWithdrawalByCurrency($cur['CurrID'], $this->list_end_date);
	                $totalDeposite = $db->getTotalDepositeByCurrency($cur['CurrID'], $this->list_end_date);
	                
	                $total = ($totalDeposite + $totalWithDrawal + $totalbuy) - $totalSell;
                	?>
               <tr style="font-size: 12px;" align="left">
               		<td style="text-align: center;"><?php echo $cur['CurrTitleKH']." (".$cur['symbol'].")";?></td>
               		<td align="right">&nbsp;<?php echo number_format($totalDeposite,2);?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($totalWithDrawal,2);?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($totalbuy,2);?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($totalSell,2);?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($total,2);?>&nbsp;</td>
               </tr>
               <?php }?>
             </table>
       		<br />
       		 <table align="center" width="100%">
			 <thead>
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</thead>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>