<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$xchange= $this->Loanxchange_list;
$frm = $this->frm_search;
$client = $this->client;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_LOAN_XCHANGE");?></title>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content';width:28.2cm;margin:0 auto;" >
	<tr>
   		<td><?php echo $frm->getElement("adv_search");?></td>
   		<!-- 
   		<td><?php //echo $frm->getElement('branch_id');?></td>
   		<td><?php //echo $frm->getElement('client_name');?></td>
   		 -->
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   
   	</tr>
</table>
</form>
<style>
.noneprint{
	display: table-cell !important; 
}
</style>
<div style=" width:26cm;min-height:20cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<div id="divPrint">
<style>
.style{
	line-height: 20px;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
		a.repLink.btn {
		    color: #008;
		    font-weight: 600;
		}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	     <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_XCHANGE");?></li>
                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                	</td>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 12px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
                 <thead>
				 <tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Khmer OS Content'">
                    <th ><?php echo $tr->translate("NUM");?></th>
                    <!-- 
                    <th ><?php //echo $tr->translate("BRANCH_NAME");?></th>
                    <th ><?php //echo $tr->translate("CUSTOMER_NAME");?></th>
                     -->
                    <th ><?php echo $tr->translate("RECIEPT_NO");?></th>
                    <th ><?php echo $tr->translate("Exchage To");?></th>
                    <th ><?php echo $tr->translate("Exchage Amount");?></th>
                    <th ><?php echo $tr->translate("EXCHANGE_RATE");?></th>
                    <th ><?php echo $tr->translate("Exchage Amount Received");?></th>
                    <th ><?php echo $tr->translate("RECIEVED_AMOUNT");?></th>
                    <th ><?php echo $tr->translate("RETURN_AMOUNT");?></th>
                    <th ><?php echo $tr->translate("DATE");?></th>
                    <th ><?php echo $tr->translate("IS_SPACIAL_CUSTOMER");?></th>   
                    <th class="noneprint" style="display: none;"><?php //echo $tr->translate("EDIT");?></th>                 
                </tr>
				</thead>
                <?php foreach ($xchange as $row){ $i=1;?>
               <tr style="font-size: 12px;" align="left">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<!-- 
               		<td>&nbsp;<?php //echo $row['branch_name']?></td>
               		<td>&nbsp;<?php //echo $row['client_name']?>&nbsp;</td>
               		 -->
               		<td align="center">&nbsp;<?php echo $row['recieptNo']?>&nbsp;</td>
               		<td align="center">&nbsp;<?php echo $row['from_to']?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo $row['fromAmount'].$row['fromAmountType'];?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo $row['rate'].$row['toAmountType'];?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo $row['toAmount'].$row['toAmountType'];?>&nbsp;</td>
               		
               		<td align="right">&nbsp;<?php echo $row['recievedAmount'].$row['fromAmountType'];?>&nbsp;</td>
					<td align="right">&nbsp;<?php echo $row['changedAmount'].$row['fromAmountType'];?>&nbsp;</td>
               		<td align="center">&nbsp;<?php echo date('d-m-Y',strtotime($row['statusDate']))?>&nbsp;</td>
               		
               		<td>&nbsp;<?php echo ($row['specail_customer']==1)?"Yes":"No"?>&nbsp;</td>
               		<td class="noneprint" style="display: none;" align="left">
               			<a class="repLink btn" target="_blank" href="<?php echo $this->url(array("module"=>'report',"controller"=>"exchanges","action"=>'exchangereceipt','id'=>$row['id']))?>" title="<?php echo $tr->translate("Exchange Receipt");?>"><?php echo $tr->translate("Exchange Receipt");?></a>
               		</td>
               </tr>
               <?php }?>
            </table>
       		<br />
       		<?php if (!empty($this->buyin)) {?>
       		<table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
       			<tr>
       				<td colspan="<?php echo count($this->buyin);?>" style="border-left: solid 1px #fff;border-top: solid 1px #fff; border-right: solid 1px #fff;">ទិញចូល</td>
       			</tr>
       			<tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Khmer OS Content'">
       				<?php foreach ($this->buyin as $rs){?>
       				<td><?php echo $rs['fromTxtType']."(".$row['fromAmountType'].")"?></td>
       				<?php }?>
       			</tr>
       			<tr style="font-size: 12px;" align="left">
       				<?php foreach ($this->buyin as $rs){?>
       				<td align="center"><?php echo number_format($rs['totalFromAmount'],2)."(".$row['fromAmountType'].")"?></td>
       				<?php }?>
       			</tr>
            </table>
            <?php }?>
            <br />
       		<?php if (!empty($this->sellout)) {?>
       		<table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
       			<tr>
       				<td colspan="<?php echo count($this->sellout);?>" style="border-left: solid 1px #fff;border-top: solid 1px #fff; border-right: solid 1px #fff;">លក់ចេញ</td>
       			</tr>
       			<tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Khmer OS Content'">
       				<?php foreach ($this->buyin as $rs){?>
       				<td><?php echo $rs['toTxtType']."(".$row['toAmountType'].")"?></td>
       				<?php }?>
       			</tr>
       			<tr style="font-size: 12px;" align="left">
       				<?php foreach ($this->sellout as $rs){?>
       				<td align="center"><?php echo number_format($rs['totalToAmount'],2)."(".$row['toAmountType'].")"?></td>
       				<?php }?>
       			</tr>
            </table>
            <?php }?>
       		<br />
       		 <table align="center" width="100%">
			 <thead>
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</thead>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>