<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$dailyCurrentCapital= $this->dailyCurrentCapital;
$frm = $this->frm_search;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_LOAN_XCHANGE");?></title>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content';width:28.2cm;margin:0 auto;" >
	<tr>
		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<style>
.noneprint{
	display: table-cell !important; 
}
</style>
<div style=" width:26cm;min-height:20cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<div id="divPrint">
<style>
	.style{
		line-height: 20px;
		font-family: 'Khmer OS Battambang';
	}
	table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
	th{padding: 5px;}
		a.repLink.btn {
		    color: #008;
		    font-weight: 600;
		}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	     <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Report Exchange Current Capital");?></li>
                			<li style="text-align:center; font-size:13px; font-family: 'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                	</td>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
                 <thead>
				 <tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Times New Roman','Khmer OS Battambang';">
                    <td ><?php echo $tr->translate("NUM");?></td>
                    <td ><?php echo $tr->translate("DATE");?></td>
                    <td ><?php echo $tr->translate("Agent Name");?></td>
                    <td ><?php echo $tr->translate("Amount");?></td>
                    <td ><?php echo $tr->translate("Currency");?></td>
                </tr>
				</thead>
                <?php $i=0; foreach ($dailyCurrentCapital as $row){ $i++;?>
               <tr style="font-size: 12px;" align="left">
               		<td style="text-align: center;"><?php echo $i;?></td>
               		<td align="center">&nbsp;<?php echo date("d/M/Y",strtotime($row['for_date']));?></td>
               		<td>&nbsp;<?php echo $row['agentName']?>&nbsp;</td>
               		<td align="right">&nbsp;<?php echo number_format($row['amount'],2);?>&nbsp;</td>
               		<td align="center">&nbsp;<?php echo $row['currTitleKH']." (".$row['symbol'].")"?>&nbsp;</td>
               </tr>
               <?php }?>
            </table>
       		<br />
       		<?php if (!empty($this->totalDailyCurrentCapital)){?>
       		 <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
       		 	 <tr class="style" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 24px;font-size:12px; font-family: 'Times New Roman','Khmer OS Battambang';">
                   <td ><?php echo $tr->translate("Currency");?></td>
                   <?php foreach ($this->totalDailyCurrentCapital as $total){?>
                    <td ><?php echo $total['currTitleKH']." (".$total['symbol'].")"?></td>
                    <?php }?>
                </tr>
                <tr style="font-size: 12px;" align="left">
                	<td align="center" ><?php echo $tr->translate("TOTAL");?></td>
                 <?php foreach ($this->totalDailyCurrentCapital as $total){?>
               		 <td align="center">&nbsp;<?php echo number_format($total['total'],2);?>&nbsp;</td>
               	 <?php }?>
                </tr>
             </table>
             <?php }?>
       		<br />
       		 <table align="center" width="100%">
			 <thead>
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</thead>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>