<?php
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('TRANSFER_CO')); 
	echo $this->headTitle();
	$frm = $this->frm_transfer;

?>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
  if(this.validate()) {
    if(dijit.byId('branch_name').get('value')==''){
     alert('Please Select Branch');
     dijit.byId('branch_name').focus();
     return false;
   	}
	if(dijit.byId('co_code').get('value')==''){
     alert('Please Select Co code');
     dijit.byId('co_code').focus();
     return false;
   	}
    if(dijit.byId('name_co').get('value')==''){
     alert('Please Select Name Co');
     dijit.byId('name_co').focus();
     return false;
   	}

   if(dijit.byId('loan_number').get('value')==''){
     alert('Please Select Loan Number');
     dijit.byId('loan_number').focus();
     return false;
   	}
    if(dijit.byId('loan_client').get('value')==''){
     alert('Please Select Client');
     dijit.byId('loan_client').focus();
     return false;
   	}
    return true;
   }else {
    return false;
   }
</script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<fieldset  style="background: #e0ebff">
<table cellspacing="10" class='fullside'>
		<legend class="mainblog" align="center"><strong><?php echo $tr->translate("EDIT_TRANSFER_CO")?></strong></legend>
		<tr>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
			    <tr>
					<td><?php echo $tr->translate("BRANCH_NAME")?></td>
					<td><?php  echo $frm->getElement('branch_name');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("CO_CODE")?></td>
					<td><?php  echo $frm->getElement('co_code');?></td>
			    </tr>
			    <tr>
			  		 <td><?php echo $tr->translate("CO_NAME")?></td>
					 <td><?php  echo $frm->getElement('name_co');?></td>
			    </tr>
			    <tr>
			    	 <td><?php echo $tr->translate("DATE")?></td>
					 <td><?php  echo $frm->getElement('Date');?></td>
			    </tr>
			</table>
		</fieldset>	
		</td>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('CO_INFO');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
			 	<tr >
					<td><?php echo $tr->translate("LOAN_NO")?></td>
					<td><?php  echo $frm->getElement('loan_number');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
					<td><?php  echo $frm->getElement('loan_client');?></td>
				</tr>
			    <tr>
					<td><?php echo $tr->translate("NOTE")?></td>
					<td><?php  echo $frm->getElement('Note');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("STATUS")?></td>
					<td><?php  echo $frm->getElement('status');?></td>
			    </tr>
			</table>
		</fieldset>
		</td>
		</tr>			 
		<tr>
		<td align="center" colspan="2">
			<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("name_co").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("loan_client").get('value');		
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}else if(type==5){
			to = dijit.byId("loan_number").get('value');
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}
	}
</script>
