<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('PURCHASE')); 
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$purchase = $this->purchase;
	$proid=0;
	if (!empty($this->purchaseDetail)){
		foreach ($this->purchaseDetail as $rs){
			$proid = $rs['pro_id'];
		}
	}
?>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/Dialog"]);
   </script>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	var pro_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));//print_r(Zend_Json::encode($this->product));?> );
	var pro_cate_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->cat_rows));?> );
	var branch_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->bran_name));?> );
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			store: pro_store,
			autoComplete: true,                        
			id: "pro_id",
			name: "pro_id",  
			class: 'fullside', 
			value:'<?php echo $proid?>',
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_PRODUCT");?>",          
			onChange: function() {  
				pro_id   = dijit.byId('pro_id').get('value');
				if(pro_id==-1){
					 window.open('<?php echo $this->baseUrl()."/installment/product/add"?>', '_blank');
				}else{
					//addRow();
				}
			}
		}, "pro_id");
		
		new dijit.form.FilteringSelect({
		store: branch_store,autoComplete: false,
		queryExpr: "*${0}*",
		id: "branch",
		name: "branch",           
		class: "fullside", 
		value:'<?php echo $purchase['branch_id'];?>',
		placeHolder:"<?php echo $tr->translate("SELECT_LOCATION");?>​",          
		onChange: function() {  
			branch_id = dijit.byId('branch').get('value');
			getAllProduct();
			if(branch_id==-1){
				dijit.byId("popup_add_branch").show();
				}
			}
		}, "branch");

		new dijit.form.FilteringSelect({
			store: pro_cate_store,autoComplete: false,
			queryExpr: "*${0}*",                      
		    id: "category_id",
		    name: "category_id",  
		    tabindex: "1",         
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_CATEGORY");?>​", 
		    onChange: function() {          
		    	category_id = dijit.byId('category_id').get('value');
			    if(category_id==-1){
			   		dijit.byId("popup_pro_cate").show();
			    }
		   }
		}, "category_id");
		isNewCustomer();
		isNewBuyer();
		getSuplierInfo();
		getBuyerInfo();
		getAllProduct();
		//initailize();
	});	
</script>
<form id='suspend_service' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				
                dijit.byId("save_close").attr("disabled",true);
			//	dijit.byId("save_new").attr("disabled",true);
				return true;
			} else {
				return false;
			}
</script>
		<table style=" width: 100%">
			<tr>
				<td valign="top" style="white-space: nowrap;" width="33%">
					<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_PURCHASE");?>​</strong></legend>
					<table style="margin: 0 auto;" cellspacing="5">
							<tr style="display: none;">
								<td><strong><?php //echo $tr->translate("OLD_SUPPLIER");?>:</strong></td>
								<td><input type="checkbox" checked="checked" name="is_new_cu" id="is_new_cu" value="1" onClick="isNewCustomer()" >
								<input type="hidden" dojoType="dijit.form.TextBox" name="id"  id="id" value="<?php echo $purchase['id'] ?>" class="fullside" />
								</td>
							</tr>
							<tr>
							   <td><?php echo $tr->translate("SUPPLIER_NAME");?>*</td>
							   <td>
							   		<span id="new_cu">
							   			<input type="text" dojoType="dijit.form.ValidationTextBox" name="supplier_name"  id="supplier_name" value="" class="fullside" required="required">
							   		</span>
							   		<span id="old_cu">
							   			<select dojoType='dijit.form.FilteringSelect'  id="sup_id" name="sup_id" onChange="getSuplierInfo();" class="fullside" required="false"​​  placeholder="ជ្រើសរើស ឈ្មោះអ្នកផ្គត់ផ្គង់">
								   			<option></option>
								   			<?php if(!empty($this->sup_ids)) foreach($this->sup_ids As $rs_sup){?>
								   			<option value="<?php echo $rs_sup['id'];?>" <?php if ($rs_sup['id']==$purchase['supplier_id']){ echo 'selected="selected"';}?>><?php echo $rs_sup['sup_name'];?></option>
								   			<?php }?>
							   			</select>
							   		</span>
							   		
							   	</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SEX");?></td>
							  	<td>
							  	<select class="fullside" id="sex" name="sex" dojoType="dijit.form.FilteringSelect" >
							  		<?php foreach ($this->sex as $ss){?>
								  		<?php if ($ss['key_code']!=3){?>
								  		<option value="<?php echo $ss['key_code'];?>"><?php echo $ss['name_en'];?></option>
								  		<?php }?>
							  		<?php }?>
							  	</select>
							  </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("AGE");?></td>
							  	<td><input type="text" dojoType="dijit.form.TextBox" name="age"  id="age" value="" class="fullside" ></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("JOB");?></td>
							  	<td><input type="text" dojoType="dijit.form.TextBox" name="occupation"  id="occupation" value="" class="fullside" ></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Tel");?></td>
							  	<td><input type="text" dojoType="dijit.form.TextBox" name="phone"  id="phone" value="" class="fullside" ></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("EMAIL");?></td>
					   			<td><input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="email" name="email" class="fullside" /></td>
					   		</tr>
					   		<tr>	
					   			<td><?php echo $tr->translate("ADDRESS");?></td>
					   			<td><input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="address" name="address" class="fullside" /></td>
							</tr>
							<tr>
								<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							</tr>
						</table>
					</fieldset>
				</td>
				<td width="33%" valign="top">
					<fieldset>
						<legend align="center"><strong><?php echo $tr->translate("BUYER");?>​</strong></legend>
						<table style="margin: 0 auto;" cellspacing="5">
							<tr >
								<td><strong><?php echo $tr->translate("OLD_BUYER");?>:</strong></td>
								<td><input type="checkbox" checked="checked"  name="is_new_buy" id="is_new_buy" value="1" onClick="isNewBuyer()" ></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("BUYER_NAME");?>*</td>
							    <td>
							    	<span id="new_buyer">
							    	<input type="text" dojoType="dijit.form.ValidationTextBox" name="buyerName"  id="buyerName" value="" class="fullside" required="required">
							   		</span>
							   		<span id="old_buyer">
							   			<select dojoType='dijit.form.FilteringSelect'  id="buyer_id" name="buyer_id" onChange="getBuyerInfo();" class="fullside" required="false"​​  placeholder="ជ្រើសរើស ឈ្មោះអ្នកផ្គត់ផ្គង់">
								   			<option></option>
								   			<?php if(!empty($this->buyer_ids)) foreach($this->buyer_ids As $rs_sup){?>
								   			<option value="<?php echo $rs_sup['id'];?>" <?php if ($rs_sup['id']==$purchase['buyer_id']){ echo 'selected="selected"';}?>><?php echo $rs_sup['buyer_name'];?></option>
								   			<?php }?>
							   			</select>
							   		</span>
							    </td>
							</tr>
							<tr>
								<td style="width: 160px"><strong><?php echo $tr->translate("JOB");?></strong></td>
								<td><input type="text" dojoType="dijit.form.TextBox"   name="buyOccupation"  id="buyOccupation" value="" class="fullside" ></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ADDRESS");?></td>
								<td><input type="text" dojoType="dijit.form.TextBox"   name="buyAddress"  id="buyAddress" value="" class="fullside" ></td>
							</tr>
						</table>
					</fieldset>
					<fieldset>
						<legend align="center"><strong><?php echo $tr->translate("ADD_PURCHASE");?>​</strong></legend>
						<table style="margin: 0 auto;" cellspacing="5">
							<tr>
								<td><?php echo $tr->translate("BRANCH");?>*</td>
							    <td><input id="branch"/></td>
							</tr>
							<tr>
								<td style="width: 160px"><strong><?php echo $tr->translate("DATE");?></strong></td>
								<td><input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="purchase_date" name="purchase_date" value="<?php echo date("Y-m-d",strtotime($purchase['date']));?>" type="text">
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("INVOICE_NO");?></td>
								<td><input type="text" dojoType="dijit.form.TextBox"  readonly="readonly" name="purchase_no"  id="purchase_no" value="<?php echo $purchase['invoice_no'];;?>" class="fullside" ></td>
							</tr>
						</table>
					</fieldset>
				</td>
				<td width="33%" valign="top">
					<fieldset>
						<legend align="center"><strong><?php echo $tr->translate("PRODUCT");?>​</strong></legend>
						<?php $countId= count($this->purchaseDetail);?>
						<table style="margin: 0 auto;" cellspacing="5">
						<?php if ($countId==1) foreach ($this->purchaseDetail as $pro){?>
							<tr>
								<td><?php echo $tr->translate("ITEM_NAME");?>
								<input dojoType="dijit.form.TextBox" class="fullside"  name="detailId" id="detailId" value="<?php echo $pro['id'];?>" type="hidden">
								</td>
								<td colspan="1"><input  id="pro_id" name="pro_id" />
								<input type="button" onclick="getAllProduct();" name="refresh" id="refresh" value="<?php echo $tr->translate('REFESH');?>" label="<?php echo $tr->translate('REFESH');?>"  dojoType="dijit.form.Button"  />
								</td>
							</tr>
							<tr>
						 		<td><?php echo $tr->translate('លេខតួ');?></td>
						 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="frame" id="frame" value="<?php echo $pro['frame'];?>" type="text"></td>
						 	</tr>
						 	<tr>
						 		<td><?php echo $tr->translate('លេខម៉ាស៊ីន');?></td>
						 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="engine" id="engine" value="<?php echo $pro['engine'];?>" type="text"></td>
						 	</tr>
						 	<tr>
						 		<td><?php echo $tr->translate('ពណ៌');?></td>
						 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="color" id="color" value="<?php echo $pro['color'];?>" type="text"></td>
						 	</tr>
							<tr>
						 		<td><?php echo $tr->translate('PRICE');?></td>
						 		<td><input dojoType="dijit.form.NumberTextBox" class="fullside" name="price" id="price" value="<?php echo $pro['price'];?>" type="text"></td>
						 	</tr>
						 	<tr>
						 		<td><strong><?php echo $tr->translate('ស្លាកលេខ');?></strong></td>
						 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="frame_no" id="frame_no" value="<?php echo $pro['frame_no'];?>" type="text"></td>
						 	</tr>
						 	<tr>
						 		<td><strong><?php echo $tr->translate('NOTE');?></strong></td>
						 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="note" id="note" value="<?php echo $pro['note'];?>" type="text"></td>
						 	</tr>
					 	<?php }?>
						</table>
					</fieldset>
				</td>
			</tr>
		  <tr>
			<td colspan="2" align="center">
				<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
				<input type="submit"  name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVECLOSE');?>"  dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconSave" />
				</td>
				<!--onclick="submitDataClose();"  -->
		</tr>
		<tr>
			<td colspan="2">
				<table id="table_row" border="1" style="width:100%;border-collapse: collapse; border:1px solid #ccc;">
					<tr id="head-title" class="head-td" align="right"></tr>
				</table>
			</td>
		  </tr>
		</table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_pro_cate" >
		<form style="background-color: buttonface; " id='frm_add_pro_cate' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate("Add Product Category");?></legend>
						<table style="margin: 0 auto; width: 95%;" cellspacing="5">
							<tr>
								<td style="width:100px"><?php echo $tr->translate("Name");?></td>
								<td><input class="fullside"  dojoType="dijit.form.ValidationTextBox" name="title" id="title" type="text" required="required" /></td>
							</tr>
							<tr>
								<td colspan="2" align="center">
									<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialog();"/>
									<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addProCate();"/>
								</td>
							</tr>
						</table>
						</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
var url_getproduct = '<?php echo $this->url(array('module'=>'installment','controller'=>'product','action'=>'getproductbybranch')); ?>';
var firstreload=0;
function getAllProduct(){
	branch_id = dijit.byId('branch').get('value');
	if(branch_id<0 || branch_id==''){
	      return false;
	}
	loadingBlock();
	dojo.xhrPost({
		url:url_getproduct,	
		content:{ 
		   'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			pro_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('pro_id').set('store', pro_store);
		    dijit.byId('pro_id').reset();
		    if(firstreload==0){
			    dijit.byId("pro_id").attr("value",'<?php echo $proid?>');
			    firstreload=1;
		    }
		    HideloadingBlock();
		},
		error: function(err) {
		}
	});
}

var template = '';
var product_name = '<?php //echo $this->product; ?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
	label_proname = dijit.byId("pro_id").attr('displayedValue');
	pro_id=dijit.byId("pro_id").get("value");
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("ITEM_NAME");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("QTY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("UNIT_PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMT_PAY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="15px" align="center"  >'+no+'</td>';
			template+='<td width="20%">&nbsp;'+label_proname+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="product_name_'+col+'" name="product_name_'+col+'" value="'+pro_id+'" /></td>';
			//template+='<td><select style="width:100%;"  dojoType="dijit.form.FilteringSelect" id="product_name_'+col+'" name="product_name_'+col+'" onChange="sumAmountDue();">'+''+'</select></td>';			

			template+='<td> <input type="text" required="true" name="qty_'+col+'" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text" required="true" name="cost_'+col+'" id="cost_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text"   name="amount_'+col+'" id="amount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;"  readOnly="true"/></td>';
			template+='<td> <input type="text"  name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

 function initailize(){
	 <?php if (!empty($this->purchaseDetail)) foreach ($this->purchaseDetail as $pud){?>
	 col++;no++;
	 template='';
	 if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("ITEM_NAME");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("QTY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("UNIT_PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMT_PAY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="15px" align="center"  >'+no+'</td>';
			template+='<td width="20%">&nbsp;<?php echo $pud['item_name']?><input type="hidden" dojoType="dijit.form.TextBox" required="true" id="product_name_'+col+'" name="product_name_'+col+'" value="<?php echo $pud['pro_id']?>" /></td>';
			//template+='<td><select style="width:100%;"  dojoType="dijit.form.FilteringSelect" id="product_name_'+col+'" name="product_name_'+col+'" onChange="sumAmountDue();">'+''+'</select></td>';			

			template+='<td> <input type="text" required="true" value="<?php echo $pud['qty']?>" name="qty_'+col+'" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text" value="<?php echo $pud['cost']?>" required="true" name="cost_'+col+'" id="cost_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text"  value="<?php echo $pud['amount']?>" name="amount_'+col+'" id="amount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;"  readOnly="true"/></td>';
			template+='<td> <input type="text"  name="note_'+col+'" id="note_'+col+'" value="<?php echo $pud['note']?>" dojoType="dijit.form.TextBox" style="width:100%;" /><input type="hidden" dojoType="dijit.form.TextBox" name="iddetail'+col+'"  id="iddetail'+col+'" value="<?php echo $pud['id'] ?>" class="fullside" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	 <?php }?>
 }
var url_getsuplier = "<?php echo $this->url(array('module'=>'installment','controller'=>'retailpurchase','action'=>'get-supplier-info')); ?>";
function getSuplierInfo(){
			sup_id = dijit.byId('sup_id').get('value');
			if(sup_id !=''){
				dojo.xhrPost({
					url:url_getsuplier,
					content:{
						'sup_id':sup_id
						},
					handleAs:"json",
					load: function(data) {
						dijit.byId("supplier_name").attr("value",data.sup_name);
						//dijit.byId("sex").attr("value",data.sex);
						dijit.byId("phone").attr("value",data.tel);
						//dijit.byId("email").attr("value",data.email);
						dijit.byId("address").attr("value",data.address);
						dijit.byId("age").attr("value",data.age);
						dijit.byId("occupation").attr("value",data.occupation);
						dijit.byId("sex").attr("value",data.sex);
					},
					error: function(err) {
						alert(err);
					}
				});
			}
}
var url_getbuyer = "<?php echo $this->url(array('module'=>'installment','controller'=>'retailpurchase','action'=>'getbuyerinfo')); ?>";
function getBuyerInfo(){
	buyer_id = dijit.byId('buyer_id').get('value');
		if(sup_id !=''){
			dojo.xhrPost({
				url:url_getbuyer,
				content:{
					'buyer_id':buyer_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("buyerName").attr("value",data.buyer_name);
					dijit.byId("buyOccupation").attr("value",data.occupation);
					dijit.byId("buyAddress").attr("value",data.address);
				},
				error: function(err) {
					alert(err);
				}
			});
		}
}
function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		sumAmountDue();
}
 
function getTotalePricePro(row){
	
	qty_id=dijit.byId('qty_'+row).get('value');
	cost_id=dijit.byId('cost_'+row).get('value');
	amount=qty_id*cost_id;
	dijit.byId('amount_'+row).attr('value',amount);
}
function isNewCustomer(){
	is_new = $('#is_new_cu').val();
	if($('#is_new_cu').is(':checked')){
		$('#old_cu').show();
		$('#new_cu').hide();
		dijit.byId('supplier_name').attr('required', false);
	}else{
		$('#old_cu').hide();
		$('#new_cu').show();
		dijit.byId('supplier_name').attr('required', true);
	}
}
function isNewBuyer(){
	is_new = $('#is_new_buy').val();
	if($('#is_new_buy').is(':checked')){
		$('#old_buyer').show();
		$('#new_buyer').hide();
		dijit.byId('buyerName').attr('required', false);
	}else{
		$('#old_buyer').hide();
		$('#new_buyer').show();
		dijit.byId('buyerName').attr('required', true);
	}
}
function sumAmountDue() {
	t=0;
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0; i<arrays.length; i++){
			t+=dijit.byId('amount_'+arrays[i]).get('value');
		}
		dijit.byId('amount_due').attr('value',t);
		
}

var url_add_pro_cate = '<?php echo $this->url(array("module"=>"accounting","controller"=>"Product","action"=>"add-new-pro-cate")); ?>';
function addProCate(){
	if(dijit.byId('frm_add_pro_cate').validate()){
	dojo.xhrPost({
		url:url_add_pro_cate,
		form: dojo.byId("frm_add_pro_cate"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
				     id: data,
					 name: dijit.byId('title').get('value')
				};
		 	addDataToSelectbox(dijit.byId('category_id'), pro_cate_store, Itemmake, data);
		    dijit.byId('frm_add_pro_cate').reset();
		    dijit.byId("popup_pro_cate").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
	}
}
var b_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->branchopt));?> );
var url_addbranch = '<?php echo $this->url(array('module'=>'global','controller'=>'branch','action'=>'addbranch')); ?>';
	function addBranch(){
		if(dijit.byId('frm_addbranch').validate()){
		dojo.xhrPost({
				url:url_addbranch,
				form: dojo.byId("frm_addbranch"),
				handleAs:"json",
				load: function(data) {
					var Itemmake = { 
							 id: data,
							 name: dijit.byId('branch_nameen').get('value')
						   };
			   addDataToSelectbox(dijit.byId('branch'), b_store, Itemmake, data);
			   dijit.byId('frm_addbranch').reset();
			   dijit.byId("popup_add_branch").hide();	
			},
			error: function(err) {
			}
	});
}
}
function hideDialog(){
	dijit.byId('frm_addbranch').reset();
	dijit.byId("popup_add_branch").hide();
}
function submitDataClose(){
	pro_id=dijit.byId("pro_id").get('value');
	if(pro_id=='' || pro_id==null){
		dijit.byId("pro_id").focus();
		return false;
	}
	if(dijit.byId('suspend_service').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'installment','controller'=>'retailpurchase','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("suspend_service"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/installment/retailpurchase";
			},
			error: function(e) {
			}
		});
	}
}
</script>