<?php
$request = Zend_Controller_Front::getInstance ()->getRequest ();

$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
echo $this->headTitle($tr->translate('PURCHASE'));
$frm = $this->form_search;
$url_receipt = $this->baseUrl()."/report/installments/retailreceipt/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<form	action=""	dojoType="dijit.form.Form" method="post">
	<table style="width: 100%">
		<tr>
			<td><?php echo $frm->getElement("adv_search");?></td>
			<td><?php echo $frm->getElement("branch_id");?></td>
			<td><?php echo $frm->getElement("supllier");?></td>
			<td><?php echo $frm->getElement("start_date");?></td>
			<td><?php echo $frm->getElement("end_date");?></td>
			<td> <?php echo $frm->getElement("status");?></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td> 
		</tr> 
	</table>
</form>
<?php
echo $this->list;
?>
<script>
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			indexkey="";
			var m = "clicked: " + key;
			if(key=="receipt"){
					url='<?php echo $url_receipt;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"receipt": {name: "<?php  echo $tr->translate("RECEIPT");?>", icon: "fa-print"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_blank');
	}
}
</script>
 