<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title> <?php echo $tr->translate("COLLECTERALL_TYPE")?></title>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'other','controller'=>'callecteralltype','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
		<legend align="center" ><strong><?php echo $tr->translate("CALLECTERALLTYPE")?></strong></legend>
		<table style="margin: 0 auto; width: 100%;" cellspacing="10" >
					​<tr>
						<td><?php echo $tr->translate("NAME_KH")?></td>
						<td><?php echo $frm->getElement('title_kh')?><?php echo $frm->getElement('id')?></td>								
					</tr>
					<tr>
						<td><?php echo $tr->translate("NAME_ENG")?></td>
						<td><?php echo $frm->getElement('title_en')?></td>	
					</tr>
					<tr>
						<td><?php echo $tr->translate("DATE")?></td>
						<td><?php echo $frm->getElement('date')?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS")?></td>
						<td><?php echo $frm->getElement('status')?></td>
					</tr>
					<tr>
						<td align="center" colspan="2">
							<input type="reset" iconClass="dijitIconClear" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button"/>
							<input type="submit" value="btn_save_close" name="btn_save_close"  id="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>	
				</table>	
		</fieldset>		
		</td>
	</tr>
</table>
</form>