<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title> <?php echo $tr->translate("COLLECTERALL_TYPE")?></title>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'other','controller'=>'callecteralltype','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<fieldset>
<table cellspacing="10" class='fullside'><legend><strong><?php echo $tr->translate("COLLECTERALL_TYPE")?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CALLECTERALLTYPE")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<?php echo $frm->getElement('id')?>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php echo $frm->getElement('title_kh')?></td>								
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_ENG")?></td>
							<td><?php echo $frm->getElement('title_en')?></td>	
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("DATE")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("DISPLAY_BY")?></td>
							<td><?php echo $frm->getElement('display_by')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('date')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status')?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td align="center"​​ colspan="2">
			<input type="submit" value="កែប្រៃ & ចាកចេញ" name="btn_save_close" label="<?php echo $tr->translate('SAVEEDIT');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>