<?php	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('PAWN_SALE'));
	echo $this->headTitle();
	$frm = $this->frm_loan;
	
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	echo $this->frmpupopinfoclient;
	
	$session_user=new Zend_Session_Namespace('authloan');
	$currentBranch = $session_user->branch_id;
	$currentlevel = $session_user->level;
?>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog",
				"dijit/form/Textarea"]);
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'sale','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
			return true;
		}else {
			return false;
		}
	</script>
	<table width="100%" style="margin-top:0px;">
		<tr>
			<td width="50%" valign="top">
				<fieldset>
					<legend><strong><?php echo $tr->translate("CLIENT_INFO")?></strong></legend>
						<table cellspacing="5"  width="100%" style="margin-top: -10px;">
						   <tr>
								<td width="150px"><?php echo $tr->translate("BRANCH_NAME")?></td>
								<td>
									<select <?php if ($currentlevel!=1){ echo 'readonly="readonly"';}?> dojoType="dijit.form.FilteringSelect" name="branch_id" id="branch_id" onchange="getProductByBranch()" class="fullside" >
										<option value=""><?php echo $tr->translate('Choose Customer');?></option>
										<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
										<option value="<?php echo $branch['id']?>" <?php if($branch['id']==$this->row['branch_id']){echo "selected='selected'";}?>><?php echo $branch['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td><strong><?php echo $tr->translate("CUSTOMER_NAME")?></strong></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="customer_name" name="customer_name" value="<?php echo $this->row['customer_name'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("TEL")?></td>
								<td><input dojoType="dijit.form.TextBox" class="fullside" id="tel" name="tel" value="<?php echo $this->row['tel'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SEX")?></td>
								<td>
									<select dojoType="dijit.form.FilteringSelect" class="fullside" name="gender" id="gender" >
										<option value="1" <?php if($this->row['gender']==1){echo "selected='selected'";}?>>Male</option>
										<option value="2" <?php if($this->row['gender']==2){echo "selected='selected'";}?>>Female</option>
									</select>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("DOB")?></td>
								<td><input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" value="<?php echo $this->row['dob'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ADDRESS")?></td>
								<td><input dojoType="dijit.form.TextBox" class="fullside" id="address" name="address" value="<?php echo $this->row['address'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NATION_ID")?></td>
								<td><input dojoType="dijit.form.TextBox" class="fullside" id="nation_id" name="nation_id" value="<?php echo $this->row['nationid_no'];?>" type="text"></td>
							</tr>
					</table>
			</fieldset>
			</td>
			<td width="50%" valign="top">
				<fieldset>
					<legend><strong><?php echo $tr->translate("PRODUCT_DESCRIPTION")?></strong></legend>
						<table cellspacing="5"  width="100%" style="margin-top: -10px;">
							<tr>
								<td width="150px"><strong><?php echo $tr->translate("INVOICE_NO")?></strong></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="invoice_no" name="invoice_no" value="<?php echo $this->row['invoice_no'];?>" type="text"></td>
							</tr>
							<tr>
								<td><strong><?php echo $tr->translate("PRODUCT_NAME")?></strong></td>
								<td><input id="product_id" /><?php ////echo $frm->getElement('product_id');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SELLING_PRICE")?>($)</td>
								<td><input dojoType="dijit.form.NumberTextBox" class="fullside" id="unit_price" name="unit_price" value="<?php echo $this->row['selling_price'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("DESCRIPTION")?></td>
								<td><input  dojoType="dijit.form.TextBox" class="fullside" id="description" name="description" value="<?php echo $this->row['description'];?>" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SELLING_DATE")?></td>
								<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside" id="selling_date" name="selling_date" value="<?php echo $this->row['selling_date'];?>" type="text"></td>
							</tr>
							
							<tr>
								<td><?php echo $tr->translate("STATUS")?></td>
								<td>
									<select dojoType="dijit.form.FilteringSelect" class="fullside" name="status" id="status" >
										<option value="1" <?php if($this->row['status']==1){echo "selected='selected'";}?>>Active</option>
										<option value="0" <?php if($this->row['status']==0){echo "selected='selected'";}?>>Deactive</option>
									</select>
								</td>
							</tr>
							
						</table>
				</fieldset>
			</td>
		</tr>
		<tr>
			<td align="center" colspan="2">
				<input type="submit" label="<?php echo $tr->translate("GO_EDIT")?>" name='savenew' id="save_new" value='savenew' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask"/>
				<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' id="save_view"  value='savenew' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask"/>
			</td>
		</tr>	
	</table>
</form>


<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var product_store  = getDataStorefromJSON('id','name', <?php array()?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		new dijit.form.FilteringSelect({
				store: product_store,
				autoComplete: false,
				queryExpr: "*${0}*",
				required: false,		           
				name: "product_id",
				id: "product_id",
				class: 'fullside',
				onChange: function() {
					product_id = dijit.byId('product_id').get('value');
					if(product_id>0){
						getProductDetail(product_id);
					}
				}
			}, "product_id");
		getProductByBranch();	
		
		setReadOnly();
		
	  });
});

function setReadOnly(){
	dijit.byId("branch_id").set('readOnly',true);
	//dijit.byId("customer_name").set('readOnly',true);
	//dijit.byId("tel").set('readOnly',true);
	//dijit.byId("gender").set('readOnly',true);
	//dijit.byId("dob").set('readOnly',true);
	//dijit.byId("address").set('readOnly',true);
	//dijit.byId("nation_id").set('readOnly',true);
	
	dijit.byId("invoice_no").set('readOnly',true);
	dijit.byId("product_id").set('readOnly',true);
	dijit.byId("unit_price").set('readOnly',true);
	dijit.byId("description").set('readOnly',true);
	dijit.byId("selling_date").set('readOnly',true);
}


var url_productid = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'sale','action'=>'get-product-id-by-branch-edit')); ?>';
function getProductByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id>0){
		dojo.xhrPost({
			url:url_productid,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {
				product_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('product_id').set('store', product_store);
				dijit.byId("product_id").attr("value",'<?php echo $this->row['pawn_id'];?>');
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var url_productdetail = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'sale','action'=>'get-product-detail')); ?>';
function getProductDetail(pawn_id){
	if(pawn_id>0){
		dojo.xhrPost({
			url:url_productdetail,	
			content:{ 
			    'pawn_id':pawn_id
			},		    
			handleAs:"json",
			load: function(data) {
				if(data){
					//dijit.byId("unit_price").attr('value',data.est_amount);
				}
				//dijit.byId("unit_price").attr("value",'<?php echo $this->row['selling_price'];?>');
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}


function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
</script>
<style>
.height200 {
    height: 105px !important;
}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>