<?php  $tran = $this->tran_schedule;

$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
$db = new Report_Model_DbTable_DbLoan();

$tran = $this->tran_schedule;
$client = $this->client;											
?>
<?php  $end_dat=$this->date_show;
?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<style>
.hover:hover{background: #ccc;}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
 <div style="height: auto; width:29cm; margin: 0 auto;">
 <form method="post">
	<table width="100%">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
		</tr>
		<tr>
			
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	</form>
 </div>
<div style=" width:29cm; min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 5px;">
	<div id="divPrint">
	<style>
.style{
	line-height: 20px;font-size: 9px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("D-d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                    </td>
	                    <td width="20%"></td>
	                </tr>
	                <?php 
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr class='style'>
	                				<td width="40%">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td></td>
	                				
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel"  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%">
	                 <tr class="style" align="center" bgcolor="#ccc" style="white-space: nowrap;">
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("LOAN_NO");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("PHONE");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("CO_NAME");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("RELEASE_DATE");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("LIFE_LOAN");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("LOAN_AMOUNT");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("DAY_PAYMENT");?></td>
	                    <!--<td rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("TIME_COLLECT");?></td>-->
	                    <td colspan="5" style="padding:0px 2px;"><?php echo $tr->translate("PAYMENT");?></td>
	                    <td rowspan="2" style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("LATE_DAY");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("OTHER");?></td>
	                </tr>
	                <tr class="style" bgcolor="#ccc" style="white-space: nowrap;">
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("PRINCIPAL_PERMONTH");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("INTEREST");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("SERVICE_CHARGE");?></td>
	                 	<td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
	                </tr>
	                <?php $amt_r1 = 0;$tir = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
		             ?>
	               <?php foreach($tran as $key =>$row){?>
	               	<tr align="center" style="font-size:9px; height: 20px; white-space:nowrap;" class="style hover">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <td align="left">&nbsp;<?php echo $row['branch_kh'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
	                     <td align="left" style="min-width:60px;">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
	                     <td align="left" style="white-space: nowrap;">&nbsp;<?php echo $row['phone_number'];?>&nbsp;</td>
	                     <td align="left" style="min-width:60px;">&nbsp;<?php echo $row['co_name'];?>&nbsp;</td>
	                     <td align="left" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['date_release']));?>&nbsp;</td>
	                     <td align="left" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['date_line'])) ;?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo number_format($row['total_capital'],2)." ".$row['currencyname'];?>&nbsp;</td>
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    <td align="center" style="white-space: nowrap;"><?php echo date('d-m-Y',strtotime($row['date_payment']));?>&nbsp;</td>
	                    <!--<td align="center"><?php //echo str_replace(' ', '',$row['time_collect']);?>&nbsp;</td>-->
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['principle_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php 
	                    $total_pay=($row['principle_after']+$row['total_interest_after']);
	                    if ($row['last_pay_date']==null or $row['last_pay_date']==""){
	                    	$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
	                    	$amount_lateday=$total_day/(60*60*24)-$free_day;
	                    	$late_day = $total_day/(60*60*24);
	                    }else {
	                    	$total_day=strtotime($end_dat)-strtotime($row['last_pay_date']);
	                    	$amount_lateday=$total_day/(60*60*24);
	                    	$late_day = $total_day/(60*60*24);
	                    }
	                    $pay_term=$row['collect_typeterm'];
	                    if($amount_lateday<0){
	                    	$amount_lateday=0;
	                    	$result=0;
	                    }
	                    else {
	                    	$total_late=($row['principle_after']+$row['total_interest_after']);
	                    	if ($pay_term==1){
	                    		$result=$total_pay*($row['pay_after']*($row['interest_rate']/100)/1)*($amount_lateday);
	                    	}
	                    	if ($pay_term==2){
	                    		$result=$total_pay*($row['pay_after']*($row['interest_rate']/100)/7)*($amount_lateday);
	                    	}
	                    	if ($pay_term==3){
	                    		$result=$total_pay*($row['pay_after']*(($row['interest_rate']/100)/30))*($amount_lateday);
	                    	}
	                    }
	                    $penelize = $row['penelize']+$result;
	                    //echo $penelize;
	                    echo str_replace('.00', '', number_format($penelize,2));?>&nbsp;
	                    </td>
	                   	<td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['service_charge'],2));?>&nbsp;</td>
	                    <td><?php 
	                    		$total_payment = $penelize+$row['principle_after']+$row['total_interest_after']+$row['service_charge'];
	                    		echo str_replace('.00', '', number_format($total_payment,2))." ".$row['currencyname'];?> 
	                   </td>
	                   <td><?php
	                          echo $late_day; //$amount_lateday;
							?></td>
	                   <td>&nbsp;&nbsp;</td>
	                   
	                </tr>
	                
		                <?php //if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $row){ ?>
		                <?php 
				               if($row['currency_type']==1){
				               		$amt_r1 = $amt_r1+$row['principle_after'];
// 				               		$amt_r2 = $amt_r2+$row['total_interest_after'];
				               		$tir = $tir+$row['total_interest_after'];
// 				               		echo $row['total_interest_after'];exit();
				               		$amt_r3 = $amt_r3+$penelize;
				               		$amt_r4 = $amt_r4+$total_payment;
				               		$amt_r5 = $amt_r5+$row['service_charge'];
				               		$total_r=$amt_r4;
				               }elseif($row['currency_type']==2){
									$amt_d1 = $amt_d1+$row['principle_after'];
									$amt_d2 = $amt_d2+$row['total_interest_after'];
									$amt_d3 = $amt_d3+$penelize;
									$amt_d4 = $amt_d4+$total_payment;
									$amt_d5 = $amt_d5+$row['service_charge'];
									$total_d=$amt_d4;
				               }else{
				               		$amn_b1 = $amn_b1+$row['principle_after'];
									$amn_b2 = $amn_b2+$row['total_interest_after'];
									$amn_b3 = $amn_b3+$penelize;
									$amn_b4 = $amn_b4+$total_payment;
									$amn_b5 = $amn_b5+$row['service_charge'];
									$total_b=$amn_b4;
				               }
		            // }
		               ?>
	                <?php }?>
	                
	            </table>
	            <div style="height:10px;"></div>
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td style="font-size: 12px;"></td>
                    <th style="font-size: 12px;"><?php echo $tr->translate("OS_AMOUNT");?></th>                    
                    <th style="font-size: 12px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($tir,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
                
              </table>
	    	</td>
	    </tr>
	</table>
	
	
	<!-- Loan late section -->
	<br />
	<hr />
	<div style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_LATE");?></div>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
    <tr>
    	<td>
            <table id="exportExcel"  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 24px;font-size:9px; font-family: 'Khmer OS Content';white-space: nowrap;">
                    <th><?php echo $tr->translate("NUM");?></th>
                    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th><?php echo $tr->translate("LOAN_NO");?></th>
                    <th><?php echo $tr->translate("CLIENT_NUM");?></th>
                    <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
                    <th><?php echo $tr->translate("CO_NAME");?></th>
                    <th><?php echo $tr->translate("INTEREST RATE");?></th>
                    <th><?php echo $tr->translate("LOAN_PERIOD");?></th>
                    <th><?php echo $tr->translate("PRINCIPAL");?></th>
                    <th><?php echo $tr->translate("PRINCIPAL_PERMONTH");?></th>
                    <th><?php echo $tr->translate("INTEREST");?></th>
                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th><?php echo $tr->translate("PAYMENT");?></th>
                    <th><?php echo $tr->translate("LATE_DAY");?></th>
                    <th><?php echo $tr->translate("PAY_DATE");?></th>
                </tr>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;
                	 $pene_amr=0; $pene_amb=0;$pene_amd=0;
                	 $serv_amr=0;$serv_amb=0;$serv_amd=0;
                ?>
                <?php $i=1;?>
               <?php if(!empty($this->loanlate_list))foreach ($this->loanlate_list as $index => $rs){ ?>
               		<?php $end_dat = $this->list_end_dates;
	               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
	               			//echo $total_pay;
	               			if ($rs['last_pay_date']==null or $rs['last_pay_date']==""){
	               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
	               				$amount_lateday=$total_day/(60*60*24)-$free_day;
	               				$total_late_day=$total_day/(60*60*24);
	               			}else {
	               				$total_day=strtotime($end_dat)-strtotime($rs['last_pay_date']);
	               				$total_late_day=$total_day/(60*60*24);
	               				$amount_lateday=$total_day/(60*60*24);
	               			}
	               			$pay_term=$rs['collect_typeterm'];
	               			if($amount_lateday<0){
	               				$amount_lateday=0;
	               				$result=0;
	               			}
	               			else {
	               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
	               				if ($pay_term==1){
	               					$result=$total_pay*($rs['pay_after']*($rs['interest_rate']/100)/1)*($amount_lateday);
	               				}
	               				if ($pay_term==2){
	               					$result=$total_pay*($rs['pay_after']*($rs['interest_rate']/100)/7)*($amount_lateday);
	               					//echo $total_pay."*(".$rs['pay_after']."*(".$rs['interest_rate']."/100)/7)*".$amount_lateday."<br />";
	               				}
	               				if ($pay_term==3){
	               					$result=$total_pay*($rs['pay_after']*(($rs['interest_rate']/100)/30))*($amount_lateday);
	               				}
	               			}
	               			//echo $amount_lateday;
	               			$penelize = $db->roundhundred($rs['penelize']+$result, $rs['curr_type']);
	               			//echo $penelize;
	               			//echo str_replace('.00', '', number_format($penelize,2));
	               			$total_payment = $penelize+$rs['principle_after']+$rs['total_interest_after']+$rs['service_charge'];
               				
               			
               			
               			?>
               <?php if($amount_lateday>0){?>
                <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content'; white-space: nowrap;">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["total_duration"]." ".$rs["Term Borrow"];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_principal"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;
               			<?php echo $penelize.' '.$rs['currency_type'];?>&nbsp;
               		</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($total_payment,2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="center">&nbsp;&nbsp;<?php echo $total_late_day." Days";?> &nbsp;</td>
               		<td align="center">&nbsp;&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
               		<!--<td align="center" style="width:100px;">&nbsp;<?php //echo  str_replace(' ', '', $rs["time_collect"]);?>&nbsp;</td> -->
                </tr>
                <?php }?>
                <?php 
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal'];
		               		$amt_r2 = $amt_r2+$rs['principle_after'];
		               		$amt_r3 = $amt_r3+$rs['total_interest_after'];
		               		$pene_amr=$pene_amr+$penelize;
		               		$amt_r4 = $amt_r4+$total_payment;
		               		$serv_amr = $serv_amr+$rs["service_charge"];
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal'];
							$amt_d2 = $amt_d2+$rs['principle_after'];
							$amt_d3 = $amt_d3+$rs['total_interest_after'];
							$pene_amd=$pene_amd+$penelize;
							$amt_d4 = $amt_d4+$total_payment;
							$serv_amd = $serv_amd+$rs["service_charge"];
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal'];
							$amn_b2 = $amn_b2+$rs['principle_after'];
							$amn_b3 = $amn_b3+$rs['total_interest_after'];
							$pene_amb= $pene_amb+$penelize;
							$amn_b4 = $amn_b4+$total_payment;
							$serv_amb = $serv_amb+$rs["service_charge"];
		               }
		               $amount_days = strtotime($this->list_end_dates)-strtotime($rs["date_payment"]);
		               $amount_days =  floor($amount_days/(60*60*24));
		               //echo $this->list_end_date['end_date'];
               ?>
                <?php }?>
               
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate('CURRENT_TYPE');?></td>                  
                    <th><?php echo $tr->translate("TOTAL_PRINCIPLE");?></th>
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amd,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($serv_amd,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amr,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($serv_amr,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amb,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($serv_amb,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                </tr>
              </table>
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
	</div>
</div>