<?php
$request = Zend_Controller_Front::getInstance ()->getRequest ();

$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
echo $this->headTitle($tr->translate('PURCHASE'));
$frm = $this->form_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<form	action=""	dojoType="dijit.form.Form" method="post">
	<table style="width: 100%">
		<tr>
			<td><?php echo $frm->getElement("adv_search");?></td>
			<td><?php echo $frm->getElement("branch_id");?></td>
			<td><?php echo $frm->getElement("supllier");?></td>
			<td><?php echo $frm->getElement("start_date");?></td>
			<td><?php echo $frm->getElement("end_date");?></td>
			<td> <?php echo $frm->getElement("status");?></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td> 
		</tr> 
	</table>
</form>
<?php
echo $this->list;
?>

 