<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:128px !important;} 
.tds{width:114px !important;}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'capitalresource','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('brance').get('value');
				if(branch_id==0){
					alert("សូមជ្រើសរើសសាខា");dijit.byId('brance').focus();return false;
				}
				dijit.byId("save_new").set("disabled",true);
				return true;
			}else{
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend class="mainblog"><strong><?php echo $tr->translate("ADD_CAPITAL")?></strong></legend>
					<table cellspacing="10"  width="100%">
						<tr><td colspan="8" bgcolor="#dbe7ff"><?php echo $tr->translate("CAPITAL_ON_HAND")?></td></tr>
						<tr>
							<td nowrap><?php echo $tr->translate("BRANCH")?></td>
							<td><?php echo $frm->getElement('brance')?></td>
							<td class="tds"><?php echo $tr->translate("CURRENT_DOLLAR")?></td>
							<td><?php echo $frm->getElement('dollar_current')?></td>
							<td class="tds"><?php echo $tr->translate("CURRENT_REIL")?></td>
							<td><?php echo $frm->getElement('reil_current')?></td>
							<td class="tds"><?php echo $tr->translate("CURRENT_BATH")?></td>	
							<td><?php echo $frm->getElement('bath_current')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE")?></td>	
							<td><?php echo $frm->getElement('date')?></td>
							<td><strong><?php echo $tr->translate("EXTRA_DOLLARS")?></strong></td>
							<td><?php echo $frm->getElement('usa')?></td>
							<td><strong><?php echo $tr->translate("EXTRA_REIL")?></strong></td>
							<td><?php echo $frm->getElement('reil')?></td>
							<td><strong><?php echo $tr->translate("EXTRA_BATH")?></strong></td>	
							<td><?php echo $frm->getElement('bath')?></td>
						</tr>
						<tr><td colspan="8" bgcolor="#dbe7ff"><?php echo $tr->translate("CAPITAL_IN_BANK")?></td></tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status')?></td>
							<td><?php echo $tr->translate("CURRENT_DOLLAR")?></td>
							<td><?php echo $frm->getElement('dollarbank_current')?></td>
							<td><?php echo $tr->translate("CURRENT_REIL")?></td>
							<td><?php echo $frm->getElement('reilbank_current')?></td>
							<td><?php echo $tr->translate("CURRENT_BATH")?></td>	
							<td><?php echo $frm->getElement('bathbank_current')?></td>
						</tr>
						<tr>
							<td></td><td></td>
							<td><strong><?php echo $tr->translate("EXTRA_DOLLARS")?></strong></td>
							<td><?php echo $frm->getElement('usabank')?></td>
							<td><strong><?php echo $tr->translate("EXTRA_REIL")?></strong></td>
							<td><?php echo $frm->getElement('reilbank')?></td>
							<td><strong><?php echo $tr->translate("EXTRA_BATH")?></strong></td>	
							<td><?php echo $frm->getElement('bathbank')?></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td colspan="5"><?php echo $frm->getElement('note');?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="បោះបង់" label="<?php echo $tr->translate("CANCEL")?>" name="cancel" id="cancel" dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" value="រក្សាទុកថ្មី" label="<?php echo $tr->translate("SAVENEW")?>" name="save_new" id="save_new" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
	<tr>
		<td>
		
			<?php $r1=0; $r2=0;$d1=0;$d2=0;$b1=0;$b2=0;
				$disburse_dollar = 0;$disburse_reil = 0;$disburse_bath = 0;
				$saving_amountr = 0;$saving_amountd = 0;$saving_amountb = 0;
            ?>
            
            <?php if(!empty($this->rsloandisburse)){?>
                <?php if(!empty($this->rsloandisburse)) foreach ($this->rsloandisburse as $key => $row){ ?>
                <?php 
                	if($row['curr_type']==1){
		               		$disburse_reil=$disburse_reil+$row['total_capital'];
		               }elseif($row['curr_type']==2){
							$disburse_dollar=$disburse_dollar+$row['total_capital'];
		               }else{
							$disburse_bath=$disburse_bath+$row['total_capital'];
		               }
		         ?>
                <?php }?>           
            <?php }?> 
            <?php if(!empty($this->LoanFee_list)){?>
                <?php if(!empty($this->LoanFee_list)) foreach ($this->LoanFee_list as $key => $row){ ?>
                <?php 
                	if($row['curr_type']==1){
		               		$r1 = $r1+$row['admin_fee'];
		               		$r2 = $r2+$row['other_fee'];
		               }elseif($row['curr_type']==2){
							$d1 = $d1+$row['admin_fee'];
							$d2 = $d2+$row['other_fee'];
		               }else{
		               		$b1 = $b1+$row['admin_fee'];
							$b2 = $b2+$row['other_fee'];
		               }
		         ?>
                <?php }?>           
            <?php }?>          
                <?php 
                    $amt_r1 = 0; $amn_r2 = 0; $amn_r3 = 0;$amt_r4 = 0;$amn_r5 = 0;
                	$amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
                	$amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
                	$i=1;$oldloan_number='';
                	$total_d=0;$total_b=0;$total_r=0;
                ?>
               <?php $is_set =0; if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
               <?php $interest=0; ?>
               <?php 
	               if($rs['currency_type']==1){
	               		$amt_r1 = $amt_r1+$rs["principal_paid"];
	               		$amn_r2 = $amn_r2+$rs["interest_paid"];
	               		$amn_r3 = $amn_r3+$rs["service_paid"];
	               		$amn_r5 = $amn_r5+$rs["penalize_paid"];
	               		$total_r=$amt_r1+$amn_r2+$amn_r3+$amn_r5;
	               }elseif($rs['currency_type']==2){
						$amt_d1 = $amt_d1+$rs["principal_paid"];
						$amt_d2 = $amt_d2+$rs["interest_paid"];
						$amt_d3 = $amt_d3+$rs["service_paid"];
						$amt_d5 = $amt_d5+$rs["penalize_paid"];
						$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
	               }else{
	               		$amn_b1 = $amn_b1+$rs["principal_paid"];
						$amn_b2 = $amn_b2+$rs["interest_paid"];
						$amn_b3 = $amn_b3+$rs["service_paid"];
						$amn_b5 = $amn_b5+$rs["penalize_paid"];
						$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
	               }
               ?>
                <?php }?>
                <?php $amt_d = 0;$amt_b3 = 0;
                $total_rr=0;$total_dd=0;$total_bb=0;
                ?>
                <?php if(!empty($this->rsincome)) foreach ($this->rsincome as $key => $rs){ ?>
                <?php 
	                if($rs['curr_type']==1){
	                	$total_rr = $total_rr+$rs["total_amount"];
	                }elseif($rs['curr_type']==2){
	                	$total_dd = $total_dd+$rs["total_amount"];
	                }else{
	                	$total_bb = $total_bb+$rs["total_amount"];
	                }
               ?>
               
                <?php }?>
           
                <?php $amt_r = 0;$amt_d = 0;$amt_b3 = 0;
                ?>
                <?php if(!empty($this->rsexpense)) foreach ($this->rsexpense as $key => $rs){ ?>
                <?php 
	                if($rs['curr_type']==1){
	                	$amt_r = $amt_r+$rs["total_amount"];
	                }elseif($rs['curr_type']==2){
	                	$amt_d = $amt_d+$rs["total_amount"];
	                }else{
	                	$amt_b3 = $amt_b3+$rs["total_amount"];
	                }
               ?>
                <?php }?>
			<table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr bgcolor="#94b0e8" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;font-family: 'Khmer OS Content';">
                    <td rowspan="2"><?php echo $tr->translate("CURRENT_TYPE");?></td>
                    <?php 
                        $colspan=3;$level=1;
	                   ?>
                    <td colspan="<?php echo $colspan;?>"><?php echo $tr->translate("ចំណូលពីការប្រមូលសរុប");?>(+)</td>
                    <td rowspan="2"><?php echo $tr->translate("កម្ចីទំលាក់");?>(-)</td>
                    <th colspan="2"><?php echo $tr->translate("INCOME_FROMLOAN_DISBURSE");?>(+)</th>
                    <td rowspan="2"><?php echo $tr->translate("ចំណូល-ចំណាយ");?>(+/-)</td>
                    <td rowspan="2"><?php echo $tr->translate("TOTAL");?>(+/-)</td>
                </tr>
                <tr bgcolor="#94b0e8" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate("ប្រាក់ដើម");?></td>
                    <td><?php echo $tr->translate("ប្រាក់ការសរុប");?></td>
                    <td><?php echo $tr->translate("ប្រាក់ពិន័យសរុប");?></td>
                    <th><?php echo $tr->translate("AMIN_FEE");?></th>
                    <th><?php echo $tr->translate("OTHER_FEE");?></th>
                </tr>
                <tr class="style" style=" line-height: 24px; font-size:11px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>                   
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($disburse_dollar,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_dd-$amt_d,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d1+$d2+$total_d+$total_dd-$amt_d-$disburse_dollar,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($disburse_reil,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_rr-$amt_r,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r1+$r2+$total_r+$total_rr-$amt_r-$disburse_reil,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($disburse_bath,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_bb-$amt_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b1+$b2+$total_b+$total_bb-$amt_b3-$disburse_bath,2);?>&nbsp;</td>
                </tr>
              </table>
		</td>
	</tr>
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	dijit.byId('dollar_current').set('readOnly',true);
	dijit.byId('bath_current').set('readOnly',true);
	dijit.byId('reil_current').set('readOnly',true);
});

var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capitaltransfer','action'=>'getamountbybranceid'));?>'; 
function getAmounts(){
	var brance_id = dijit.byId('brance').get('value');
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance').get('value'),
		},	
		handleAs:"json",
		load: function(respone) {
			for(i=0;i<respone.length;i++){
				if(respone[i].account_id==1){
					dijit.byId('dollar_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bath_current').attr('value',respone[i].amount_bath);
					dijit.byId('reil_current').attr('value',respone[i].amount_riel);
				}else{
					dijit.byId('dollarbank_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bathbank_current').attr('value',respone[i].amount_bath);
					dijit.byId('reilbank_current').attr('value',respone[i].amount_riel);
					}
		   }
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function statusCheck(){
	var status = dijit.byId('status').get('value');
	if(status == -1){
		alert("សូមមេត្តាជ្រើសរើសស្ថានភាពយ៉ាងហោចមួយ!!");
	}
}

function submitDataClose(){
	if(dijit.byId("brance").get('value')==''){
		alert("Please Select Branch Name");
		dijit.byId("brance").focus();
		return false;
	}
	if(dijit.byId('frm_add').validate()) {
		dijit.byId("save_close").set("disabled",true);
		dijit.byId("save_new").set("disabled",true);
		var url_submit = '<?php echo $this->url(array('module'=>'capital','controller'=>'capital','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/capital/capital";
			},
			error: function(e) {
			}
		});
	}
}
</script>
