<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Capital Transfer"));
$frm = $this->frm;
?>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'capital','controller'=>'capitalresource','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width="100%">
   		<tr>
   			<td><?php echo $frm->getElement("search");?></td>
   			<td><?php echo $frm->getElement("start_date");?></td>
   			<td><?php echo $frm->getElement("end_date");?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement("btn_search");?></td>
   		</tr>
   </table>
</form>
<?php echo $this->list;?>


