<?php
	$this->headTitle('Add Loan IL'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
 <style>
   #table tr th{
   	padding: 10px;
    border: solid 1px #ccc8c8;
        background: #e7ecf7;
	}
   </style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
			zone = dijit.byId('zone').get('value');
			co_id = dijit.byId('co_id').get('value');
			client = dijit.byId('member').get('value');
            branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}if(co_id=='' || co_id==-1){
				alert('Please Select CO Name !');
				dijit.byId('co_id').focus();
				return false;
			} if(zone=='' || zone==-1){
				alert('Please Select Zone !');
				dijit.byId('zone').focus();
				return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
			currency_type = dijit.byId('currency_type').get('value');
			if(currency_type==1){
				amount_loan = dijit.byId('total_amount').get('value');
				if(amount_loan<100000){
					alert('Loan Amount Must Than 100000 for Riel Currency!');
					return false;
                }
            }
			dijit.byId('savenew').set('disabled',true);
			dijit.byId('saveclose').set('disabled',true);
			return true;
		}else {
		    return false;
		}
</script>
<fieldset style="background: #e0ebff">
<table width="100%" style="margin-top:0px;" cellspacing="10">
     <legend class="mainblog" ><strong><?php echo $tr->translate("IL_DISBURSE")?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
			 <fieldset >
				<legend align="center" ><strong><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
					        <td><strong><?php echo $tr->translate("BRANCH_NAME")?></strong></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
					    </tr>
					    <tr>
					    	<td><?php echo $tr->translate("LOAN_NO")?></td>
							<td><?php echo $frm->getElement('loan_code');?></td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /></td>
						</tr>
						<tr>
							<td><strong><?php echo $tr->translate("CUSTOMER_NAME")?></strong></td>
							<td><input id="member" /></td>
						</tr>
						<tr>
							<td></td>
							<td><input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/></td>
						</tr>
						<tr>
							<td><strong><?php echo $tr->translate("CO_NAME")?></strong></td>
							<td><input id="co_id" /></td>
						</tr>
						<tr>
					    	<td><?php echo $tr->translate("LOAN_LEVEL")?></td>
							<td><?php echo $frm->getElement('level');?></td>
					    </tr>
					     <tr>
					  		<td style=" width: 40%;"><?php echo $tr->translate("ZONE_NAME")?></td>
							<td><?php echo $frm->getElement('zone');?></td>
					    </tr>
					    <tr>
					    	<td><?php echo $tr->translate("LOAN_TYPE")?></td>
							<td><?php echo $frm->getElement('loan_type');?></td>
					    </tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("INFO_ILLOAN")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
					        <td style="width: 41%;"><strong><?php echo $tr->translate("LOAN_AMOUNT")?></strong></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
					    </tr>
					    <tr>
					    	<td><strong><?php echo $tr->translate("CURRENCY")?></strong></td>
							<td align="left"><?php echo $frm->getElement('currency_type');?></td>
					    </tr>
					    <tr>
					    	<td><?php echo $tr->translate("AMIN_FEE")?></td>
							<td><?php echo $frm->getElement('loan_fee');?></td>
					    </tr>
					    <tr>
					    	<td><?php echo $tr->translate("OTHER_FEE")?></td>
							<td><?php echo $frm->getElement('other_fee');?></td>
					    </tr>
					    <tr>
					    	<td><strong><?php echo $tr->translate("REPAYMENT_TYPE")?></strong></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
					    </tr>
					    <tr>
							<td style="width: 34%;"><strong><?php echo $tr->translate("INTEREST_RATE")?></strong></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TERM_INSTALL")?></td>
							<td><?php echo $frm->getElement('pay_every');?></td>
						</tr>
						<tr>
							<td><strong><?php echo $tr->translate("TERM_BORROW")?></strong></td>
							<td><?php echo $frm->getElement('period');?></td>
						</tr>
						<tr>
					  		<td style=" width: 40%;"><?php echo $tr->translate("LOAN_RELEASE")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
					    </tr>
					    
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("INFO_FUND")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						 <tr>
					        <td style="width: 41%;"><?php echo $tr->translate("TIME_COLLECION")?></td>
							<td><?php echo $frm->getElement('time');?></td>
					     </tr>
					     <tr>
					    	<td><?php echo $tr->translate("TERM_FUND")?></td>
							<td><?php echo $frm->getElement('collect_termtype');?></td>
					     </tr>
					     <tr>
							<td><?php echo $tr->translate("TERM_GRAICE_PARIOD")?><br/>(<label style="font-size:10px;" id="graice_type"></label>)</td>
							<td><?php echo $frm->getElement('graice_pariod');?></td>
						</tr>
					     
					     <tr>
					    	<td style="width: 34%;"><?php echo $tr->translate("AMOUNT_TERM_FUND")?></td>
							<td><?php echo $frm->getElement('amount_collect');?></td>
					     </tr>
						 <tr>
							<td><?php echo $tr->translate("HOLIDAY_STATUS")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
						 </tr>
					    <tr>
					    	<td><strong><?php echo $tr->translate("FIRST_PAYMENT")?></strong></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
					    </tr>
					    <tr>
					    	<td><?php echo $tr->translate("LIFE_LOAN")?></td>
							<td><?php echo $frm->getElement('date_line');?></td>
					    </tr>
					    <tr>
					    	<td><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></label></td>
							<td><?php echo $frm->getElement('amount_collect_pricipal');?></td>
					    </tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	 
	<tr>
		<td align="center" colspan="3">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  
				 iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
</fieldset>
 
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់', onCancel:hideDialog" id="frm_client" style="width:1000px">
	<div id="rpt_print" class="print" style="text-align:center;">
	<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='save_close' id='save_close' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
	<input type="button" onclick="submitDataClose(2);" label="<?php echo $tr->translate("SAVE_PRINT");?>" id='saveprint' name='saveprint' value='saveprint' dojoType="dijit.form.Button"
	iconClass="dijitIconNewTask"/>
	
	<div id="t_amountmoneytype" name="t_amountmoneytype"></div>
	</div>
</div>
</div>
</form>
<?php //echo $this->frmpupoploantype;?>
<script type="text/javascript">	
    function checkValidateDate(){
    	debt_term = dijit.byId('pay_every').get('value');
		if(debt_term==1){
			term_d =1; 
		}else if(debt_term==2){
			term_d =7; 
		}else{
			term_d =30; 
		}
		
		collect_term = dijit.byId('collect_termtype').get('value');
		if(collect_term==1){
			term_c =1; 
		}else if(collect_term==2){
			term_c =7; 
		}else{
			term_c =30; 
		}
		debt_amount = dijit.byId('period').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if((collect_amount*term_c)>(debt_amount*term_d)){
			alert('<?php echo $tr->translate("SMS_BORROW_FUND")?>');
			dijit.byId('collect_termtype').focus();
			return false;
		}
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('total_amount').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		if(dijit.byId("currency_type").get('value')==1){
			amount_payment = amount_payment%100 > 0 ? (amount_payment-(amount_payment%100)+100) : amount_payment;
		}
			dijit.byId('amount_collect_pricipal').attr('value',amount_payment);
	}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
//dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', [] );//getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->recieverlist));?> );
var client_number_store  = getDataStorefromJSON('id','name', [] );//getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->recieverlist));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		changeCollectType();
	  });
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			window.open("<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>","_blank");
			}else{
			getLoanLevel(member);
			dijit.byId('customer_code').attr('value',member);
		}
}
	}, "member");

	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				window.open("<?php echo $this->url(array('module'=>'loan','controller'=>'co','action'=>'add')); ?>","_blank");
			}else{
			}
	    }
		}, "co_id");
	 
	});
</script>
<script type="text/javascript">
function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
		dijit.byId('customer_code').reset();
		getLoanByBranch();
		getAllClientByBranch(branch_id);
		getAllClientNumberByBranch(branch_id);
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_co = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-coname')); ?>';
function getAllCo(){
	dojo.xhrPost({
		url:url_co,	
		content:{ 
		},		    
		handleAs:"json",
		load: function(data) {
			co_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('co_id').set('store', co_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	member = dijit.byId('member').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	return false;
	if(member=='' || member==-1){
		alert('ជ្រើសរើសអតិថិជន');
		dijit.byId('member').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0,
		    'member':member
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('loan_code').attr('value',data);
		},
		error: function(err) {
		}
	});
}
function showloantype(){
	$('#loan_type').val('asdfsd');
	$('input[name="loan_type"]').val("10");
}
function calCulateAdminFee(){
	p_income="<?php echo $this->setting['adminfee']?>";
	t_admin=dijit.byId('total_amount').get('value');
	adminfee=(p_income*(t_admin/100));
	dijit.byId('loan_fee').attr('value',adminfee);
	chechPaymentMethod();
}
function CompareGraicePariod(){
	graice_pariod = dijit.byId('graice_pariod').get('value');
	period = dijit.byId('period').get('value');
	if(graice_pariod>=period){
		alert('<?php echo $tr->translate("AMOUNT_GRAICEPARIOD_THEN_AMOUNT_LOAN")?>');
		dijit.byId('graice_pariod').attr('value',(period-1));
	}
}
function chechPaymentMethod(){
	method_id = dijit.byId('repayment_method').get('value');
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?>";
	dijit.byId('amount_collect_pricipal').attr('value',0);
	dijit.byId("amount_collect").set('readOnly',false);
	dijit.byId("collect_termtype").set('readOnly',false);	
	if(method_id==6){
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
		dijit.byId('amount_collect').attr('value',1);
		dijit.byId('amount_collect').set('readOnly',true);
		
	}else if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId("amount_collect").set('readOnly',true);
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').attr('value',2);
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
		dijit.byId('amount_collect_pricipal').attr('value','');
		//dijit.byId('amount_collect_pricipal').focus();
		setDefaultPaymentAmount();
	}else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}
}
function changeCollectType(){
	get_id = dijit.byId('pay_every').get('value');
	dijit.byId('collect_termtype').attr('value',get_id);
	changeGraicePeroid();
	CalculateDate();
}
function changeGraicePeroid(){
	disp_value = dijit.byId('collect_termtype').attr('displayedValue');
	dojo.byId('graice_type').innerHTML=disp_value;
	calCulateFirstPayment();	
}
var getloan_level = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-loanlevel')); ?>';
function getLoanLevel(client_id){
	   if(client_id==''){
		   return false;}
		dojo.xhrPost({
	    url: getloan_level,	
	    content : { 
	    	'client_id': client_id,
	    	'type':1
		},	    
		handleAs:"json", 
		load: function(data) {	
			customer_code = dijit.byId("customer_code").get("value");
			dijit.byId('loan_code').attr('value',customer_code+'-'+data);
			dijit.byId('level').attr('value',data);
		},
		error: function(err) {
		}
	});
}
var url_submitzone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
		dojo.xhrPost({
	    url: url_submitzone,	
		form: dojo.byId("form_zone"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_zone').reset(); 
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
		}
	});
}

</script>
<?php 
echo $this->frmpupoploantype;
echo $this->frmPopupZone;
?>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	calCulateFirstPayment();
}
function calCulateEndDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		if(pay_term==3){//month
			mm = a.getMonth()+amount_date+1;
		}else if(pay_term==2){//week
			a.setDate(a.getDate() + (amount_date*7)); 
			var mm = a.getMonth() + 1;
		}else if(pay_term==1){
			a.setDate(a.getDate() + (amount_date)); 
			var mm = a.getMonth() + 1;
		}
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}
function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = dijit.byId('collect_termtype').get('value');
	amount_date = dijit.byId('amount_collect').get('value');
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
	if(pay_term==3){//month
		var month = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var month = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var month = a.getMonth() + 1;
	}
	
	mm = month%12;
	var year = parseInt(month/12);
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+year;
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
////add preview loan
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloantest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		zone = dijit.byId('zone').get('value');
		co_id = dijit.byId('co_id').get('value');
		client = dijit.byId('member').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			alert('Please Select Branch Name!');
			dijit.byId('branch_id').focus();
			return false;
		}
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}if(co_id=='' || co_id==-1){
			alert('Please Select CO Name !');
			dijit.byId('co_id').focus();
			return false;
		}if(zone=='' || zone==-1){
			alert('Please Select Zone !');
			dijit.byId('zone').focus();
			return false;
		}
		rs = checkValidateDate();
		if(rs==false){
          return false;			
        }
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";
				temp='';	fund_title=0;thead='';fund_title=0;
				 		temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						temp+='<tr><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						temp+='<th><?php echo $tr->translate("ចំនួនថ្ងៃ");?></th></tr>';
				var t_principal_permonth=0;
				var t_total_payment=0;
				var t_total_interest=0;
				for(i=0;i<data.length;i++){
			        r++;
			        t_principal_permonth = parseFloat(t_principal_permonth)+parseFloat(data[i].principal_permonth);
			        t_total_interest = parseFloat(t_total_interest) + parseFloat(data[i].total_interest);
			        t_total_payment = parseFloat(t_total_payment) + parseFloat(data[i].total_payment);
					    temp+='<tr><td align="center">'+r+'</td>';
						var myDate = new Date(data[i].date_payment);
						d = new Date(data[i].date_name);
						temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_principal,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						temp+='<td><b>'+dojo.number.format(data[i].total_payment,2)+'<b></td>';
						temp+='<td><b>'+dojo.number.format((data[i].total_principal-data[i].principal_permonth),2)+'<b></td>';
						temp+='<td>'+data[i].amount_day+'</td></tr>';
				 }
				temp+='<tr style=" background: #e7ecf7;"><td align="center"><?php echo $tr->translate("TOTAL");?></td>';
				temp+='<td colspan="2"></td>';
				temp+='<td><b>'+dojo.number.format(t_principal_permonth,2)+'</b></td>';
				temp+='<td><b>'+dojo.number.format(t_total_interest,2)+'</b></td>';
				temp+='<td><b>'+dojo.number.format(t_total_payment,2)+'</b></td>';
				temp+='<td colspan="2"><b><b></td>';
				temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("frm_client").show();
			},
			error: function(err) {
				alert(err);
			document.getElementsByClassName("overlay")[0].style.display="none";
			alert("You can not preview this loan number!");
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
}
function loantype(){
	var data=dijit.byId("loan_type").get('value');
	if(data==-1){
		dijit.byId("frm_loantype").show();
	}
}
function zone(){
	    if(dijit.byId('zone').get('value')==-1){
	    	dijit.byId("frm_zone").show();
        }
}
var url_loantype = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add-newloantype')); ?>';
function addNewloanType(){
	if(dijit.byId('form_loantype').validate()){
	dojo.xhrPost({
		url:url_loantype,	
		content:{ 
		    'title_en':dijit.byId('title_en').get('value'),
		    'title_kh':dijit.byId('title_kh').get('value'),
		    'type':24,
		},
		handleAs:"json",
		load: function(data) {
			labelen = dijit.byId('title_en').get('value');
			labelkh = dijit.byId('title_kh').get('value');
			$('#loan_type').val(labelkh+'-'+labelen);
			$('input[name="loan_type"]').val(data);
			 	
			dijit.byId('frm_loantype').reset();
			dijit.byId('frm_loantype').hide();
		},
		error: function(err) {
			alert(err);
		}
	});
  }
}
var url_zone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
	if(dijit.byId('form_zone').validate()){
	dojo.xhrPost({
		url:url_zone,	
		content:{ 
		    'zone_name':dijit.byId('zone_name').get('value'),
		    'zone_number':dijit.byId('zone_number').get('value'),
		    'status':1,
		},
		handleAs:"json",
		load: function(data) {
			labelen = dijit.byId('zone_name').get('value');
			labelkh = dijit.byId('zone_number').get('value');
			$('#zone').val(labelkh+'-'+labelen);
			$('input[name="zone"]').val(data);
			 	
			dijit.byId('frm_zone').reset();
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		}
	});
  }
}
function showPopupclient(){
	if(dijit.byId('branch_id')!=''){
		dijit.byId("frmpop_client").show();
	}else{
		alert('Please Select Branch First!');
		dijit.byId('branch_id').focus();
		}
}
function popupcreditofficer(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please select branch first');
		dijit.byId('branch_id').focus();
	}else{
		dijit.byId('frm_co').show();
    }
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function submitDataClose(type){
	zone = dijit.byId('zone').get('value');
	co_id = dijit.byId('co_id').get('value');
	client = dijit.byId('member').get('value');
   branch_id = dijit.byId('branch_id').get('value');
    if (branch_id=='' || branch_id==-1){
  	   alert('Please Select Branch Name!');
	   dijit.byId('branch_id').focus();
	   return false;
    }
	if (client=='' || client==-1){
		alert('Please Select Client Name !');
		dijit.byId('member').focus();
		return false;
	}if(co_id=='' || co_id==-1){
		alert('Please Select CO Name !');
		dijit.byId('co_id').focus();
		return false;
	} if(zone=='' || zone==-1){
		alert('Please Select Zone !');
		dijit.byId('zone').focus();
		return false;
	}
	rs = checkValidateDate();
	if(rs==false){
      return false;			
    }
	currency_type = dijit.byId('currency_type').get('value');
	if(currency_type==1){
		amount_loan = dijit.byId('total_amount').get('value');
		if(amount_loan<100000){
			alert('កម្ចីជាលុយរៀល ត្រូវតែធំជា 1ម៉ឺនរៀល!');
			return false;
        }
    }
	if(dijit.byId('frm_add_tran').validate()) {
		dijit.byId('saveprint').set('disabled',true);
		dijit.byId('saveclose').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('savenew').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'submitloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),	
			handleAs:"json",	    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				if(type==1){
					window.location.href ="<?php echo $this->baseUrl();?>/loan/index";
				}else{
					window.location.href ='<?php echo $this->baseUrl().'/report/loan/rpt-paymentschedules/id/'?>'+data;
				}
			},
			error: function(e) {
			}
		});
	}
}
function getRefreshGroup(){
	var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
	filterClient();
	getAllCo();
	loading();
	setTimeout(stopLoading, 1000);
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function stopLoading(){
	 document.getElementsByClassName("overlay")[0].style.display="none";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>