<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LOAN_IL"));
$frm = $this->frm_search;

$url_Payment = $this->baseUrl()."/loan/payment/add/id/"; 
$url_agreement = $this->baseUrl()."/report/loan/agreement/id/";
$url_schedule = $this->baseUrl()."/report/loan/rpt-paymentschedules/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width="100%">
   <tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
   		<td> <?php echo $frm->getElement('branch_id');?></td>
   		<td><?php echo $frm->getElement("client_name");?></td>
   		<td><?php echo $frm->getElement("repayment_method");?></td>
   		<td><?php echo $frm->getElement('co_id');?></td>
   </tr>
   <tr>
   		<td><?php echo $frm->getElement('currency_type');?></td>
   		<td><?php echo $frm->getElement('pay_every');?></td>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement('status');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   </tr>
</table>
</form>
<?php echo $this->list;?>
<script>
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			 if(key=="payment"){
				url='<?php echo $url_Payment;?>';
			}else if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
			}else if(key=="schedulePay"){
				url='<?php echo $url_schedule;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
			"schedulePay": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>