 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Dashboard Loan System Management"));
	echo $this->headTitle();
	
	$db = new Home_Model_DbTable_DbDashboard();
	?>
 
 <!--Morris Chart CSS -->
<link rel="stylesheet" href="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.css">

 <!-- Bootstrap core CSS -->
 <link href="<?php echo $this->baseUrl()."/"?>dashboard/css/bootstrap.min.css" rel="stylesheet">
<!-- Icons CSS -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/icons.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/style.css" rel="stylesheet">
<div id="page-wrapper">
	<!-- Page content start -->
	<div class="page-contentbar">
		<!-- START PAGE CONTENT -->
		<div id="page-right-content">
			<div class="container">
				 <div class="row">
					<div class="col-lg-6">
						<!-- 
						<div class="card-box">
							<div  style="padding-left: 0; margin-left: 0; margin-top: 0;">
								<ul id="module-image">						
									<li style="text-align:center;">
										<a href="<?php //echo $this->baseUrl()."/report/loan/rpt-sold"?>">
											<img title="<?php //echo $tr->translate("LOAN_DISBURSE");?>" src="<?php //echo $this->baseUrl()."/images/icon/reportIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php //echo $tr->translate("LOAN_DISBURSE");?></h5></span>
										</a>
									</li>
									<li style="text-align:center;">
										<a href="<?php //echo $this->baseUrl()."/report/paramater/rpt-daily-cash"?>">
											<img title="<?php //echo $tr->translate("REPORT_DAILY_CASH");?>" src="<?php //echo $this->baseUrl()."/images/icon/reportIncomeIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php //echo $tr->translate("REPORT_DAILY_CASH");?></h5></span>
										</a>
									</li>
									<li style="text-align:center;">
										<a href="<?php //echo $this->baseUrl()."/report/paramater/rpt-cancel-sale"?>">
											<img title="<?php //echo $tr->translate("CANCEL_REPORT");?>" src="<?php //echo $this->baseUrl()."/images/icon/reportCancelIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php //echo $tr->translate("CANCEL_REPORT");?></h5></span>
										</a>
									</li>
									<li style="text-align:center;">
										<a href="<?php //echo $this->baseUrl()."/report/loan/rpt-loan-outstanding"?>">
											<img title="<?php //echo $tr->translate("LOAN_OUTSTADING");?>" src="<?php //echo $this->baseUrl()."/images/icon/balanceIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php //echo $tr->translate("LOAN_OUTSTADING");?></h5></span>
										</a>
									</li>
								</ul>
							</div>
						</div>
						 -->
						<div class="card-box">
							<div class="col-lg-12">
								<div class="accounting-management text-center">
									<div class="col-lg-12 capital-box" style="width: 100%; background: #203864; color: #fff">
										<span data-bind="text: txnRecorded"><?php if ($this->netIncome<0){ echo "R ".number_format(abs($this->netIncomeRiels),2);}else{ echo "R ".number_format($this->netIncomeRiels,2);}?></span><br />
										<span data-bind="text: txnRecorded"><?php if ($this->netIncome<0){ echo "$ ".number_format(abs($this->netIncomeDollar),2);}else{ echo "$ ".number_format($this->netIncomeDollar,2);}?></span><br />
										<span data-bind="text: txnRecorded"><?php if ($this->netIncomeBath<0){ echo "B ".number_format(abs($this->netIncomeBath),2);}else{ echo "B ".number_format($this->netIncomeBath,2);}?></span>
										<p class="month" style="width: 70%; text-align: center; margin: 0 auto;" data-bind="text: lang.lang.transactions_recorded"><?php echo $tr->translate("Net Income")?></p>
									</div>
									<div class="col-lg-12" style="padding: 0;">
										<div class="col-lg-6 capital-box" style="background: #0077c5;">
											<span data-bind="text: currentRatio"><?php echo "R ".number_format($this->totalIncomeRiels,2);?></span> <br />
											<span data-bind="text: currentRatio"><?php echo "$ ".number_format($this->totalIncomeDollar,2);?></span> <br />
											<span data-bind="text: currentRatio"><?php echo "B ".number_format($this->totalIncomeBath,2);?></span>
											<p class="month" data-bind="text: lang.lang.current_ratio"><?php echo $tr->translate("Total Income")?></p>
										</div>
										<div class="col-lg-6 capital-box" style="background: #21abf6; color: #fff;">
											<span data-bind="text: quickRatio"><?php echo "R ".number_format($this->ExpenseRiels,2);?></span> <br />
											<span data-bind="text: quickRatio"><?php echo "$ ".number_format($this->ExpenseDollar,2);?></span> <br />
											<span data-bind="text: quickRatio"><?php echo "B ".number_format($this->ExpenseBath,2);?></span>
											<p class="month" style="color: #fff;" data-bind="text: lang.lang.quick_ratio"><?php echo $tr->translate("Total Expense")?></p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="card-box">
                             <div class="col-lg-12">
	                             <div class="p-20 m-b-20">
	                                 <h5 class="m-t-0"><?php echo $tr->translate("Monthly Loan Disburse")?></h5>
                                   <ul class="list-inline chart-detail-list">
										<li>
											<h5 class="font-normal"><i class="fa fa-circle m-r-10 text-muted reils"></i><?php echo $tr->translate("Riels")?></h5>
										</li>
										<li>
											<h5 class="font-normal"><i class="fa fa-circle m-r-10 text-muted dollar"></i><?php echo $tr->translate("Dollar")?></h5>
										</li>
										<li>
											<h5 class="font-normal"><i class="fa fa-circle m-r-10 text-muted baht"></i><?php echo $tr->translate("Baht")?></h5>
										</li>
									</ul>
                                    <div id="morris-bar-example" style="height: 200px;"></div>
                                </div>
							</div>
						</div> 
					</div> <!-- end col -->	  
					 <div class="col-lg-6">
						<div class="card-box">
							<div  style="padding-left: 0; margin-left: 0; margin-top: 0;">
								<ul id="module-image">
									<li style="text-align:center;">
										<a href="<?php echo $this->baseUrl()."/report/loan/rpt-loan-disburse"?>">
											<img title="<?php echo $tr->translate("LOAN_DISBURSE");?>" src="<?php echo $this->baseUrl()."/images/icon/reportIncomeIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php echo $tr->translate("LOAN_DISBURSE");?></h5></span>
										</a>
									</li>					
									<li style="text-align:center;">
										<a href="<?php echo $this->baseUrl()."/report/loan/rpt-dailypayment"?>">
											<img title="<?php echo $tr->translate("RPT-DAILYPAYMENT");?>" src="<?php echo $this->baseUrl()."/images/icon/reportIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php echo $tr->translate("RPT-DAILYPAYMENT");?></h5></span>
										</a>
									</li>
									<li style="text-align:center;">
										<a href="<?php echo $this->baseUrl()."/report/loan/rpt-payment"?>">
											<img title="<?php echo $tr->translate("RPT_CLIENT_PAYMENT");?>" src="<?php echo $this->baseUrl()."/images/icon/reportCancelIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></h5></span>
										</a>
									</li>
									<li style="text-align:center;">
										<a href="<?php echo $this->baseUrl()."/report/loan/rpt-loan-outstanding"?>">
											<img title="<?php echo $tr->translate("LOAN_OUTSTADING");?>" src="<?php echo $this->baseUrl()."/images/icon/balanceIcon.png"?>" alt="Customer">							
											<span style="margin-top: 5px; font-size: 14px; font-weight: bold; color: #000000"><h5 data-bind="text: lang.lang.accounting" style="margin-top: 5px; display: inline-block;"><?php echo $tr->translate("LOAN_OUTSTADING");?></h5></span>
										</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="card-box">
							<div class="col-lg-12">
								<div class="col-lg-6">
									<p><span data-bind="text: lang.lang.performance"><?php echo $tr->translate("Pawnshop Infomation")?></span></p>
									<table class="performance">
										<tbody>
											<tr>
												<td><a href="<?php echo $this->baseUrl()."/report/paramater/rpt-properties";?>"><span data-bind="text: lang.lang.income"><?php echo $tr->translate("Number of Pawnshop")?></span></a></td>
												<td></td>
												<td align="right"><span data-bind="text: obj.income"><?php echo $this->allPawnShop;?></span></td>
											</tr>
											<tr>
												<td><span data-bind="text: lang.lang.expense"><?php echo $tr->translate("Pawnshop Breaks")?></span></td>
												<td></td>
												<td align="right"><span data-bind="text: obj.expense"><?php echo $this->PawnShopCompleted;?></span></td>
											</tr>
											<tr>
												<td><b><span data-bind="text: lang.lang.net_income"><?php echo $tr->translate("Pawnshop Completed")?></span></b></td>
												<td></td>
												<td align="right"><b data-bind="text: obj.net_income"><?php echo $this->PawnShopDach;?></b></td>
											</tr>
										</tbody>
									</table>
								</div>
								<div class="col-lg-6">
									<p><span data-bind="text: lang.lang.performance"><?php echo $tr->translate("Customer / CO Infomation")?></span></p>
									<table class="performance">
										<tbody>
											<tr>
												<td><a href="<?php echo $this->baseUrl()."/report/groupmember/rpt-client";?>"><span data-bind="text: lang.lang.income"><?php echo $tr->translate("Customers")?></span></a></td>
												<td></td>
												<td align="right"><span data-bind="text: obj.income"><?php echo $this->AllClient;?></span></td>
											</tr>
											<tr>
												<td><a href="<?php echo $this->baseUrl()."/report/paramater/rpt-staff";?>"><span data-bind="text: lang.lang.expense"><?php echo $tr->translate("CO")?></span></a></td>
												<td></td>
												<td align="right"><span data-bind="text: obj.expense"><?php echo $this->CountAllAgency;?></span></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="col-lg-12">
								<div class="col-lg-12">
									<p><span data-bind="text: lang.lang.performance"><?php echo $tr->translate("Loan Information")?></span></p>
									<div class="widget-body alert-info welcome-nopadding">
											<table width="100%" class="saleInfo">
												<thead>
													<tr align="center">
														<td rowspan="2" width="20%">										
															&nbsp;
														</td>
														<td rowspan="2"  width="15%">
															<span data-bind="text: obj.ar_customer"><?php echo $tr->translate("Loan Disburse")?></span>
														</td>
														<td colspan="3" style="border: solid 1px #eee;">
															<span data-bind="text: obj.ar_overdue"><?php echo $tr->translate("Loan Amount")?></span>
														</td>
													</tr>
													<tr align="center"  >
														<td><?php echo $tr->translate("Riels")?> (R)</td>
														<td><?php echo $tr->translate("Dollar")?> ($)</td>
														<td><?php echo $tr->translate("Baht")?> (B)</td>
													</tr>
												</thead>
												<tbody>
													<?php 
													$AllLoans=0;
													$totalRiels=0;
													$totalDollar=0;
													$totalBath=0;
													if (!empty($this->countAllLoan)) foreach ($this->countAllLoan as $allLoan){
														$AllLoans = $AllLoans +$allLoan['countLoan'];
														if ($allLoan['currency_type']==1){
															$totalRiels = $totalRiels + $allLoan['total'];
														}else if($allLoan['currency_type']==2){
															$totalDollar = $totalDollar + $allLoan['total'];
														}else if($allLoan['currency_type']==2){
															$totalBath = $totalBath + $allLoan['total'];
														}
													}?>
													<tr align="left">
														<td class="border-rig">										
															<span data-bind="text: obj.ar_open"><?php echo $tr->translate("Total Loan")?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_customer"><?php echo $AllLoans;?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "R ".number_format($totalRiels,2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "$ ".number_format($totalDollar,2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "B ".number_format($totalBath,2);?></span>
														</td>
													</tr>
													<?php 
													$AllLoansCommplete=0;
													$totalRielsCommplete=0;
													$totalDollarCommplete=0;
													$totalBathCommplete=0;
													if (!empty($this->allLoanComplete)) foreach ($this->allLoanComplete as $allLoan){
														$AllLoansCommplete = $AllLoansCommplete +$allLoan['countLoan'];
														if ($allLoan['currency_type']==1){
															$totalRielsCommplete = $totalRielsCommplete + $allLoan['total'];
														}else if($allLoan['currency_type']==2){
															$totalDollarCommplete = $totalDollarCommplete + $allLoan['total'];
														}else if($allLoan['currency_type']==2){
															$totalBathCommplete = $totalBathCommplete + $allLoan['total'];
														}
													}?>
													<tr align="left">
														<td class="border-rig">										
															<span data-bind="text: obj.ar_open"><?php echo $tr->translate("Completed Loan")?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_customer"><?php echo $AllLoansCommplete;?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "R ".number_format($totalRielsCommplete,2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "$ ".number_format($totalDollarCommplete,2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "B ".number_format($totalBathCommplete,2);?></span>
														</td>
													</tr>
													<tr align="left">
														<td class="border-rig">										
															<span data-bind="text: obj.ar_open"><?php echo $tr->translate("Bad Loan")?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_customer"><?php echo $this->countBadLoan;?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "R ".number_format($this->CancelPropertyAmount,2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "$ ".number_format($this->CountAllSale['totalAmount'],2);?></span>
														</td>
														<td align="center">
															<span data-bind="text: obj.ar_overdue"><?php echo "B ".number_format($this->CountAllSale['totalAmount'],2);?></span>
														</td>
													</tr>
												</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div> <!-- end col -->	  
				</div> <!-- end row -->
				
                 <div class="row-fluid">
					<div style="margin-top: 10px; margin-left: 0;" align="center">
						<p>© 2018<span data-bind="text: lang.lang.all_rights_reserved"><a href="http://www.cam-app.com" target="_blank" > Cam App Teachnology</a>. All rights reserved.</span></p>
					</div>	
				</div>       
			</div>
		</div>
		<!-- END PAGE CONTENT -->
	</div>

</div>
   <!-- js placed at the end of the document so the pages load faster -->
        <script src="<?php echo $this->baseUrl()."/"?>dashboard/js/jquery-2.1.4.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/"?>dashboard/js/bootstrap.min.js"></script>


		<!--Morris Chart-->
		<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.min.js"></script>
		<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/raphael/raphael-min.js"></script>


        
        
 <!-- Dashboard init 
<script src="<?php //echo $this->baseUrl()."/"?>dashboard/pages/jquery.dashboard.js"></script>-->
<?php 
$start_year = date("Y-m-d",strtotime(" -4 month"));
?>
<script>
//creating bar chart
var $barData  = [];
var $barData  = [
    <?php  for ($i=0; $i<=4; $i++ ){
    	$year = date("Y-m",strtotime("$start_year+$i month"));
    	$month = date("m",strtotime("$start_year+$i month"));
    	$loan = $db->getLoanDisbursPerMonth($year);
    ?>
    { y: '<?php echo $year;?>', a: <?php echo $loan['riels'];?>, b: <?php echo $loan['dollar'];?> , c: <?php echo $loan['bath'];?> },
    <?php }?>
];

/**
* Theme: SimpleAdmin Admin Template
* Author: Coderthemes
* Morris Chart
*/
!function($) {
    "use strict";

	var MorrisCharts = function() {};
    //creates Bar chart
    MorrisCharts.prototype.createBarChart  = function(element, data, xkey, ykeys, labels, lineColors) {
        Morris.Bar({
            element: element,
            data: data,
            xkey: xkey,
            ykeys: ykeys,
            labels: labels,
            hideHover: 'auto',
            resize: true, //defaulted to true
            gridLineColor: '#eeeeee',
            barSizeRatio: 0.4,
            xLabelAngle: 35,
            barColors: lineColors
        });
    },
    MorrisCharts.prototype.init = function() {

        
        this.createBarChart('morris-bar-example', $barData, 'y', ['a', 'b', 'c'], ['<?php echo $tr->translate("Riels")?> (R)', '<?php echo $tr->translate("Dollar")?> ($)', '<?php echo $tr->translate("Baht")?> (B)'], ['#21abf6', '#0077c5', "#0f575b"]);
    },
    //init
    $.MorrisCharts = new MorrisCharts, $.MorrisCharts.Constructor = MorrisCharts
}(window.jQuery),

//initializing
function($) {
    "use strict";
    $.MorrisCharts.init();
    
}(window.jQuery);

</script>
 <!-- App Js -->
<script src="<?php echo $this->baseUrl()."/"?>dashboard/js/jquery.app.js"></script>
