<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$rows=$this->cleint;
	$row_old = $this->change_calleteral;
	
?>
<meta charset="utf-8">
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("បង្កាន់ដៃតម្កល់ទ្រព្យដាក់ធានា");?></title>
<form method="post">
</form>
<div style=" width:25cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
p{ line-height: 10px;}
th{padding: 5px;}
ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold; list-style-type: none;}
td ul li{list-style: none; }
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="list-style:none; text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="list-style:none;text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("សំណើរសុំប្តូរ ឯកសារអត្តសញ្ញាណតម្កល់ធានា");?></li>
                			<li style="list-style:none;text-align:center; font-size:13px;"></li>
                		</ul>
                	</td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                <?php //if(empty($this->calleteral_list)){?>
                 <tr align="center" style="font-weight:bold; line-height: 20px; font-size:9px; padding:5px 0px; ">
                    <td colspan="3" style="font-family:'Khmer MEF2';text-align: left; border:1px solid #fff; border-bottom: 1px solid #000;" valign="top">
						 <p style="font:12px 'Khmer OS Content';line-height: 18px;">ខ្ញុំបាទ / នាងខ្ញុំឈ្មោះ........<strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $rows['name_kh']?></strong>....ភេទ...<?php echo $rows['gender']?>. ថ្ងៃខែឆ្នំាកំណើត....<?php echo date("d-m-Y",strtotime($rows['dob']));?>...<strong style="font-weight: bold;font:12px 'Khmer MEF2'"></strong>..................<strong style="font-weight: bold;font:12px 'Khmer MEF2';"></strong>.......។</p>
						 <p style="font:12px 'Khmer OS Content';line-height: 18px;">អាស័យដ្ឋានបច្ចុប្បន្ន : ផ្ទះលេខ...<?php echo $rows['house'];?>....ក្រុមទី.......ភូមិ..<?php echo $rows['village_name'];?>.ឃុំ,សង្កាត់..<?php echo $rows['commune_name'];?>.. ស្រុក,ខណ្ឌ,ក្រុង..<?php echo $rows['district_name'];?>..ខេត្ដ,រាជធានី...<?php echo $rows['province_en_name'];?>............។</p>
						 <p style="font:12px 'Khmer MEF2';line-height: 15px;">សំណើរសុំប្តូរ </p>
						 <?php if(!empty($row_old))foreach ($row_old as $key =>$row){?>
						 	<p style="font:12px 'Khmer OS Content';line-height: 18px;"><?php echo $key+1;?> .<strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['collecteral_title_old'];?></strong>&nbsp;លេខៈ...<?php echo $row['from_number_collateral'];?>...ចុះថ្ងៃទី..<?php echo date("d",strtotime($row['from_issue_date']));?>..ខែ..<?php echo date("m",strtotime($row['from_issue_date']));?>..ឆ្នាំ..<?php echo date("Y",strtotime($row['from_issue_date']));?>..ម្ចាស់កម្មសិទ្ធឈ្មោះ...<strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['from_owner_name'];?></strong>...ចេញដោយ <strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['from_issueby'];?></strong>។</p>
						 <?php }?>
						 <p style="font:12px 'Khmer MEF2';line-height: 15px;">ពី អេហ្វ ខេអេច ផន សប ដោយដាក់ជំនូសមកវិញដោយ  </p>
                   		<?php if(!empty($row_old))foreach ($row_old as $key =>$row){?>
						 	<p style="font:12px 'Khmer OS Content';line-height: 18px;"><?php echo $key+1;?> .<strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['collecteral_title_en'];?></strong> &nbsp;លេខៈ...<?php echo $row['number_collateral'];?>...ចុះថ្ងៃទី..<?php echo date("d",strtotime($row['issue_date']));?>..ខែ..<?php echo date("m",strtotime($row['issue_date']));?>..ឆ្នាំ..<?php echo date("Y",strtotime($row['issue_date']));?>..ម្ចាស់កម្មសិទ្ធឈ្មោះ...<strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['toowner_name'];?></strong>......ចេញដោយ <strong style="font-weight: bold;font:12px 'Khmer MEF2'"><?php echo $row['note'];?></strong>។</p>
						 <?php }?>
						 <p style="font:12px 'Khmer OS Content';line-height: 18px;">អាស្រ័យដូចបានជំរាបជូនខាងលើ សូមលោកនាយក មេត្តាពិនិត្យសំណើរ និងផ្តល់ដល់ខ្ញុំបាទ/នាងខ្ញុំដោយក្តីអនុគ្រោះ ។</p>
                    	<p style="font:12px 'Khmer OS Content';line-height: 18px;">សូមលោកនាយក មេត្តាទទួលនូវការគោរពដ៏ខ្ពង់ខ្ពស់អំពី ខ្ញុំបាទ/នាងខ្ញុំ ។</p>
                    </td>
                </tr>
                 <tr>
                	<td align="center" valign="top" width="33%">
                	    <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                		<p style="font:12px 'Khmer MEF2';line-height: 18px;">តំណាង អេហ្វ ខេអេច ផន សប</p>
						<p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខានិងត្រា</p> 
						<p style="height:100px;"></p>
						<p style="font:12px 'Khmer MEF2';line-height: 18px;">ឈ្មោះ..................................</p>
                	</td>
                	<td align="center" valign="top" width="33%">
                	     <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                	     <p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខា ឬ ស្នាមមេដៃស្តាំអ្នកប្រគល់</p>
						 <p style="height:120px;"></p>
						 <p style="font:12px 'Khmer MEF2';line-height: 18px;">ឈ្មោះ..................................</p>
                	</td>
                	<td align="center" valign="top">
                	     <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                	     <p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខា ឬ  ស្នាមមេដៃស្តាំអ្នកសុំប្តូរ</p>
						 <p style="height:120px;"></p>
						 <p style="font:12px 'Khmer MEF2';line-height: 18px;">ឈ្មោះ..................................</p>
                	</td>
                </tr>
                <tr>
                	<td colspan="3" align="center" valign="top" style="border-right: 1px solid #fff;border-left: 1px solid #fff;"><p style="font:12px 'Khmer OS Content';">ខាងក្រោមនេះសម្រាប់ប្រើប្រាស់នៅពេលដែលអតិថិជនសងបំណុលរួច ហើយដកយក​​​​​​​​​​​​​​​ឯកសារ បញ្ជាក់កម្មសិទ្ធរបស់ខ្លួនទៅវិញ</p></td>
                </tr>
                <tr>
                	<td align="center" valign="top">
                	    <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                		<p style="font:12px 'Khmer MEF2';line-height: 18px;">តំណាង អេហ្វ ខេអេច ផន សប</p>
						<p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខានិងត្រាអ្នកប្រគល់</p> 
						<p style="height:83px;"></p>
						<p style="font:12px 'Khmer MEF2';line-height: 18px;">ឈ្មោះ..................................</p>
                	</td>
                	<td align="center" valign="top">
                	     <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                	     <p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខា ឬ ស្នាមមេដៃស្តាំអ្នកប្រគល់</p>
						 <p style="height:100px;"></p>
						 <p style="font:12px 'Khmer MEF2';line-height: 18px;vertical-align: bottom;">ឈ្មោះ..................................</p>
                	</td>
                	<td align="center" valign="top">
                	     <p style="font:12px 'Khmer OS Content';line-height: 18px;">ថ្ងៃទី..........ខែ...........ឆ្នាំ.........</p> 
                	     <p style="font:12px 'Khmer MEF2';line-height: 18px;">ហត្ថលេខា ឬ  ស្នាមមេដៃស្តាំអ្នកទទួល</p>
						 <p style="height:100px;"></p>
						 <p style="font:12px 'Khmer MEF2';line-height: 18px;">ឈ្មោះ..................................</p>
                	</td>
                </tr>
                <tr>
                	<td colspan="3" style="font:12px 'Khmer OS Content'; line-height: 18px;border: 1px solid #fff;border-top: 1px solid #000;" valign="top">សេចក្តីបញ្ជាក់៖ ម្ចាស់កម្មសិទិ្ធត្រូវតែរក្សាបង្កាន់ដៃនេះ   ដើម្បីដកយកឯកសារទ្រព្យ ដាក់ធានាត្រលប់ទៅវិញ ។មានតែអ្នកដែលផ្តិតមេដៃតម្កល់ទេ ទើបមានសិទ្ធដកយកឯកសារបញ្ជាក់កម្មសិទ្ទទៅវិញបាន។ ក្នុងករណីបាត់បង្កាន់ដៃនេះ   អេហ្វ ខេអេច ផន សប តម្រូវអាយម្ចាស់កម្មសិទ្ធស្របច្បាប់ធ្វើលិខិតបញ្ចាក់ពីអាជ្ញាធរ ភូមិ ឃុំ/សង្កាត់ មកអោយអេហ្វ ខេអេច ផន សប ទើបអាចដកបាន។ </td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
</div>
</div>
