<?php
	 $tr = Application_Form_FrmLanguages::getCurrentlanguage();	
    echo $this->headTitle($tr->translate('TRANSFER_CO_CO')); 
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferco','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
  if(this.validate()) {
    if(dijit.byId('branch_name').get('value')==''){
     alert('Please Select Branch');
     dijit.byId('branch_name').focus();
     return false;
   	}
    if(dijit.byId('co_code').get('value')==''){
     alert('Please Select CO Code');
     dijit.byId('co_code').focus();
     return false;
   	}
	if(dijit.byId('formc_co').get('value')==''){
     alert('Please Select CO Name');
     dijit.byId('formc_co').focus();
     return false;
   	}
	if(dijit.byId('to_co_code').get('value')==''){
     alert('Please Select To CO Code');
     dijit.byId('to_co_code').focus();
     return false;
   	}
	if(dijit.byId('to_co').get('value')==''){
     alert('Please Select To CO Name');
     dijit.byId('to_co').focus();
     return false;
   	}
	if(dijit.byId('formc_co').get('value')== dijit.byId('to_co').get('value')){
		alert("can not transfer the same co");
		dijit.byId('to_co').focus();
		return false;
	}
    dijit.byId("btn_save").set("disabled",true);
    dijit.byId("btn_save_close").set("disabled",true);
    return true;
   }else {
    return false;
   }
</script>
<fieldset  style="background: #e0ebff">
<table cellspacing="10" class='fullside'>
	<legend class="mainblog" align="center"><strong><?php echo $tr->translate('TRANSFER_CO_CO');?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="10"  >
			    <tr>
					<td><?php echo $tr->translate("BRANCH_NAME")?></td>
					<td><?php  echo $frm->getElement('branch_name');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("FROM_CO")?></td>
					<td><?php  echo $frm->getElement('co_code');?></td>
			    </tr>
			    <tr>
			  		<td><?php echo $tr->translate("FROM_CO")?></td>
					<td><?php  echo $frm->getElement('formc_co');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("NOTE")?></td>
					<td><?php  echo $frm->getElement('Note');?></td>
			    </tr>
			</table>
		</fieldset>	
		</td>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('CO_INFO');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="10"  >
			 	<tr>
					<td><?php echo $tr->translate("TO_CO")?></td>
					<td><?php  echo $frm->getElement('to_co_code');?></td>
				</tr>
			 	<tr >
					<td><?php echo $tr->translate("TO_CO")?></td>
					<td><?php  echo $frm->getElement('to_co');?></td>
				</tr>
			    <tr>	
					<td><?php echo $tr->translate("DATE")?></td>
					<td><?php  echo $frm->getElement('Date');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("STATUS")?></td>
					<td><?php  echo $frm->getElement('status');?></td>
				</tr>
			</table>
		</fieldset>
		</td>
		<td>
			<fieldset style="min-height: 153px;background: #f3feff;">
		        <legend style="text-align: center;"><strong>សម្គាល់</strong></legend>
		        	<span>&nbsp;រាល់ទិ&#8203;ន្នន័យទាំងអស់នឹងត្រូវបានផ្ទេរពី COចាស់មក CO ថ្មីដូចជា ៖</span>
	        		<ul style="padding-left:5px;">
			        	<li>១. ប្រាក់បានបង់ពីមុន ទាំងអស់</li>
			        	<li>២. កម្ចីដែលបានទំលាក់ទាំងអស់</li>
			        	<li>៣. តារាងកាលវិភាគដែលត្រូវបង់ ទាំងអស់</li>
		        	</ul>
            </fieldset>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="2">
			<input type="button" onclick="submitDataClose()" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" id="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<input type="submit" value="រក្សាទុក" name="btn_save" id="btn_save" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("formc_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("formc_co").get('value');
			dijit.byId("formc_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("to_co").get('value');		
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}else if(type==4){
			to = dijit.byId("to_co_code").get('value');
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}
	}

	function submitDataClose(){
		if(dijit.byId('branch_name').get('value')==''){
		     alert('Please Select Branch');
		     dijit.byId('branch_name').focus();
		     return false;
		   	}
		    if(dijit.byId('co_code').get('value')==''){
		     alert('Please Select CO Code');
		     dijit.byId('co_code').focus();
		     return false;
		   	}
			if(dijit.byId('formc_co').get('value')==''){
		     alert('Please Select CO Name');
		     dijit.byId('formc_co').focus();
		     return false;
		   	}
			if(dijit.byId('to_co_code').get('value')==''){
		     alert('Please Select To CO Code');
		     dijit.byId('to_co_code').focus();
		     return false;
		   	}
			if(dijit.byId('to_co').get('value')==''){
		     alert('Please Select To CO Name');
		     dijit.byId('to_co').focus();
		     return false;
		   	}
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId('btn_save').set('disabled',true);
			dijit.byId('btn_save_close').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferco','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/loan/transferco";
				},
				error: function(e) {
				}
			});
		}
	}
</script>
