<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<?php 
    $tran = $this->tran_schedule;
	$client = $this->client;
	$frm = $this->frm_search;
?>
<style>
.style1:hover{ background: #ccc;}
</style>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("LOAN_LATE");?></title>
<form method="post">
<table style="font-family: 'Khmer OS Content';width:28.2cm; margin:0 auto;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   	</tr>
   	<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<br/>
<div style=" width:28.2cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 0.2cm;">
<div id="divPrint">
<style>

.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_LATE");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("D-d-m-Y",strtotime($this->list_end_date));?></li>
                		</ul>
                	<td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
              <thead>
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 24px;font-size:9px; font-family: 'Khmer OS Content';white-space: nowrap;">
                    <td><?php echo $tr->translate("NUM");?></td>
                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td><?php echo $tr->translate("LOAN_NO");?></td>
                    <td><?php echo $tr->translate("CLIENT_NUM");?></td>
                    <td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
                    <td><?php echo $tr->translate("CO_NAME");?></td>
                    <td><?php echo $tr->translate("INTEREST RATE");?></td>
                    <td><?php echo $tr->translate("LOAN_PERIOD");?></td>
                    <td><?php echo $tr->translate("PRINCIPAL");?></td>
                    <td><?php echo $tr->translate("PRINCIPAL_PERMONTH");?></td>
                    <td><?php echo $tr->translate("INTEREST");?></td>
                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
                    <td><?php echo $tr->translate("PAYMENT");?></td>
                    <td><?php echo $tr->translate("LATE_DAY");?></td>
                    <td><?php echo $tr->translate("PAY_DATE");?></td>
                </tr>
                </thead>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;
                	 $pene_amr=0; $pene_amb=0;$pene_amd=0;
                	 $serv_amr=0;$serv_amb=0;$serv_amd=0;
                	 $saving_r=0;$saving_d=0;$saving_b=0;
                ?>
                <?php $i=1;?>
               <?php if(!empty($this->loanlate_list))foreach ($this->loanlate_list as $index => $rs){ ?>
                <tr class="style1" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content'; white-space: nowrap;">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["total_duration"]." ".$rs["Term Borrow"];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_principal"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;
               			<?php $end_dat = $this->list_end_date;
	               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
	               			//echo $total_pay;
	               			if ($rs['last_pay_date']==null or $rs['last_pay_date']==""){
	               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
	               				$amount_lateday=$total_day/(60*60*24)-$free_day;
	               				$total_late_day=$total_day/(60*60*24);
	               			}else {
	               				$total_day=strtotime($end_dat)-strtotime($rs['last_pay_date']);
	               				$total_late_day=$total_day/(60*60*24);
	               				$amount_lateday=$total_day/(60*60*24);
	               			}
	               			$pay_term=$rs['collect_typeterm'];
	               			if($amount_lateday<0){
	               				$amount_lateday=0;
	               				$result=0;
	               			}
	               			else {
	               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
	               				if ($pay_term==1){
	               					$result=$total_pay*(2*($rs['interest_rate']/100)/1)*($amount_lateday);
	               				}
	               				if ($pay_term==2){
	               					$result=$total_pay*(2*($rs['interest_rate']/100)/7)*($amount_lateday);
	               				}
	               				if ($pay_term==3){
	               					$result=$total_pay*(2*(($rs['interest_rate']/100)/30))*($amount_lateday);
	               				}
	               			}
	               			$penelize = $rs['penelize']+$result;
	               			//echo $penelize;
	               			//echo str_replace('.00', '', number_format($penelize,2));
	               			$total_payment = $penelize+$rs['principle_after']+$rs['total_interest_after'];
               				echo number_format($penelize,2).' '.$rs['currency_type'];
               			
               			
               			?>&nbsp;
               		</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($total_payment,2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="center" style="background: rgba(255, 0, 0, 0.65);">&nbsp;&nbsp;<?php echo $total_late_day." Days";?> &nbsp;</td>
               		<td align="center">&nbsp;&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
               		<!--<td align="center" style="width:100px;">&nbsp;<?php //echo  str_replace(' ', '', $rs["time_collect"]);?>&nbsp;</td> -->
                </tr>
                
                <?php 
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal'];
		               		$amt_r2 = $amt_r2+$rs['principle_after'];
		               		$amt_r3 = $amt_r3+$rs['total_interest_after'];
		               		$pene_amr=$pene_amr+$penelize;
		               		$amt_r4 = $amt_r4+$total_payment;
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal'];
							$amt_d2 = $amt_d2+$rs['principle_after'];
							$amt_d3 = $amt_d3+$rs['total_interest_after'];
							$pene_amd=$pene_amd+$penelize;
							$amt_d4 = $amt_d4+$total_payment;
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal'];
							$amn_b2 = $amn_b2+$rs['principle_after'];
							$amn_b3 = $amn_b3+$rs['total_interest_after'];
							$pene_amb= $pene_amb+$penelize;
							$amn_b4 = $amn_b4+$total_payment;
		               }
		               $amount_days = strtotime($this->list_end_date)-strtotime($rs["date_payment"]);
		               $amount_days =  floor($amount_days/(60*60*24));
		               //echo $this->list_end_date['end_date'];
               ?>
                <?php }?>
               
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate('CURRENT_TYPE');?></td>                  
                    <td><?php echo $tr->translate("TOTAL_PRINCIPLE");?></td>
                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amd,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amr,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($pene_amb,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                </tr>
              </table>
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>