<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('REPORT_PAWN_WRITE_OFF'));
 $frm = $this->frm_loan;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style=" min-width:29cm;margin:0 auto;" >
	<tr>
		<td><?php echo $frm->getElement('adv_search');?></td>
		<td><?php echo $frm->getElement('branch_id');?></td>
		<td><?php echo $frm->getElement('members');?></td>
		<td><?php echo $frm->getElement('product_id');?></td>
	</tr>
	<tr>
		<td><?php echo $frm->getElement('currency_type');?></td>
		<td><?php echo $frm->getElement('start_date');?></td>
		<td><?php echo $frm->getElement('end_date');?></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		<td></td>
		<td></td>
	</tr>
</table>
</form>
<div style="width:100%; margin:0 auto;">
<div style=" min-width:29cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.25cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
.hover:hover{ background:#ccc;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<table width="100%" >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_PAWN_WRITE_OFF");?></li>
                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                    </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
                <?php 
                	  $amt_r = 0;
                	  $amt_d = 0;
                	  $amn_b = 0;
					  $count_d = 0;$count_r=0;$count_b=0;
                ?>
                <thead>
	               <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:10px 0px; ">
	                    <th><?php echo $tr->translate("NUM");?></th>
	                    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th><?php echo $tr->translate("PAWN_CODE");?></th>
	                    <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
						<th><?php echo $tr->translate("PHONE");?> / <?php echo $tr->translate("ADDRESS");?></th> 
	                    <th><?php echo $tr->translate("LOAN_AMOUNT");?></th> 
	                    <th><?php echo $tr->translate("INTEREST RATE");?></th>
	                    <th><?php echo $tr->translate("LOAN_PERIOD");?></th>
	                    <th>&nbsp;<?php echo $tr->translate("PAWN_DATE");?>&nbsp;</th>
	                    <th>&nbsp;<?php echo $tr->translate("PAWN_ENDDATE");?>&nbsp;</th>
	                    <th><?php echo $tr->translate("PRODUCT_NAME");?></th> 
	                    <th><?php echo $tr->translate("EST_VALUE");?></th>
	                    <th><?php echo $tr->translate("DATE");?></th>
	                    <th><?php echo $tr->translate("NOTE");?></th> 
	                </tr>
                </thead>
                <?php 
                    $record = 0; if(!empty($this->LoanCollectionco_list))
                	foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php 
                  if($rs["curr_type"]==1){//reil
                  	$count_r=$count_r+1;
                  	$amt_r = $amt_r+$rs["loan_amount"];
                  }elseif($rs["curr_type"]==2){
                  	$amt_d = $amt_d+$rs["loan_amount"];
                  	$count_d=$count_d+1;
                  }else{
                  	$amn_b = $amn_b+$rs["loan_amount"];
                  	$count_b = $count_b+1;
                  }
                ?>
	                <tr class="style hover" style="font-family: 'Khmer OS Content'; line-height:20px; ">
	               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $record; ?>&nbsp;</td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["client_number"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["client_name"];?></td>
	               		<td style="font-size: 10px; max-width: 200px; white-space:normal;">&nbsp;&nbsp;<?php echo $rs["phone"];?><?php echo $rs['village_name'].",".$rs['village_name'].",".str_replace("Commune","",$rs['commune_name']).",".$rs['district_name'].",".$rs['province_en_name'];?></td>
						<td style="font:bolder 12px Arial ;text-align: center;​">&nbsp;&nbsp;<?php echo number_format($rs["loan_amount"],2).''.$rs['currency_type'];?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;<?php echo $rs['total_duration'].$rs['termborrow'];//$rs['pay_term'];?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center; white-space:nowrap; ">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center; white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
	               		<td ><?php echo $rs["product_name"];?></td>
	               		<td style="font:bolder 11px Arial ;text-align: center;background:#eeeeee;"><?php echo $rs["est_amount"];?></td>
	               		<td style="font-size: 12px;text-align: center; white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_dach"]));?>&nbsp;</td>
	               		<td style="font-size: 12px;">&nbsp;<?php echo $rs["note_dach"];?>&nbsp;</td>
	                </tr>
                <?php }?>
	                <tr>
		                <td colspan="14">
			               <br /><table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			                <tr bgcolor="#c1d0f3" class="style" style="font-weight:bold; line-height: 24px; text-align: center;">
			                    <th><?php echo $tr->translate("CURRENT_TYPE");?></th>
			                    <th>&nbsp;<?php echo $tr->translate("PAWN_NUMBER");?></th>                 
			                    <th><?php echo $tr->translate("TOTAL_PRINCEPLE");?></th>
			                </tr>
			                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
			                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
			                    <td>&nbsp;<?php echo $count_d;?></td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
			                </tr>
			                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
			                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
			                    <td>&nbsp;<?php echo $count_r;?></td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
			                </tr>
			                <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
			                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($count_b,2);?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
			                </tr>
			              </table>
	              	   </td>
		           </tr>
             </table>
    	</td>
    </tr>
</table>
<br />
 <table align="center" width="100%">
   <tr style="font-size: 14px;">
        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
        <th></th>
        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
        <th></th>
        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
   </tr>
</table>
</div>
</div>
</div>