<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('REPROT_PAWN_SALE'));
 $frm = $this->frm_loan;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content';" >
	<tr>
		<td><?php echo $frm->getElement('adv_search');?></td>
		<td><?php echo $frm->getElement('start_date');?></td>
		<td><?php echo $frm->getElement('end_date');?></td>
		<td><?php echo $frm->getElement('status');?></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	</tr>
</table>
</form>

<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style="width:100%; margin:0 auto;">
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:17px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPROT_PAWN_SALE");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->search['end_date']));?></h2>
                    </td>
                    <td width="20%"></td>
                </tr> 
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;white-space: nowrap;" cellspacing="0">
                <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 24px;  padding:10px 0px; ">
                    <th style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("INVOICE_NO");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th> 
                    <th style="padding:5px 0px;"><?php echo $tr->translate("SEX");?></th>                   
                    <th style="padding:5px 0px;"><?php echo $tr->translate("PHONE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("ADDRESS");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("PRODUCT_NAME");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("SELLING_PRICE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("DESCRIPTION");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("SELLING_DATE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("USER");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("STATUS");?></th>
                </tr>
                
                <?php $i=0;if(!empty($this->rs)) foreach ($this->rs as $rs){$i++; ?>

                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 11px; text-align: center;">&nbsp;<?php echo $i; ?>&nbsp;</td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["invoice_no"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["customer_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["sex"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["tel"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["address"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["product_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo "$ ".number_format($rs["selling_price"],2);?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["description"];?></td>
               		
               		<td style="font-size: 11px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["selling_date"]));?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo $rs["user_name"];?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo $rs["status"];?></td>
                </tr>
                <?php }?>
            </table>
            
            <br />
              
            <table align="center" width="100%">
				<tr style="font-size: 12px;">
			        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
			   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>