<?php 
	defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//$frm=$this->form;
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$session_user=new Zend_Session_Namespace('authloan');
	$request=Zend_Controller_Front::getInstance()->getRequest();
?>						 
<title><?php echo $tr->translate("PRODUCT_INFO");?></title>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
dojo.require("dojo.NodeList-manipulate");
</script>
<form id='frm_add_tran' action="" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				dijit.byId('savenew').set('disabled',true);
			    dijit.byId('saveclose').set('disabled',true);
				return true;
			}else {
				return false;
			}
	</script>
<fieldset style="background: #e0ebff">
<table width="100%" style="margin-top:0px;" cellspacing="10">
     <legend class="mainblog" ><strong><?php echo $tr->translate("PRODUCT_INFO")?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
			 <fieldset >
				<legend align="center" ><strong><?php echo $tr->translate("PRODUCT_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
					    <tr>
					    	<td><strong><?php echo $tr->translate("ឈ្មោះទំនិញ")?></strong></td>
							<td><input class="fullside" dojoType="dijit.form.ValidationTextBox" required="1" id="name" name="name" value="" type="text"></td>
					    </tr>
					    <tr >
							<td><?php echo $tr->translate("លេខកូដ")?></td>
							<td><input class="fullside" dojoType="dijit.form.TextBox" id="pro_code" name="pro_code" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TYPE")?></td>
							<td><input id="product_type" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រភេទផលិតផល")?></td>
							<td><input id="category_id" /></td>
						</tr>
						<tr>
					    	<td><strong><?php echo $tr->translate("ថ្លៃដើម")?></strong></td>
							<td><input class="fullside" dojoType="dijit.form.NumberTextBox" required="true" id="cost_price" name="cost_price" value="" type="text"></td>
					    </tr>
					     <tr>
					  		<td ><strong><?php echo $tr->translate("ថ្លៃលក់")?></strong></td>
							<td><input class="fullside" dojoType="dijit.form.NumberTextBox" required="true" id="selling_price" name="selling_price" value="" type="text"></td>
					    </tr>
				</table>
			</fieldset>	
		</td>
		<td width="66%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("QTY_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
							<td colspan="2">
								<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
									</table>
								<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
							</td>
					    </tr>
					    <tr>
							<td colspan="2"><input type="button" onclick="addNewProLocation();" label="<?php echo $tr->translate("ADD_BRANCH")?>"  dojoType="dijit.form.Button"	 iconClass="dijitIconNewTask"/></td>
						</tr>
					    <tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td></td>
						</tr>
					     <tr>
							<td colspan="2"><input class="fullside" dojoType="dijit.form.TextBox" id="description" name="description" value="" type="text"></td>
						</tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
</fieldset>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
</div>
</form>
<script>
var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );

$('#product_id').submit(function() {
	category = $("#category").val();
    if(category==''){
        alert("សូមជ្រើសរើស ប្រភេទផលិតផល! ");
        $('#category').select2('open');
        return false;
    }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	    
	}
});
dojo.ready(function(){	
	new dijit.form.FilteringSelect({
		store: cate_store,
		required: false,		           
		name: "category_id",
		id: "category_id",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			//member = dijit.byId('member').get('value');
			
	}
		}, "category_id");
	new dijit.form.FilteringSelect({
		store: cate_store,
		required: false,		           
		name: "product_type",
		id: "product_type",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			
	    }
		}, "product_type");
	addNewProLocation();
	
});
	index = 0;
	
	function totalQty(index){
		o_measure = $('#qty_unit').val();
		unit_qty = $('#current_qty_'+index).val();
		other_qty = $('#other_qty_'+index).val();
		total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
		total_qty = parseFloat(unit_qty)+ total_other_qty;
		$('#total_qty_'+index).val(total_qty);
	}
	
	function doTotalQty(){
		o_measure = $('#qty_unit').val();
		if(o_measure=="" || o_measure==0){
			$('#qty_unit').val(1);
		}
		var identity = $('#identity').val();
		if(identity!=""){
			var arrays = identity.split(',');
			for(var index=0;index<arrays.length;index++) {
				o_measure = $('#qty_unit').val();
				unit_qty = $('#current_qty_'+index).val();
				other_qty = $('#other_qty_'+index).val();
				total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
				total_qty = parseFloat(unit_qty)+ total_other_qty;
				$('#total_qty_'+index).val(total_qty);
			}
		}
		var strings = arrays.join(',');
	}
var template = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
branch_opt = '<?php echo $this->rsbranch;?>';
function addNewProLocation(){
		col++;no++;
		template='';
		if(title!=1){    
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("BRANCH_NAME");?></th>';
			temp+='<th ><?php echo $tr->translate("CURRENT_QTY");?></th>';
			temp+='<th ><?php echo $tr->translate("ចំនួនជិតអស់ពីស្តុក");?></th>';
			temp+='<th><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		 }
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center"><select id="branch_id'+col+'" name="branch_id'+col+'" dojoType="dijit.form.FilteringSelect">'+branch_opt+'</select></td>';
			template+='<td width="20%"><input dojoType="dijit.form.NumberTextBox" type="text" required="true" id="total_qty_'+col+'" name="total_qty_'+col+'" value="" /></td>';
			template+='<td width="25%"><input type="text"  name="alert_qty'+col+'" class="fullside" id="alert_qty'+col+'" dojoType="dijit.form.NumberTextBox" /></td>';
			template+='<td width="25%"><input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
}

function deleteRecord(index,type) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	function getPopupCategory(){
		val = $('#category').val();
		if(val==-1){
			$('#categorypopup').modal('show');
		}
	}
	<?php $url_add_category =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-category')); ?>
	function addNewCategory(){
		var cat_name  = $("#cat_name").val();
		$.ajax({
			url: "<?php echo $url_add_category;?>",
			type: "post",
			data: $('#frmCat').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#category').append($("<option></option>").attr("value",rs['cat_id']).attr("selected",true).text(cat_name));                       
				 $("#category").select2();
				$('#categorypopup').modal('hide');
			},
			error:function(err){
				alert("faile insert");
			}
		});
	}
	
</script>