<?php 
	$frm = $this->formFilter;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("PRODUCT");?></title>
<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table width="100%">
	   <tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	   		<td> <?php echo $frm->getElement('branch_id');?></td>
	   		<td><?php echo $frm->getElement("product_type");?></td>
	   		<td><?php echo $frm->getElement("category");?></td>
	   </tr>
	   <tr>
	   		<td><?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement('end_date');?></td>
	   		<td><?php echo $frm->getElement('status');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
</form>
<?php echo $this->list; ?>