<?php	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('LOAN_RESCHEDULE'));
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$graiceperiod = $this->graiceperiod;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.html");
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'repaymentschedule','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
            branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if(dijit.byId('get_laonnumber').get('value')==''){
			   alert('Please Select Loan Number!');
			   dijit.byId('get_laonnumber').focus();
			   return false;
			}
			if(dijit.byId('customer_code').get('value')==''){
			   alert('Please Select	Customer Code!');
			   dijit.byId('customer_code').focus();
			   return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
  				dijit.byId("savenew").set("disabled",true);
				dijit.byId("saveclose").set("disabled",true);
				return true;
			}else {
				return false;
			}
</script>
<fieldset style="background: #e0ebff">
<table cellspacing="5" width="100%">
	<legend class="mainblog"><strong><?php echo $tr->translate("INFO_INDILOAN");?></strong></legend>
	<tr>
		<td valign="top">
			<fieldset>
			     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				    <tr>
						<td><?php echo $tr->translate("BRANCH_NAME");?></td>
						<td><?php echo $frm->getElement('branch_id');?></td>
				    </tr>
				    <tr>
				        <td><strong><?php echo $tr->translate("LOAN_NO");?></strong></td>
						<td><?php echo $frm->getElement('get_laonnumber');?></td>
				    </tr>
				</table>
			</fieldset>	
		</td>
		<td valign="top">
			<fieldset>
			     <legend align="center" ><strong><?php echo $tr->translate('CUSTOMER_INFO');?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				 	<tr>
						<td><?php echo $tr->translate("CUSTOMER_CODE");?></td>
						<td><input id="customer_code" /></td>
					</tr>
				 	<tr>
						<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
						<td><input id="member" /></td>
					</tr>
				</table>
			</fieldset>
		</td>
		<td valign="top">
			<fieldset>
			     <legend align="center"><strong><?php echo $tr->translate('SERVICE_INFO');?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
					<tr>
						<td><?php echo $tr->translate("PAID_PRINCIPAL");?><input dojoType="dijit.form.TextBox" required="true" id="loan_code" name="loan_code" type="hidden"></td>
						<td><?php echo $frm->getElement('principle_paid');?>
						<?php echo $frm->getElement('instalment_date');echo $frm->getElement('old_payterm');echo $frm->getElement('old_release_date');echo $frm->getElement('old_rate');?>
					</tr>
					<tr>
						<td><?php echo $tr->translate("INPUT_DATE");?></td>
						<td><?php echo $frm->getElement('date_payment');?></td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>
	<tr>
		<td colspan="6"  style="border-bottom:1px solid #ccc;    background: none repeat scroll 0 0 #bbcff3;"><strong><?php echo $tr->translate("LOAN_RESCHEDULE");?></strong></td>
	</tr>
	<tr>
		<td width="30%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('INFO_ILLOAN');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			     <tr>
			    	<td><strong><?php echo $tr->translate("LOANOUTSTADING");?></strong></td>
					<td><?php echo $frm->getElement('deposit');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("MORE_LOAN");?></td>
					<td><?php echo $frm->getElement('loan_fee');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("DESCRIPTION");?></td>
					<td><?php echo $frm->getElement('noted');?></td>
			    </tr>
			    <tr>
					<td><strong><?php echo $tr->translate("TOTAL_AMOUNT");?></strong></td>
					<td><?php echo $frm->getElement('total_amount');?></td>
			    </tr>
			    <tr>
			        <td><?php echo $tr->translate("CURRENCY");?></td>
					<td align="left"><?php echo $frm->getElement('currency_type');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("REPAYMENT_TYPE");?></td>
					<td><?php echo $frm->getElement('repayment_method');?></td>
			    </tr>
			    <tr>
					<td><strong><?php echo $tr->translate("INTEREST_RATE");?></strong></td>
					<td><?php echo $frm->getElement('interest_rate');?></td>
				</tr>
			</table>
		</fieldset>	
		</td>
		<td width="40%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('TERM_INSTALL');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr>
					<td><?php echo $tr->translate("LOAN_RELEASE");?></td>
					<td><?php echo $frm->getElement('release_date');?></td>
				</tr>
			 	<tr>
					<td><?php echo $tr->translate("TERM_INSTALL");?></td>
					<td><?php echo $frm->getElement('pay_every');?></td>
				</tr>
				<tr>
					<td><strong><?php echo $tr->translate("TERM_BORROW");?></strong></td>
					<td><?php echo $frm->getElement('period');?></td>
				</tr>
				<tr>
					<td style="white-space: nowrap;"><label><?php echo $tr->translate("TERM_GRAICE_PARIOD");?></label >
						(<label style="font-size:10px;" id="graice_type"></label>)
					</td>
					<td><?php echo $frm->getElement('graice_pariod');?></td>
				</tr>
			 	<tr>
					<td><strong><?php echo $tr->translate("FIRST_PAYMENT");?></strong></td>
					<td><?php echo $frm->getElement('first_payment');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("LIFE_LOAN");?></td>
					<td><?php echo $frm->getElement('date_line');?></td>
				</tr>
			    <tr>
					<td><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD");?></label></td>
					<td><?php echo $frm->getElement('amount_collect_pricipal');?></td>
				</tr>
			</table>
		</fieldset>
		</td>
		<td width="30%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate("INFO_FUND");?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				
				<tr>
					<td style="white-space: nowrap;"><?php echo $tr->translate("TIME_COLLECION");?></td>
					<td><?php echo $frm->getElement('time');?></td>
			    </tr>
			    <tr>
			    	<td style="white-space: nowrap;"><?php echo $tr->translate("TERM_FUND");?></td>
					<td><?php echo $frm->getElement('collect_termtype');?></td>
			    </tr>
			    <tr>
					<td><?php echo $tr->translate("AMOUNT_TERM_FUND");?></td>
					<td><?php echo $frm->getElement('amount_collect');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("HOLIDAY_STATUS");?></td>
					<td><?php  echo $frm->getElement('every_payamount');?></td>
				</tr>
			</table>
		</fieldset>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<input type="reset" label="<?php echo $tr->translate("CLEAR");?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="button"  onclick="submitDataClose()" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose'	id='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW");?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();"  label="<?php echo $tr->translate("PREVIEW");?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
</fieldset>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់', onCancel:hideDialog" id="frm_client" style="width:1000px">
	<div id="rpt_print" class="print">
	<div id="t_amountmoneytype" name="t_amountmoneytype"></div>
	</div>
</div>
</div>
</form>
<script type="text/javascript">	
    function checkValidateDate(){
    	debt_term = dijit.byId('pay_every').get('value');
		if(debt_term==1){
			term_d =1; 
		}else if(debt_term==2){
			term_d =7; 
		}else{
			term_d =30; 
		}
		
		collect_term = dijit.byId('collect_termtype').get('value');
		if(collect_term==1){
			term_c =1; 
		}else if(collect_term==2){
			term_c =7; 
		}else{
			term_c =30; 
		}
		debt_amount = dijit.byId('period').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if((collect_amount*term_c)>(debt_amount*term_d)){
			alert('<?php echo $tr->translate("SMS_BORROW_FUND");?>');
			dijit.byId('collect_termtype').focus();
			return false;
		}
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('total_amount').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	
    	collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		dijit.byId('amount_collect_pricipal').attr('value',amount_payment);
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		changeCollectType();
		
		dijit.byId("total_amount").set('readOnly',true);
		dijit.byId("customer_code").set('readOnly',true);
		dijit.byId("member").set('readOnly',true);
		dojo.connect(dojo.byId("deposit"), "onkeyup", function(evt){
			deposit = dijit.byId("deposit").get("value");
			loan_fee = dijit.byId("loan_fee").get("value");
			total_loanamount  = deposit+loan_fee;
			dijit.byId("total_amount").attr("value",total_loanamount);
		});
		dojo.connect(dojo.byId("loan_fee"), "onkeyup", function(evt){
			deposit = dijit.byId("deposit").get("value");
			loan_fee = dijit.byId("loan_fee").get("value");
			total_loanamount  = deposit+loan_fee;
			dijit.byId("total_amount").attr("value",total_loanamount);
		});
		
	  });
	 var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		//getClientInfo(2);
}
	}, "member");

	 var client_number = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient_number));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_number}),
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	readonly:false,
	onChange: function() {
		
}
	}, "customer_code");
	 
	});
	
</script>
<script type="text/javascript">
function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
}
function popupCheckCO (){	
}	
function calCulateEndDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		if(pay_term==3){//month
			mm = a.getMonth()+amount_date+1;
		}else if(pay_term==2){//week
			a.setDate(a.getDate() + (amount_date*7)); 
			var mm = a.getMonth() + 1;
		}else if(pay_term==1){
			a.setDate(a.getDate() + (amount_date)); 
			var mm = a.getMonth() + 1;
		}
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}
function calCulateAdminFee(){
	p_income="<?php echo $this->setting['adminfee']?>";
	t_admin=dijit.byId('total_amount').get('value');
	adminfee=(p_income*(t_admin/100));
	dijit.byId('loan_fee').attr('value',adminfee);
}
function CompareGraicePariod(){
	graice_pariod = dijit.byId('graice_pariod').get('value');
	period = dijit.byId('period').get('value');
	if(graice_pariod>=period){
		alert('<?php echo $tr->translate("AMOUNT_GRAICEPARIOD_THEN_AMOUNT_LOAN");?>');
		dijit.byId('graice_pariod').attr('value',(period-1));
	}
}
function chechPaymentMethod(){
	method_id = dijit.byId('repayment_method').get('value');
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD");?>";
	dijit.byId('amount_collect_pricipal').attr('value',0);

	dijit.byId("amount_collect").set('readOnly',false);
	dijit.byId("collect_termtype").set('readOnly',false);
	
	
	if(method_id==6){
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
		dijit.byId('amount_collect').attr('value',1);
		dijit.byId('amount_collect').set('readOnly',true);
		
	}else if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId("amount_collect").set('readOnly',true);
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').attr('value',2);
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD");?>";
		dijit.byId('amount_collect_pricipal').attr('value','');
		dijit.byId('amount_collect_pricipal').focus();
		setDefaultPaymentAmount();
	}else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}
}
function changeCollectType(){
	get_id = dijit.byId('pay_every').get('value');
	dijit.byId('collect_termtype').attr('value',get_id);
	changeGraicePeroid();
	CalculateDate();
}
function changeGraicePeroid(){
	disp_value = dijit.byId('collect_termtype').attr('displayedValue');
	dojo.byId('graice_type').innerHTML=disp_value;
	calCulateFirstPayment();
}

function getClientInfo(type){
	alert(33);
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
</script>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	calCulateFirstPayment();
}
function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');
	
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = dijit.byId('collect_termtype').get('value');
	amount_date = dijit.byId('amount_collect').get('value');
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
////add preview loan
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloantest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		client = dijit.byId('member').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			alert('Please Select Branch Name!');
			dijit.byId('branch_id').focus();
			return false;
		}
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}
		rs = checkValidateDate();
		if(rs==false){
          return false;			
        }
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				temp='';	fund_title=0;thead='';fund_title=0;
				 		temp='<table class="collape tablesorter" style="font-size:13px;" id="table" width="100%">'
						temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						temp+='<th><?php echo $tr->translate("ចំនួនថ្ងៃ");?></th></tr>';
				for(i=0;i<data.length;i++){
			        r++;
					    temp+='<tr><td align="center">'+r+'</td>';
						temp+='<td>'+data[i].date_payments+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_principal,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						temp+='<td><b>'+dojo.number.format(data[i].total_payment,2)+'<b></td>';
						temp+='<td><b>'+dojo.number.format((data[i].total_principal-data[i].principal_permonth),2)+'<b></td>';
						temp+='<td>'+data[i].amount_day+'</td></tr>';
				 }
				temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("frm_client").show();
			},
			error: function(err) {
				alert("You can not preview this loan number!");
			}
	   });
	}
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
}
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('get_laonnumber').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'loan_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('deposit').attr('value',data.total_principal);
			dijit.byId('total_amount').attr('value',data.total_principal);
			dijit.byId('period').attr('value',data.remaintimes);
			dijit.byId("member").attr('value',data.client_id);
			dijit.byId('customer_code').set('readOnly',true);
			dijit.byId("customer_code").attr('value',data.client_id);
			dijit.byId('member').set('readOnly',true);
			dijit.byId('currency_type').attr('value',data.currency_type);
			dijit.byId('currency_type').set('readOnly',true);
			dijit.byId('interest_rate').attr('value',data.interest_rate);
		    dijit.byId('repayment_method').attr('value',data.payment_method);
		    dijit.byId('branch_id').attr('value',data.branch_id);
		    dijit.byId('branch_id').set('readOnly',true);
		    dijit.byId('loan_code').attr('value',data.loan_number);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
graice_period = '<?php echo $graiceperiod["value"]?>';
var url_getLoanReshcedule = '<?php echo $this->url(array('module'=>'loan','controller'=>'repaymentschedule','action'=>'getloan-reschedule')); ?>';
function getLoanInfoByLoanNumber(){
	loan_id = dijit.byId('get_laonnumber').get('value');
	var oneDay = 24*60*60*1000;
	var date_collect = new Date();
	dojo.xhrPost({
	    url: url_getLoanReshcedule,	
	    content : { 
		    'loan_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('total_amount').attr('value',data.all_total);
		},
		error: function(err) {
		}
	});
}
function loantype(){
	var data=dijit.byId("loan_type").get('value');
	if(data==-1){
		dijit.byId("frm_loantype").show();
		}
}
function zone(){
	zone = dijit.byId('zone').get('value');
	if(zone==-1){
		dijit.byId("frm_zone").show();
	}
}
function submitDataClose(){
	branch_id = dijit.byId('branch_id').get('value');
    if (branch_id=='' || branch_id==-1){
  	   alert('Please Select Branch Name!');
	   dijit.byId('branch_id').focus();
	   return false;
    }
	if(dijit.byId('get_laonnumber').get('value')==''){
	   alert('Please Select Loan Number!');
	   dijit.byId('get_laonnumber').focus();
	   return false;
	}
	if(dijit.byId('customer_code').get('value')==''){
	   alert('Please Select	Customer Code!');
	   dijit.byId('customer_code').focus();
	   return false;
	}
	rs = checkValidateDate();
	if(rs==false){
      return false;			
    }
	if(dijit.byId('frm_add_tran').validate()) {
		dijit.byId("savenew").set("disabled",true);
		dijit.byId("saveclose").set("disabled",true);
		var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'repaymentschedule','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/loan/repaymentschedule";
			},
			error: function(e) {
			}
		});
	}
}
</script>