<?php
	 $tr = Application_Form_FrmLanguages::getCurrentlanguage();	
    echo $this->headTitle($tr->translate('TRANSFER_CO_CO')); 
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferzone','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
  if(this.validate()) {
    if(dijit.byId('branch_name').get('value')==''){
     alert('Please Select Branch');
     dijit.byId('branch_name').focus();
     return false;
   	}
	if(dijit.byId('to_co_code').get('value')==''){
     alert('Please Select To CO ');
     dijit.byId('to_co_code').focus();
     return false;
   	}
    return true;
   }else {
    return false;
   }
</script>
<fieldset>
<table cellspacing="10" class='fullside'>
	<legend><strong><?php echo $tr->translate('TRANSFER_CO_CO');?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
					<td><?php echo $tr->translate("BRANCH_NAME")?></td>
					<td><?php  echo $frm->getElement('branch_name');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("DATE")?></td>
					<td><?php  echo $frm->getElement('Date');?></td>
			    </tr>
			    <tr>
			  		 <td><?php echo $tr->translate("ZONE_NAME")?></td>
					 <td><?php echo $frm->getElement('zone_name');?></td>
			    </tr>
			</table>
		</fieldset>	
		</td>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('CO_INFO');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr >
					<td><?php 	echo $tr->translate("TO_CO")?></td>
					<td><?php 	echo $frm->getElement('to_co');?></td>
				</tr>
				<tr>
					<td><?php 	echo $tr->translate("TO_CO")?></td>
					<td><?php  echo $frm->getElement('to_co_code');?></td>
				</tr>
			    <tr>
			    	  <td><?php echo $tr->translate("NOTE")?></td>
					  <td><?php  echo $frm->getElement('Note');?></td>
			    </tr>
			    <tr>
			    	  <td><?php echo $tr->translate("STATUS")?></td>
					  <td><?php  echo $frm->getElement('status');?></td>
			    </tr>
			</table>
		</fieldset>
		</td>
	</tr>
					 
		<tr>
		<td align="center" colspan="2">
			<input type="submit" value="រក្សាទុក" name="btn_save" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("co_code").attr('value',id);
		}else if(type==3){		
			to = dijit.byId("to_co").get('value');		
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}else if(type==4){
			to = dijit.byId("to_co_code").get('value');
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}
	}
</script>
