
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("TRANSFER_CO_CO"));
$frm = $this->frm_transfer;

?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferzone','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   	<table>
  	<tr>
  	    <td><?php  echo $frm->getElement('note');?></td>
  		<td><?php  echo $frm->getElement('branch_name');?></td>
  		<td><?php  echo $frm->getElement('co_code');?></td>	
  		<td><?php echo $frm->getElement('start_date');?></td>
  		<td><?php echo $frm->getElement('end_date');?></td>
  		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
  	</tr>
  </table>
</form>
 <?php echo $this->list; ?>
