<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("INVOICE"));
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="width:100%; margin:0 auto;">
	<div style=" min-width:29cm; min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.25cm;" >
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				tr.blue {
				    background: #fbf9f9;
				}
				tr.red {
				    background: #ececec;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang'; margin:0; padding:0; border:none;">
			            	<tr>
			                	<td width="20%"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><?php echo $this->sale['branch_nameen'];?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("INVOICE");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">INVOICE</li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			                <tr>
			                	<td colspan="3">
			                		<table align="left" width="40%" style=" line-height:25px; font-family: 'Khmer OS Battambang'; font-size:14px; margin:0; padding:0; border:none;">
			                			<tr>
			                				<td style="width: 30%;"><?php echo $tr->translate("CUSTOMER_NAME")?></td>
			                				<td style="width: 70%;"> : <?php echo $this->sale['name_kh']." (".$this->sale['client_number'].")";?></td>
			                			</tr>
			                			<tr>
			                				<td><?php echo $tr->translate("Tel")?></td>
			                				<td> : <?php echo $this->sale['phone'];?></td>
			                			</tr>
			                		</table>
			                		<table align="right" width="25%" style=" line-height:25px; font-family: 'Khmer OS Battambang'; font-size:14px; margin:0; padding:0; border:none;">
			                			<tr>
			                				<td ><?php echo $tr->translate("SALE_NO")?></td>
			                				<td > : <span style="color: red;"><?php echo $this->sale['saleNO'];?></span></td>
			                			</tr>
			                			<tr>
			                				<td align="left" style="white-space: nowrap;"><?php echo $tr->translate("DATE")?></td>
			                				<td align="left"> : <?php echo date("d M Y",strtotime($this->sale['dateSold']));?></td>
			                			</tr>
			                		</table>
			                	</td>
			                </tr>
			            </table>
			        </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel" valign="top"  style=" width:100%;height: 14cm; border: solid 1px #000; ">
		    			<table width="100%"  style="font-family: 'Khmer OS Battambang';font-size:14px;  border-collapse:collapse; white-space: nowrap;" cellspacing="0">
                				<thead>
					               <tr bgcolor="#c1d0f3" class="style" align="center" style=" border-bottom:solid 1px #000; font-weight:bold; line-height: 25px; font-size:12px; padding:10px 0px; ">
					                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
					                    <td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
					                    <td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
					                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
					                    <td>&nbsp;<?php echo $tr->translate("PRICE");?>&nbsp;</td> 
					                    <td>&nbsp;<?php echo $tr->translate("AMOUNT");?>&nbsp;</td>
					                </tr>
					          	</thead>
                					<?php 
			                	$location="";
			                	$gTotalPurchase=0;
			                    if(!empty($this->saleDetail)) 
			                	foreach ($this->saleDetail as $key => $rs){ 
				                	$gTotalPurchase = $gTotalPurchase + $rs["amount"];
				                	
			                    ?>
				                <tr class="style hover <?php if (($key+1%2)==1){ echo 'blue';}else{ echo 'red';}?>" style="line-height:20px; ">
				               		<td style="font-size: 14px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td align="center" style="font-size: 14px;">&nbsp;&nbsp;<?php echo $rs["item_code"];?></td>
				               		<td align="center" style="font-size: 14px;">&nbsp;&nbsp;<?php echo $rs["item_name"];?></td>
				               		<td align="center" style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["qty"];?></td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["sellingPrice"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["amount"],2);?>&nbsp;</td>
				                </tr>
			                <?php }?>
					                	
                		</table>
			    	</td>
			    </tr>
			    <tr>
			    	<td>
			    		<table width="100%"  style="font-family: 'Khmer OS Battambang';font-size:14px;  border-collapse:collapse; white-space: nowrap;" cellspacing="0">
			                <tbody>
			                	<tr style=" line-height: 30px; font-weight: 600;">
			                		<td width="70%">&nbsp;</td>
			                		<td align="right"><?php echo $tr->translate("TOTAL");?>&nbsp;</td>
			                		<td  align="right"><?php echo "$ ".number_format($this->sale['total'],2)?>&nbsp;</td>
			                	</tr>
			                	<tr style=" line-height: 30px; font-weight: 600;">
			                		<td width="70%">&nbsp;</td>
			                		<td  align="right"><?php echo $tr->translate("PAID");?>&nbsp;</td>
			                		<td  align="right"><?php echo "$ ".number_format($this->sale['paid'],2)?>&nbsp;</td>
			                	</tr>
			                	<tr style="line-height: 30px; font-weight: 600;">
			                		<td width="70%">&nbsp;</td>
			                		<td align="right"><?php echo $tr->translate("BALANCE");?>&nbsp;</td>
			                		<td  align="right"><?php echo "$ ".number_format($this->sale['balance'],2)?>&nbsp;</td>
			                	</tr>
			                </tbody>
			                
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			 <table align="center" width="100%">
			   <tr style="font-size: 14px;">
			        <th style="width:30%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('ហត្ថលេខា និងឈ្មោះអតិថិជន');?></th>
			        <th></th>
			        <th></th>
			        <th style="width:30%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('ហត្ថលេខា និងអ្នកទទួល');?></th>
			   </tr>
			   <tr><td style="height: 30px;">&nbsp;</td></tr>
			   <tr style="font-size: 14px;">
			        <th style="width:30%;text-align:center;  font-family:'Khmer OS Battambang'"><?php echo $this->sale['name_kh'];?></th>
			        <th></th>
			        <th></th>
			        <th style="width:30%;text-align:center;font-family:'Khmer OS Battambang'"><?php echo $this->sale['last_name']." ".$this->sale['first_name'];?></th>
			   </tr>
			</table>
		</div>
	</div>
</div>