<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Report Inventory Purchase Detail"));
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="width:100%; margin:0 auto;">
	<div style=" min-width:29cm; min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.25cm;" >
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang'; margin:0; padding:0; border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Report Inventory Purchase Detail");?></li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			                <tr>
			                	<td colspan="3">
			                		<table align="left" width="40%" style=" line-height:14px; font-family: 'Khmer OS Battambang'; font-size:12px; margin:0; padding:0; border:none;">
			                			<tr>
			                				<td style="width: 30%;"><?php echo $tr->translate("SUPPLIER_NAME")?></td>
			                				<td style="width: 70%;"> : <?php echo $this->purchase['sup_name']." (".$this->purchase['supplier_no'].")";?></td>
			                			</tr>
			                			<tr>
			                				<td><?php echo $tr->translate("Tel")?></td>
			                				<td> : <?php echo $this->purchase['tel'];?></td>
			                			</tr>
			                			<tr>
			                				<td><?php echo $tr->translate("Email")?></td>
			                				<td> : <?php echo $this->purchase['email'];?></td>
			                			</tr>
			                		</table>
			                		<table align="right" width="25%" style=" line-height:14px; font-family: 'Khmer OS Battambang'; font-size:12px; margin:0; padding:0; border:none;">
			                			<tr>
			                				<td ><?php echo $tr->translate("INVOICE_NO")?></td>
			                				<td > : <span style="color: red;"><?php echo $this->purchase['invoice_no'];?></span></td>
			                			</tr>
			                			<tr>
			                				<td><?php echo $tr->translate("BRANCH")?></td>
			                				<td> : <?php echo $this->purchase['branch_namekh'];?></td>
			                			</tr>
			                			<tr>
			                				<td align="left"><?php echo $tr->translate("DATE")?></td>
			                				<td align="left"> : <?php echo date("d M Y",strtotime($this->purchase['date']));?></td>
			                			</tr>
			                		</table>
			                	</td>
			                </tr>
			            </table>
			        </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel">
			            <table width="100%" border="1" style="font-family: 'Khmer OS Content';font-size:12px;  border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
			                <thead>
				               <tr bgcolor="#c1d0f3" class="style" align="center" style=" font-weight:bold; line-height: 25px; font-size:12px; padding:10px 0px; ">
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("UNIT_PRICE");?>&nbsp;</td> 
				                    <td>&nbsp;<?php echo $tr->translate("AMOUNT");?>&nbsp;</td>
				                </tr>
			                </thead>
			                <?php 
			                	$location="";
			                	$gTotalPurchase=0;
			                    if(!empty($this->purchaseDetail)) 
			                	foreach ($this->purchaseDetail as $key => $rs){ 
				                	$gTotalPurchase = $gTotalPurchase + $rs["amount"];
			                    ?>
				                <tr class="style hover" style="line-height:20px; ">
				               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["item_code"];?></td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["item_name"];?></td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["qty"];?></td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["cost"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["amount"],2);?>&nbsp;</td>
				                </tr>
			                <?php }?>
			                	<tr style="font-weight: 600;border-bottom: solid 1px #fff;border-left: solid 1px #fff;border-right: solid 1px #fff;">
			                		<td colspan="5" align="right"><?php echo $tr->translate("TOTAL");?>&nbsp;</td>
			                		<td  align="right"><?php echo "$ ".number_format($gTotalPurchase,2)?>&nbsp;</td>
			                	</tr>
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			 <table align="center" width="100%">
			   <tr style="font-size: 14px;">
			        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
			   </tr>
			</table>
		</div>
	</div>
</div>