<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");
$session_user=new Zend_Session_Namespace('authloan');
$level =$session_user->level;
$loanPayment = $this->loanPayment;
$data = $this->data;
?>
<title><?php echo $tr->translate("PAYMENT_RECEIPT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>

<div style="width:100%; margin:0 auto;">
	<div style="min-width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
		<div id="divPrint">
			<style type="text/css">
				
				td.bgBorderColor {
				    height: 5px;
				    border-top: solid 1px #133b84;
				}
				span.lbtitle {
				    min-width: 100px;
				    display: inline-block;
				}
				span.value{ line-height:12px; min-width:80px; display: inline-block; text-align: center; padding: 0 2px;}
				span.border_bt.value {
				    border-bottom: dashed 1px #000; padding: 0 10px;
				}
				span.borderCo.value {
				    border: 1px solid #133b84;
				    min-height: 35px;
				    width: 100%;
				}
				td.lbtitlev {
				    padding-left: 14px;
				}
				span.borderCo.value label {
				    line-height: 34px;
				}
				table tr td{
					color: #133b84 !important;
				}
		         table table tr td ul li{text-align: center;list-style: none;line-height: 20px; font-weight: bold;}
			</style>
			<table width="100%">
				<tr>
			    	<td align="center" valign="top">
					<?php for($i=0;$i<2;$i++){?>
					<?php if($i==1){?>
						<div style="border-bottom:2px dotted #000;width:100%;margin:50px 0px;"></div>
					<?php }?>
					<table  cellspacing="10" style=" color: #133b84 !important; width:25cm; max-height:14.85cm; white-space:nowrap; font-family:'Khmer OS Battambang'; font-size: 16px; ">
						 <tr valign="top">
							<td align="center" colspan="6" valign="top" height="80">	
								   <table  cellpadding="0" cellspacing="0" style="font-family: 'Times New Roman','Khmer OS Battambang';padding:0; width:100%;white-space:nowrap;">
								   		<tr style="line-height:10px;">
								   			<td width="28%"></td>
								   			<td valign="top">
									   			<ul style="padding-top: 5px; ">
						                			<li style=" line-height: 30px; text-align:center; font-size:18px !important; font-family:'Times New Roman','Khmer MEF2'"><?php echo $loanPayment['branch_nameen'];//$tr->translate("BRAND_TITLE");?></li>
						                			<li style=" line-height: 30px; text-align:center; font-size:17px !important; font-family:'Times New Roman','Khmer MEF2'"><?php echo $tr->translate("PAYMENT_RECEIPT");?></li>
						                			<li style=" line-height: 30px; text-align:center; font-size:17px !important;font-family:'Times New Roman'; font-weight: bold;">PAYMENT RECEIPT</li>
						                		</ul>
							                </td>
							                <td width="28%" valign="bottom">
							                	<ul style="padding-top: 5px;">
						                			<li style="text-align:left; font-size:14px !important; font-family:'Times New Roman','Khmer OS Battambang'"><span class="lbtitle">កាលបរិច្ឆេទ</span> : <span class=" value"><strong class="fonttel" style="font-size:12px;"><?php echo date('d/m/Y H:i:s');?></strong></span></li>
						                			<li style="text-align:left; font-size:14px !important; font-family:'Times New Roman','Khmer OS Battambang'"><span class="lbtitle">បង្កាន់ដៃលេខ</span> : <span class=" value"><label style="color:#f90909" id="lbl_reciept_no"><?php echo $loanPayment['receipt_no'];?></label></span></li>
						                		</ul>
							                </td>
										</tr>
										<tr>
			                				<td colspan="3">
					                    	</td>
					                   </tr>  
								</table>
							</td>
				   		 </tr> 
				    	<tr>
				    		<td align="center" colspan="6" valign="top" height="80">	
							   <table  cellpadding="2" style=" line-height: 30px;  font-family: 'Times New Roman','Khmer OS Battambang' ;font-size:18px !important;white-space:nowrap; width:24cm; margin: 0 auto;">
									<tr class="fontsize">
											<td class="lbtitlev" valign="top" width="17%">សាខា </td>
											<td ><span class="borderCo value" ><label id="lbl_branch_id">&nbsp;<?php echo $loanPayment['branch_name'];?>&nbsp;</label></span></td>
											<?php $opo=0; if ($opo==1){?>
											<td class="lbtitlev">ប្រាក់ដើមមុនបង់ </td>
											<td >
												<span class="borderCo value" >
													<label style="color:red" id="lbl_priciple_amount">&nbsp;<?php //echo number_format($loanPayment['begining_balance'],2);?>&nbsp;</label>
												</span>
											</td>
											<td class="lbtitlev">ប្រាក់ដើមបានបង់</td>
											<td >
												<span class="borderCo value" >
													<label style="color:red" id="lbl_os_amount">&nbsp;<?php //echo number_format($loanPayment['principal_paid'],2);?>&nbsp;</label>
												</span>
											</td>
											<?php }?>
											<td class="lbtitlev">ចំនួនប្រាក់ត្រូវបង់សរុប</td>
											<td >
												<span class="borderCo value">
													<label style="color:red" id="lbl_total_payment">&nbsp;<?php echo number_format($loanPayment['total_paymentpaid'],2);?>&nbsp;</label>
												</span>
											</td>
											<td class="lbtitlev">ការប្រាក់បានបង់</td>
											<td >
												<span class="borderCo value">
													<label style="color:red" id="lbl_amount_receive">&nbsp;<?php echo number_format($loanPayment['interest_paid'],2);?>&nbsp;</label>
												</span>
											</td>
									</tr>
									<tr >
											<td class="lbtitlev">លេខរំលស់</td>
											<td >
												<span class="borderCo value">
													<strong class="fonttel" ><label  id="lbl_loan_number">&nbsp;<?php echo $loanPayment['loan_number'];?>&nbsp;</label></strong>
												</span>
											</td>
											<td class="lbtitlev">បង់លើកទី</td>
											<td >
												<span class="borderCo value" >
													<label id="lbl_paidTime">&nbsp;<?php echo $loanPayment['paid_times'];?>&nbsp;</label>
												</span>
											</td>
											
											<td class="lbtitlev">ប្រាក់ពិន័យបានបង់</td>
											<td >
												<span class="borderCo value">
													<label style="color:red" id="lbl_total_interest">&nbsp;<?php echo number_format($loanPayment['penalize_paid'],2);?>&nbsp;</label>
												</span>
											</td>
									</tr>
									<tr>
											<td class="lbtitlev">ឈ្មោះអតិថិជន</td>
											<td >
												<span class="borderCo value" >
													<label id="lbl_group_member">&nbsp;<?php echo $loanPayment['client_name'];?>&nbsp;</label>
												</span>
											</td>
											<td class="lbtitlev">ថ្ងៃបានបង់ប្រាក់</td>
											<td >
												<span class="borderCo value">
													<label style="color:red" id="lbl_collect_date">&nbsp;<?php echo date("d/M/Y",strtotime($loanPayment['date_payment']));?>&nbsp;</label>
												</span>
											</td>
											<td class="lbtitlev" style="min-width: 100px;font-weight: bold;">ប្រាក់បានបង់សរុប </td>
											<td >
												<span class="borderCo value" style="min-width: 100px;font-weight: bold;">
													<label style="color:red" id="lbl_amount_return">&nbsp;<?php echo '$ '.number_format($loanPayment['total_paymentpaid'],2);?>&nbsp;</label>
												</span>
											</td>
											
									</tr>
									<tr >
										<td class="lbtitlev">សម្គាល់</td>
											<td colspan="5" >
												<span class="borderCo value" style="min-height: 70px;">
													<label id="lbl_note">&nbsp;<?php echo $loanPayment['note'];?>&nbsp;</label>
												</span>
											</td>
											
									</tr >
									<tr class="fontsize">
										<td colspan="2"></td>
										<td colspan="4" align="center" >
											<table  width="100%" style="text-align:center; font-family: 'Times New Roman','Khmer MEF2'" >
												<tr>
													<td width="50%">បេឡាករ</td>
													<td width="50%">ហត្ថលេខា និងឈ្មោះអតិថិជន</td>
												</tr>
												<tr>
													<td colspan="2" style="height: 100px;"></td>
												</tr>
												<tr>
													<td><span class=" value" style="min-width: 100px;" id="CurrentUserLBL"><?php echo $loanPayment['user_name'];?></span></td>
													<td><span class=" value" style="min-width: 100px;" id="ClientLbl"><?php echo $loanPayment['client_name'];?></span></td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td colspan="8" class=""></td>
									</tr>
									<tr style="line-height: 20px;font-size: 14px;">
										<td valign="top">
											<span style="text-decoration:underline;font-size: 14px;"></span>
										</td>
										<td colspan="5">
											<span style="white-space: pre-line;font-size: 14px;"></span>
										</td>
									</tr>
									<tr style="line-height: 30px;font-size: 16px;">
										<td colspan="6" style="border-top:1px dotted #000;">
										</td>
									</tr>
									<tr style="line-height: 30px;font-size: 16px;">
										<td valign="top">
											<span style="">អាសយដ្ឋាន</span>
										</td>
										<td colspan="5">
											<span style="white-space: pre-line;font-size: 16px;"><?php echo $loanPayment['br_address'];?>
											</span>
										</td>
									</tr>
									<tr style="line-height: 30px;font-size: 16px;">
										<td>
											<span >លេខទំនាក់ទំនង</span>
										</td>
										<td colspan="5">
											<span style="white-space: pre-line;font-size: 16px;"><?php
												echo $loanPayment['branch_tel'];?></span>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
					<?php }?>
				</td>
			</tr>
		</table>
		</div>
	</div>
</div>