<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Report Inventory Purchase Detail"));
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="width:100%; margin:0 auto;">
	<div style=" width:15cm; height:21cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="divPrint" class="print" style="text-align:center; widht:100% ">
			<style>
				.style {
					line-height: 18px;
					font-size: 12px !important;
				}
				th {
					padding: 3px;
				}
				td.bill-ship-bg {
					background: #ccc;
					padding: 3px 10px;
				}
				td.tel_header p {
					display: inline-block;
				}
				#boder-td{
					border: 1px solid #000;
				}
				span.labelBorderBottom {
				    border-bottom: dashed 1px #00f;
				    min-width: 30px;
				    display: inline-block;
					line-height: 9px;
					text-align: center;
				}
				</style>
				<table  style="font-family: 'Times New Roman','Khmer OS Battambang'; text-align: center; margin:0 auto; width:100%; ">
					<tbody>
						<tr style="text-align:center; line-height:16px; font-size:12px; font-family:'Khmer OS Muol Light'; ">
							  <td align="center" valign="top" width="20%"><span><img src="<?php echo $this->baseUrl()?>/images/Filed other.zip.png" style="width: 80%;"></span>
							  </td>
							  <td align="center" valign="top" width="60%" ><span style="color: blue;">ព្រះរាជាណាចក្រកម្ពុជា<br>
							  ជាតិ សាសនា ព្រះមហាក្សត្រ</span><br>
							  <img src="<?php echo $this->baseUrl()?>/images/agreementsign.JPG" style="width: 100px;"><p/><span style="color: red; font-size: 14px;">ហាងម៉ូតូ យុក សុខហួង</span>
							  </td>
							  <td align="center" valign="top" width="20%" ><span><img src="<?php echo $this->baseUrl()?>/images/honda_dream_2017.png" style="width: 80%;"></span>
							  </td>
						</tr>
						<tr>
							<td colspan="3">
								<table  style=" text-align: center; width:100%;">
									<tbody>
										<tr style="text-align:center; line-height:16px; font-size:10px; font-family:'Khmer OS Muol Light';" >
											 <td align="left" valign="top" width="20%" >
												<span><img src="<?php echo $this->baseUrl()?>/images/honda_motorycles_st_blazey_mx.png" style="width: 70%; margin-top: 0px;"></span>
												<div>
													<label style="line-height: 12px; font-size:12px; color: red;">
													Tel:&nbsp;012 72 74 04<br>
													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0888 72 74 04<br>
													&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;095 75 38 44
													</label>
												</div>
											 </td>
											  <td width="60%" valign="top">
												<span><p>មានលក់ម៉ូតូ គ្រប់ប្រភេទ នឹងមួកសុវត្ថិភាព<br>ជាពិសេសមាន សេវាកម្មបង់រំលស់ ម៉ូតូគ្រប់ប្រភេទ<br>YOUK SOKHOUNG Sell all kind of motorbike and helmet</p></span>
											</td>
											  <td align="center" valign="middle" width="20%">
												<span style="color: red; font-size:16px; font-family:'Times New Roman','Khmer OS Battambang';" id="LBinvoice">&nbsp;00000</span>
											</td>
										</tr>
										<tr style="text-align:center; line-height:20px; color: red; font-size:14px; font-family:'Times New Roman','Khmer OS Battambang';">
											 <td colspan="3">
												<table  style=" text-align: left; width:100%;">
													<tr>
														<td width="35%" valign="top" style="line-height: 16px; font-size:12px; color: red;" >
															<span>អាស័យដ្ឋាន: ភូមិស្លរក្រាម <br />សង្កាត់ស្លរក្រាម ក្រុងសៀមរាប <br /> ស្ពានហ្រ្គងអូតែល, ផ្លូវមាត់ស្ទឹង (ខាងកើតសណ្ឋាគារអាម៉ាន់សារ៉ា)</span>
														</td>
														<td align="center" valign="top"><span style="color: blue; font-size: 14px; text-decoration: underline; font-family: 'Khmer OS Muol Light';">វិក័យប័ត្រ<br />INVOICE</span></td>
														<td width="35%" valign="top">
															<table width="100%" border="1" cellspacing="0" align="right" style=" border-collapse:collapse; border:solid 1px #000; font-size: 10px; color: #000; ">
																<tr align="center">
																	<td style="width: 30%; font-size: 12px;">សៀវភៅលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;</td>
																</tr>
																<tr align="center">
																	<td style="width: 30%; font-size: 12px;">បង្កាន់ដៃពន្ឋលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;</td>
																</tr>
																<tr align="center">
																	<td style="width: 30%; font-size: 12px;">ស្លាកលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;</td>
																</tr>
															</table>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="left"  style="line-height: 16px; font-size:12px; color: blue;">
							បានលក់ជូន អតិថិជនឈ្មោះ<span class="labelBorderBottom" style="min-width: 50%;"><span class="labelValue" id="LBclientName"></span></span>ភេទ​<span class="labelBorderBottom" style="min-width: 8%;"><span class="labelValue" id="LBclientGender">&nbsp;</span></span>អាយុ​<span class="labelBorderBottom" style="min-width: 8%;"><span class="labelValue" id="LBclientAge">&nbsp;</span></span>
							លេខអត្តសញ្ញាណប័ណ្ណ<span class="labelBorderBottom" style="min-width: 40%;"><span class="labelValue" id="LBclientNationID"></span></span>ភូមិ<span class="labelBorderBottom" style="min-width: 35%;"><span class="labelValue" id="LBclientVillage"></span></span>
							ឃុំ<span class="labelBorderBottom" style="min-width: 30%;"><span class="labelValue" id="LBclientComune"></span></span>ស្រុក<span class="labelBorderBottom" style="min-width: 30%;"><span class="labelValue" id="LBclientDistrict"></span></span>ខេត្ត<span class="labelBorderBottom" style="min-width: 27.5%;"><span class="labelValue" id="LBclientProvince"></span></span>
							លេខទូរស័ព្ទ<span class="labelBorderBottom" style="min-width: 87.5%;"><span class="labelValue" id="LBclientPhone"></span></span>
							</td>		
						</tr>
						<tr>
							<td colspan="3" style="text-align:left;">
								<table id="exportExcel" border="1"  style="border-collapse: collapse; border:solid 1px #000;   font-size: 10px; white-space: normal;" width="100%" cellspacing="0">
									<thead>
										<tr class="style" align="center" style=" font-family:'Times New Roman','Khmer OS Muol Light'; background-color: #1E8449; color: #ffffff; padding: 2px 0px">
											<td>&nbsp;បរិយាយ<br>DESCRIPTION&nbsp;</td>
											<td>&nbsp;ប្រភេទ<br>MODEL&nbsp;</td>
											<td>&nbsp;កម្លាំងម៉ាស៊ីន<br>POWER&nbsp;</td>
											<td>&nbsp;ពណ៏<br>COLOR&nbsp;</td>
											<td>&nbsp;លេខម៉ាស៊ីន<br>ENGNE N<sup>0</sup>&nbsp;</td>
											<td>&nbsp;លេខតូ<br>FRAME N<sup>0</sup>&nbsp;</td>
											<td style="min-width: 100px;">&nbsp;តម្លៃ<br>PRICE&nbsp;</td>
										</tr>		
									</thead>
									<tbody>	
										<tr style="line-height:16px; font-size:10px; ">
											<td align="center">&nbsp;<span id="LBDescription"></span>&nbsp;</td>
											<td align="center">&nbsp;<span id="LBModel"></span>&nbsp;</td>
											<td>&nbsp;<span id="LBPower"></span>&nbsp;</td>
											<td>&nbsp;<span id="LBColor"></span>&nbsp;</td>
											<td align="center">&nbsp;<span id="LBEngineNo"></span>&nbsp;</td>
											<td align="right" >&nbsp;<span id="LBFrameNo"></span>&nbsp;</td>
											<td align="right">&nbsp;<span id="LBPrice"></span>&nbsp;</td>
										</tr>
										 <tr style="line-height:16px; font-size:10px; " >
											<td align="center">&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
										</tr>
										<tr style="line-height:16px; font-size:10px; " >
											<td align="center">&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
										</tr>
										<tr style="line-height:16px; font-size:12px; " >
											<td valign="top" colspan="4" rowspan="3" style="border-left: 1px solid #ffffff; border-bottom:#fff solid 1px; padding: 5px 3px;">
												<p style="font-size: 10px; text-align: left; line-height: 22px;  color: red;  font-family:'Times New Roman','Khmer OS Muol Light';">
												<span style="text-decoration: underline;">ចំណាំៈ</span>
												-អតិថិជនបានពិនិត្យ ត្រឹមត្រូវរួចហើយ
												<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-ទំនិញទិញហើយមិនអាចដូរវិញបានទេ
												<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-NO REFUND
												</p>
											</td>	
											<td colspan="2" align="right" style="font-size:10px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';">សរុប/TOTAL:&nbsp;&nbsp;</td>
											<td align="right"  style="font-size:14px; line-height:28px; background-color: #D2B4DE; " >&nbsp;<span id="LBTotal"></span>&nbsp;</td>
										</tr>
										<tr style="line-height:28px; font-size:14px;">
											<td colspan="2" align="right" style=" font-size:10px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';">&nbsp;ប្រាក់កក់/DEPOSIT:&nbsp;</td>
											<td align="right" style="background-color: #D2B4DE;" >&nbsp;<span id="LBDeposit"></span>&nbsp;</td>
										</tr>	
										<tr style="line-height:28px; font-size:14px; ">
											<td colspan="2" align="right" style=" font-size:10px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';" >&nbsp;នៅខ្វះ/BALANCE DUE:&nbsp;</td>
											<td align="right" style="background-color: #D2B4DE;" >&nbsp;<span id="LBBalance"></span>&nbsp;</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="right">
								<span style="color: blue; font-size: 10px; text-align: right; font-family:'Times New Roman','Khmer OS Battambang';"><p></p></span>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="center">
								<table  style=" text-align: center; width:100%;">
									<tr style="font-size: 10px;">
										<td style="width:50%; color: blue; text-align:center; font-size: 12px; font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;"><td>&nbsp;</td>
										<td style=" width:50%; color: blue; text-align:center; font-size: 12px; font-weight:200;">ថ្ងៃ ទី<span class="labelBorderBottom" style="min-width: 25%;"><span class="labelValue" id="LBDate"></span></span>ខែ<span class="labelBorderBottom" style="min-width: 25%;"><span class="labelValue" id="LBMonth"></span></span>ឆ្នាំ <span class="labelBorderBottom" style="min-width: 15%;"><span class="labelValue" id="LBYear"></span></span></td>
								   </tr>
									<tr style="font-size: 10px;">
										<td style="width:50%; color: blue; text-align:center; font-size: 10px; font-family:'Times New Roman','Khmer OS Muol Light';font-weight:200;white-space: nowrap; ">ស្នាមមេដៃអ្នកទិញ  / <strong>CUSTOMER'S THUMB PRINT</strong><td>&nbsp;</td>
										<td style=" width:50%; color: blue; text-align:center; font-size: 10px; font-family:'Times New Roman','Khmer OS Muol Light';font-weight:200;">ហត្ថលេខាអ្នកលក់ / <strong>SELLER'S SIGNATURE</strong></td>
								   </tr>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
</div>