<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Sumary Stock Report"));
 $frm = $this->formFilter;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table width="90%">
	   <tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	   		<td> <?php echo $frm->getElement('branch_id');?></td>
	   		<td><?php echo $frm->getElement("category");?></td>
	   </tr>
	   <tr>
	   		<td> <?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement("end_date");?></td>
	   		<td><?php echo $frm->getElement('status');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
</form>
<div style="width:100%; margin:0 auto;">
	<div style=" min-width:29cm; min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.25cm;" >
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Khmer OS Battambang';
				}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Sumary Stock Report");?></li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			        </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel">
			            <table width="100%" border="1" style="font-family: 'Khmer OS Content';font-size:12px;  border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
			                <thead>
				               <tr bgcolor="#c1d0f3" class="style" align="center" style=" font-weight:bold; line-height: 25px; font-size:12px; padding:10px 0px; ">
				                    <th>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("PRODUCT_CATEGORY");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("STOCK_IN");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("STOCK_OUT");?>&nbsp;</th>
				                    <th>&nbsp;<?php echo $tr->translate("CURRENT_QTY");?>&nbsp;</th> 
				                    <th>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</th>
				                </tr>
			                </thead>
			                <?php 
			                	$location="";
			                    if(!empty($this->sumaryStok))
			                	foreach ($this->sumaryStok as $key => $rs){ 
			                    ?>
			                    <?php 
			                    if ($location != $rs['location_id']){
			                    ?>
			                     <tr class="style hover" style=" line-height:20px; ">
			                     	<th colspan="11" align="center" style="font-weight: 600; "><?php echo $rs["branch_namekh"];?></th>
			                     </tr>
			                    <?php }$location = $rs['location_id'];?>
				                <tr class="style hover" style="line-height:20px; ">
				               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["categoryName"];?></td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["item_code"];?></td>
				               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["item_name"];?></td>
				               		<td align="center">&nbsp;<?php if (!empty($rs["purchaseQty"])){echo $rs["purchaseQty"];}else{ echo 0;};?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php if (!empty($rs["stockOut"])){echo $rs["stockOut"];}else{ echo 0;};?>&nbsp;</td>
				               		<td style="font-size: 12px; text-align: center;">&nbsp;&nbsp;<?php echo $rs["qty"];?>&nbsp;</td>
				               		
				               		<td style="font-size: 12px;">&nbsp;<?php echo $rs["note"];?>&nbsp;</td>
				                </tr>
			                <?php }?>
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			 <table align="center" width="100%">
			   <tr style="font-size: 14px;">
			        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
			   </tr>
			</table>
		</div>
	</div>
</div>