<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("BRANCH_LIST"));
?>	
<?php $frm =  $this->frm_branch;?>
<form method="post">
<table   style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;">
	
	<tr>	
	 	<td><?php echo $frm->getElement('adv_search') ?></td>
	 	<td><?php echo $frm->getElement('select_branch_nameen') ?></td>
	 	<td><?php echo $frm->getElement('status_search');?></td>
	 	<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button></td>
	 </tr>
</table>
</form>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div  style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">

<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	
    	<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Khmer OS Battambang';
			}
			th{padding: 5px;}
			table { page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}	
		</style>
		<div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_NAME");?></label></h2>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr >
                				<td width="45%" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        	<table id="exportExcel"  align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <thead>
				    <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; background: #ccd9ff; line-height: 14px; font-size:12px; padding:5px 0px; ">
				        <th ><?php echo $tr->translate("NUM");?></th>
				        <th ><?php echo $tr->translate("BRANCH_NAME");?></th>
				        <th ><?php echo $tr->translate("BRANCH_NAMEEN");?></th>
				        <th ><?php echo $tr->translate("BRANCH_CODE");?></th>
				        <th ><?php echo $tr->translate("BRANCH_ADDRESS");?></th>
				        <th ><?php echo $tr->translate("BRANCH_TEL");?></th>
				        <th ><?php echo $tr->translate("FAX");?></th>
				        <th ><?php echo $tr->translate("OTHER");?></th>
				    </tr>
				    </thead>
					<?php 
					if(!empty($this->branch_list)) foreach($this->branch_list as $key =>$row){
					 	?>
					     <tr style="font-size: 10px;" align="center" >
					        <td><?php echo $key+1; ?></td>
					        <td align="left">&nbsp;<?php echo $row['branch_namekh']?>&nbsp;</td>
					        <td align="left">&nbsp;<?php echo $row['branch_nameen']?>&nbsp;</td>
					        <td><?php echo $row['branch_code']?></td>
					        <td align="left">&nbsp;<?php echo $row['br_address']?></td>
					        <td><?php echo $row['branch_tel']?></td>
					        <td><?php echo $row['fax']?></td>
					        <td><?php echo $row['other']?></td>
					    </tr>
					    <?php }?>
				</table>		
			</td>
		</tr>
	</table><br />
	<table align="center" width="100%">
		<thead>
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
		</thead>
	</table>
	</div>	
 </div>
 