<?php 
	defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$session_user=new Zend_Session_Namespace('authloan');
	$request=Zend_Controller_Front::getInstance()->getRequest();
?>						 
<title><?php echo $tr->translate("BALANCESTOCK");?></title>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/Dialog"]);
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Form");
</script>
<style>
tr.head-td {
    background: #f3f1f1;
}
</style>
<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
			var identity = $('#identity').val();
			if(identity==""){
				alert('<?php echo $tr->translate("Please insert amount product to stock");?>');
				return false;
			}
			dijit.byId('savenew').set('disabled',true);
		    dijit.byId('saveclose').set('disabled',true);
			return true;
		}else {
			return false;
		}
	</script>
	<fieldset style="background: #e0ebff">
		<table width="100%" style="margin-top:0px;" cellspacing="10">
	     	<legend class="mainblog" ><strong><?php echo $tr->translate("BALANCESTOCK")?></strong></legend>
	     	<tr>
		  		<td ><strong><?php echo $tr->translate("CLOSINGDATE")?></strong>
		  		<input  dojoType="dijit.form.DateTextBox" required="true" id="closingDate" name="closingDate" value="now" type="text"></td>
		    </tr>
			<tr>
				<td  valign="top">
					 <fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("QTY_INFO")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
								<tr>
									<td colspan="2">
										<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
											<thead>
												<tr id="head-title" class="head-td" align="right">
													<th rowspan="2"><?php echo $tr->translate("NUM");?></th>
													<th rowspan="2"><?php echo $tr->translate("PRODUCT_CATEGORY");?></th>
													<th rowspan="2"><?php echo $tr->translate("ITEM_CODE");?></th>
													<th rowspan="2"><?php echo $tr->translate("ITEM_NAME");?></th>
													<th colspan="2"><?php echo $tr->translate("CURRENT_STOCK");?></th>
													<th rowspan="2"><?php echo $tr->translate("NOTE");?></th>
												</tr>
												<tr class="head-td">
													<th><?php echo $tr->translate("QTY");?></th>
													<th><?php echo $tr->translate("Value");?></th>
												</tr>
											</thead>
											<tbody>
												<?php $i=0; $location=""; $identity=''; if (!empty($this->currentstock)) foreach ($this->currentstock as $rs){ $i++;
													 $balanceValue = $rs["qty"]*$rs["cost_price"];
													 if (empty($identity)){$identity=$i;}else{ $identity=$identity.",".$i;}
								                    if ($location != $rs['location_id']){
								                    ?>
								                     <tr class="style hover" style=" line-height:20px;background: #fff; ">
								                     	<th colspan="10" align="center" style="font-weight: 600; "><?php echo $rs["branch_namekh"];?></th>
								                     </tr>
								                    <?php }$location = $rs['location_id'];?>
												<tr style=" background: #fff;">
													<td align="center">&nbsp;<?php echo $i;?><input style="width:91%;"  dojoType="dijit.form.TextBox" id="branch_id<?php echo $i;?>" name="branch_id<?php echo $i;?>" value="<?php echo $rs["location_id"];?>" type="hidden">&nbsp;</td>
													<td>&nbsp;<?php echo $rs['categoryName'];?>&nbsp;</td>
													<td>&nbsp;<?php echo $rs['item_code'];?>&nbsp;</td>
													<td>&nbsp;<?php echo $rs['item_name'];?>&nbsp;<input style="width:91%;"  dojoType="dijit.form.TextBox"  id="productId<?php echo $i;?>" name="productId<?php echo $i;?>" value="<?php echo $rs["id"];?>" type="hidden"></td>
													<td align="center">&nbsp;<?php echo $rs["qty"];?>&nbsp;<input style="width:91%;"  dojoType="dijit.form.TextBox" id="qty<?php echo $i;?>" name="qty<?php echo $i;?>" value="<?php echo $rs["qty"];?>" type="hidden"></td>	
													<td align="center">&nbsp;<?php echo $balanceValue;?><input style="width:91%;" readonly="readonly"  dojoType="dijit.form.TextBox" required="true" id="qtyBalacne<?php echo $i;?>" name="qtyBalacne<?php echo $i;?>" value="<?php echo $rs["qty"];?>" type="hidden">
													<input style="width:91%;" class="fullside"  dojoType="dijit.form.TextBox" id="costBalacne<?php echo $i;?>" name="costBalacne<?php echo $i;?>" value="<?php echo $balanceValue;?>" type="hidden">&nbsp;</td>
													<td width="200px">&nbsp;<input style="width:91%;" dojoType="dijit.form.TextBox" id="note<?php echo $i;?>" name="note<?php echo $i;?>" value="" type="text">&nbsp;</td>
												</tr>
												<?php }?>
											</tbody>
										</table>
										<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="<?php echo $identity;?>" >
									</td>
							    </tr>
						</table>
					</fieldset>	
				</td>
			</tr>
			<tr>
				<td align="center" colspan="3">
					<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
						 iconClass="dijitIconClear"/>
					<input type="submit" label="<?php echo $tr->translate("SAVE")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  
						 iconClass="dijitIconNewTask"/>
				</td>
			</tr>	
		</table>
	</fieldset>
</form>
<script>

</script>