<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:128px !important;} 
.tds{width:114px !important;}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('brance').get('value');
				if(branch_id==0){alert("សូមជ្រើសរើសសាខា");dijit.byId('brance').focus();return false;}
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form Add Interest</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr><td colspan="8" bgcolor="#dbe7ff">តារាងអាត្រាការប្រាក់</td></tr>
						<tr>
							<td class="tds">Interest Lable</td>
							<td><?php echo $frm->getElement('inter_one')?></td>
							<td class="tds">Interest Value</td>
							<td><?php echo $frm->getElement('interest1')?><?php echo $frm->getElement('id')?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="បោះបង់" label="បោះបង់" name="cancel" id="cancel" dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" value="កែប្រែ" label="កែប្រែ" name="save" id="save" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	dijit.byId('dollar_current').set('readOnly',true);
	dijit.byId('bath_current').set('readOnly',true);
	dijit.byId('reil_current').set('readOnly',true);
});

var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capitaltransfer','action'=>'getamountbybranceid'));?>'; 
function getAmounts(){
	var brance_id = dijit.byId('brance').get('value');
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance').get('value'),
		},	
		handleAs:"json",
		load: function(respone) {
			for(i=0;i<respone.length;i++){
				if(respone[i].account_id==1){
					dijit.byId('dollar_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bath_current').attr('value',respone[i].amount_bath);
					dijit.byId('reil_current').attr('value',respone[i].amount_riel);
				}else{
					dijit.byId('dollarbank_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bathbank_current').attr('value',respone[i].amount_bath);
					dijit.byId('reilbank_current').attr('value',respone[i].amount_riel);
					}
		   }
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function statusCheck(){
	var status = dijit.byId('status').get('value');
	if(status == -1){
		alert("សូមមេត្តាជ្រើសរើសស្ថានភាពយ៉ាងហោចមួយ!!");
	}
}

</script>
