<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frmExchange;
	$this->headTitle($tr->translate('Edit Condiction Trasfer'));
	echo $this->headTitle();
?>	
<script type="text/javascript">
dojo.require('dijit.form.Form');
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require('dijit.form.Textarea');
dojo.require("dijit.Dialog");
</script>
<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				dijit.byId("save_close").set("disabled",true);
				dijit.byId("save_new").set("disabled",true);
				return true;
			}else {
				return false;
			}
	</script>
	<fieldset>
	<table cellspacing="10" class='fullside' >
		<legend class="mainblog" align="center"><strong><?php echo $tr->translate('Edit Condiction Trasfer');?></strong></legend>
		<tr>
			<td width="33%;" valign="top">
			<fieldset>
			     <legend align="center"><strong><?php echo $tr->translate('Currency Information');?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
				    <tr>
						 <td><?php echo $tr->translate("Currency")?></td>
						 <td>
							 <?php echo $frm->getElement('currency_id');?>
							 <input type="hidden" value="<?php echo $this->row['id'];?>" class="fullside" readonly="readonly" required="required" id="id" name="id" dojoType="dijit.form.TextBox" />
						 </td>
				    </tr>
					<tr>
				  		  <td><?php echo $tr->translate("NOTE")?></td>
						  <td><?php echo $frm->getElement('note');//echo $frm->getElement('for_date');?></td>
				    </tr>			    
				   <tr>
						  <td><?php echo $tr->translate("STATUS")?></td>
						  <td><?php echo $frm->getElement('status');?></td>
					</tr>
				</table>
			</fieldset>	
			</td>
			<td width="33%;" valign="top">
			<fieldset>
			     <legend align="center"><strong><?php echo $tr->translate('Condiction Information');?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
				 	<tr >
						 <td><?php echo $tr->translate("From Amount")?></td>
						 <td><?php echo $frm->getElement('fromAmount');?></td>
					</tr>
					<tr>
						  <td><?php echo $tr->translate("To Amount")?></td>
						  <td><?php echo $frm->getElement('toAmount');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("Total Fee")?></td>
						<td><?php echo $frm->getElement('totalFee');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("Commision Fee")?></td>
						<td><?php echo $frm->getElement('commisionFee');?></td>
					</tr>
				</table>
			</fieldset>
			</td>
		</tr>
		<tr>
			<td align="center" colspan="3">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
					 iconClass="dijitIconClear"/>
				<input type="submit"   label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose'​​ value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask"/>
			</td>
		</tr>	
	</table>
	</fieldset>
</form>
