<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('authloan');
	$username = $session_user->first_name;
	$them_style ='soria';
	$level =  $session_user->level;
// 	if($level!=1 AND $action=='edit'){
// 		if($module=='group' AND $action=='edit'){
// 		}
// 		else{
// 			Application_Form_FrmMessage::redirectUrl("/home");
// 		}
// 	}
	if (empty($session_user->user_id)){
		Application_Form_FrmMessage::redirectUrl("/");
	}
	
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link href="<?php echo $this->baseUrl()."/datatable/bootstrap.min.css"?>" media="screen" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link rel="stylesheet" href="<?php echo $base_url;?>css/font-awesome.min.css"/>

	<link href="<?php echo $base_url;?>cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	
	<!-- table  -->
	<?php 
	if(($module!='report' AND $level==4) OR $action=='rpt-loan-income'){
		if(($module=='default' and $controller=='index' and $action=='changepassword' ) OR $level==1){
	    }else{
			Application_Form_FrmMessage::redirectUrl("/report");	
		}
	?>
	<?php }?>
	<?php if($module!='home'){?>
	    <link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>js/dojo-1.6.1/dijit/themes/<?php echo $them_style."/".$them_style?>.css" />
        <script src="<?php echo $this->baseUrl()."/contextMenu/1.11.3/"?>jquery.min.js"></script>
       <?php //if($action=='index'){?>
	<!-- 
	<script type="text/javascript" src="<?php //echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php //echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>
	 -->
       <?php  } ?>
	<?php //}?>
	<!-- export library -->
	<?php if($module=='report'){?>
	 <script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/tableExport.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jquery.base64.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/html2canvas.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/sprintf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/jspdf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/base64.js"></script> 
      <?php } ?>	
	<!-- end -->
	
	<?php if ($action=="index" AND $module !="home"){?>
	<link href="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.css" rel="stylesheet" type="text/css" />
	<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.ui.position.min.js" type="text/javascript"></script>
	
	<link href="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl()."/datatable/"?>responsive.dataTables.min.css" rel="stylesheet" type="text/css" />
   
    <script src="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()."/datatable/"?>dataTables.responsive.min.js" type="text/javascript"></script>
   
    <script>
    $(document).ready(function() {
        $('#datatable-responsive').DataTable( {
        	responsive: true,
       	 "dom": '<"top"i>rt<"bottom"flp><"clear">',
        	searching: false,
        } );
    } );
    </script>
	<?php }?>
	
	<?php if($module!='home'){?>
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<script>dojoConfig = {parseOnLoad: true}</script>
	    <script>
			require(["dijit/form/Form","dijit/form/FilteringSelect","dijit/form/Button"]);
      </script>
	<?php }?>
	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
		*{ padding:0;margin:0;}
        html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.add-link{  
				    background-color: rgb(90, 138, 237);
			  width: 90px;
			  margin-top: 2px;
			  color: #fff;
			  text-align: center;
			  font-size: 13px;
			  font-weight: 600;}
		.fullside{ width:98%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:96%; 
		font-family: 'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif;
		/*font-family:Arial,serif !important;*/ /*font-family:'Khmer OS Battambang'*/}
		.normal,.alternate{ font-size:90% !important;}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
		.border{ border: 1px solid #ccc; height: 100%; margin: 5px; padding: 5px;}
        .border1{ border: 1px solid #ccc; height: 100%; margin: 5px; margin-left:0px; padding: 5px;}
		span.icon_menu {
		    padding: 0 5px;
		    font-size: 28px;
		}
		.mainblog{background: #b0ccff;
		    border-radius: 2px;
		    padding: 5px;
		    border: 1px solid #2761ca;
		 }
		table#datatable-responsive tr td a {
		    color: #008;
		}
		#menu a {
		    -webkit-box-sizing: content-box;
		    -moz-box-sizing: content-box;
		    box-sizing: content-box;
		}
		ul li {
		    list-style-type: none;
		}
	</style>	
</head>
    <body class="<?php echo $them_style;?>" >
       <!--  <div data-dojo-type="dijit/layout/BorderContainer" style="width: 100%; height: 100%;"> -->
             <!-- <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'top'"> -->
            <table width="100%">
                <tr>
                	<td colspan="2" valign="top" style="position: fixed;width: 100%; z-index: 1;top: 0;background:rgb(243, 241, 241) none repeat scroll 0% 0%" >
                		 <?php echo $this->render('header.phtml')?>
			                <p style="font-size:13px !important; ">
						              <span style="padding-left: 3px;padding-right: 3px;float: left; font-weight:600;"><?php echo $tr->translate("USING_BY");?><a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><?php echo $username;?></a></span>  
							<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"> | <?php echo $tr->translate("SIGN_OUT");?></a>
			                 <?php if($action=='index' AND $module!='report' AND $module!='home'){?>
			                 <a class='add-link' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?></a>
							<?php }elseif($action=='add' OR $action=='edit' OR $action=='quickchange' OR $action=='withdrawal' OR $module=='report' ){?>
							 <span style="padding-left: 3px;padding-right: 3px; float: right; font-weight:600;"><a class='add-link' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><?php echo $tr->translate('GO_BACK');?></a></span>
							<?php }?>
							</p>
                	</td>
                </tr>
                <tr>
                	<td colspan="2" height="90px;"></td>
                </tr>
            	<tr>
            		<td colspan="2" valign="top" width="99%" >
            			<div class="col-sm-12" style=" padding: 0;">
            				<?php if($module!='home') {?>
	           			<div class="col-sm-2" style=" padding: 0;">
	           				
            					<?php echo $this->render('menuleft.phtml')?>
            				
	           			</div>
	           			<?php }?>
	           			<div  class="<?php if($module!='home') { echo 'col-sm-10'; }else{?><?php echo 'col-sm-12'; }?>">
	           				<?php if($module=='report' AND $action!='index'){?>
							<!-- 
							<div class="menureport">
								<ul>
									<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
									<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
									<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
								</ul>
							</div>
							 -->
							 <div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
								<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
									<i class="fa fa-print"></i>
								</div>
								<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
								<div class="ptss__settings">
									<div class="ptss__single-setting" id="ptss__layout">
										<div class="ptss__setting-control">
											<div class="ptss__layout-wrapper">
												<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
												<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
												<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
											</div>
											
										</div>
									</div>
									
								</div>
							</div>
							<div style="clear:both;"></div>
							<?php }?>
							<?php 
							$db = new Application_Model_DbTable_DbUsers();
	            			$rs = $db->getAccessUrl($module,$controller,$action);
	            			echo $this->layout()->content;
// 	            			if(!empty($rs) OR $action=='changepassword'){
// 	            				echo $this->layout()->content;
// 	            			}else{
// 	            				echo $this->layout()->content;
// 	            				echo $this->render('pagenotfund.phtml');
// 	            			}
            			 ?>
            			 <?php 
			               	if($module=='report' AND $action!='rpt-paymentschedules'){
			              ?>
		                <?php }?>
	           			</div>
            			</div>
           			</td>
            	</tr>
            </table>
    </body>
<style>
    
    </style>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php if($module=='report' OR $module=='reports' AND $action!='index'){?>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}

jQuery(function () {
	'use strict';
	
	jQuery(".ptss__toggle-btn").click(function () {	
		jQuery('.js-ptss-frame').toggleClass('is-opened');
	});
	
	jQuery('.ptss__layout-wrapper > div').click(function(){
		
		jQuery(this).closest('.ptss__setting-control').find('.ptss__layout-wrapper').removeClass('is-selected');
		
		jQuery(this).parent().addClass('is-selected');
		
		if( jQuery(this).hasClass('ptss__layout-box--wide') ) {
			
			jQuery('body').removeClass('boxed');
			jQuery('#ptss__boxed-bg').hide();
			
			jQuery('body').removeClass('bg1').removeClass('bg2').removeClass('bg3').removeClass('bg4');
			
			jQuery('#ptss__boxed-backgrounds span').removeClass('is-selected');
			
		} else {
			
			jQuery('body').addClass('boxed');
			jQuery('#ptss__boxed-bg').show();
			
		}
		
	});
})
</script>
<?php } ?>
</html>