	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace('authloan');
	$arr_module = $session_user->arr_acl;
	
	$menu = array();
// 	print_r($arr_module);
$module = '';
$controller=array();
$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			$lblcontroller = $rs['label'];
// 			$lblcontroller = $rs['controller'];
			if($rs['controller']=='index' AND $rs['module']=='group' ){
				$lblcontroller='CLIENT_INFO';
			}
			if($rs['controller']=='index' AND $rs['module']=='loan' ){
				$lblcontroller='IL_DISBURSE';
			}
			
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>'<li><a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a></li>');
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>'<li><a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a></li>'));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;   
?>
<div id="header-left">
<ul>
<?php 
	if($request->getModuleName()!='default' AND $action!='changepassword' ){
		$dc=new Application_Model_Decorator();					
		$class="current-left";					
		$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
		if($menu) echo $menu;	
	}				
?>
	</ul>																
	</div>
	<style>
	.current-left{  background: none repeat scroll 0 0 #EDF7F8 !important;}
	</style>