<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH')); 
?>
<?php  $frm = $this->frm_branch;?>
<script>
       dojo.require("dijit.form.Textarea");
</script>
<form id="frm_branch" action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
               dijit.byId("save_new").set("disabled",true);
			   dijit.byId("save_close").set("disabled",true);
				return true;
			} else {
				return false;
			}
	</script>
	<fieldset>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<legend ><strong><?php echo $tr->translate("ADD_BRANCH");?></strong></legend>
		<tr>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("BRANCH_NAME")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("BRANCH_CODE")?></td>
							<td><?php echo $frm->getElement("branch_code");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement("branch_namekh");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SHOPNAME")?></td>
							<td><?php echo $frm->getElement("branch_nameen");?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("BRANCH_ADDRESS")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("PREFIX_CODE");?></td>
							<td><?php echo $frm->getElement("prefix_code");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php echo $frm->getElement("branch_tel");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("BRANCH_ADDRESS")?></td>
							<td><?php echo $frm->getElement("br_address");?></td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("NOTE")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							 <td><?php echo $tr->translate("DESCRIPTION")?></td>
							 <td><?php echo $frm->getElement("description");?></td>								
						</tr>
						<tr>
							<td><?php echo $tr->translate("BRANCH_NOTE")?></td>
							<td><?php echo $frm->getElement("branch_note");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("BRANCH_STATUS")?></td>
							<td><?php echo $frm->getElement("branch_status");?></td>
						</tr>
						 
				</table>
			</fieldset>	
		</td>
	</tr>
	 
	<tr>
		<td colspan="3" align="center">
			<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
			<input type="button" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />
			<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />
		</td>
	</tr>					
	</table>	
</fieldset>
</form>
<script>
function submitDataClose(){
	if(dijit.byId('frm_branch').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_branch"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/other/branch";
			},
			error: function(e) {
			}
		});
	}
}

</script>