<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_BRANCH​​_INFO')); 
?>
<?php  $frm = $this->frm_branch;?>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<fieldset>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<legend ><strong><?php echo $tr->translate("UPDATE_BRANCH​​_INFO");?></strong></legend>
				<tr>
				<td width="33%;" valign="top">
					 <fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("BRANCH_NAME")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
								<tr>
									<td><?php echo $tr->translate("BRANCH_CODE")?></td>
									<td><?php echo $frm->getElement("branch_code");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_NAMEKH")?></td>
									<td><?php echo $frm->getElement("branch_namekh");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_NAMEEN")?></td>
									<td><?php echo $frm->getElement("branch_nameen");?></td>
								</tr>
						</table>
					</fieldset>	
				</td>
				<td width="33%;" valign="top">
					 <fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("BRANCH_ADDRESS")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
								<tr>
									<td><?php echo $tr->translate("PREFIX_CODE");?></td>
									<td><?php echo $frm->getElement("prefix_code");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE")?></td>
									<td><?php echo $frm->getElement("branch_tel");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_ADDRESS")?></td>
									<td><?php echo $frm->getElement("br_address");?></td>
								</tr>
						</table>
					</fieldset>	
				</td>
				<td width="33%;" valign="top">
					<fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("NOTE")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
								<tr>
									 <td><?php echo $tr->translate("BRNACH_FAX")?></td>
									 <td><?php echo $frm->getElement("fax");?></td>								
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_NOTE")?></td>
									<td><?php echo $frm->getElement("branch_note");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_STATUS")?></td>
									<td><?php echo $frm->getElement("branch_status");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_DISPLAY")?></td>
									<td><?php echo $frm->getElement("branch_display");?></td>
								</tr>
						</table>
					</fieldset>	
				</td>
			</tr>
	 
			<tr>
				<td colspan="6" align="center">
				  <input type="reset" label="<?php echo $tr->translate('clear');?>" id="" dojoType="dijit.form.Button"
	                              iconClass="dijitIconClear" />
							  <input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
			          iconClass="dijitEditorIcon dijitEditorIconSave"/>
				</td>
			</tr>					
	</table>	
	</fieldset>
</form>