<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_BRANCH​​_INFO')); 
	$photo=$this->baseUrl().'/images/no-image.png';
	if (!empty($this->row['images_branch'])){
		$photo=$this->baseUrl().'/images/'.$this->row['images_branch'];
	}
?>
<?php  $frm = $this->frm_branch;?>
<script>
       dojo.require("dijit.form.Textarea");
</script>
<style>
.image-box {
    text-align: center;
}
.image-box img {
        width: 100%;
    /* border-radius: 60%; */
    height: auto;
    /* margin-top: 10px; */
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 30px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 35px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 50%;
    text-align: center;
    margin: 0 auto;
}
</style>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<fieldset>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<legend ><strong><?php echo $tr->translate("UPDATE_BRANCH​​_INFO");?></strong></legend>
				<tr>
				<td width="66%;" valign="top">
					 <fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("BRANCH_NAME")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
								<tr>
									<td><?php echo $tr->translate("BRANCH_CODE")?></td>
									<td><?php echo $frm->getElement("branch_code");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_NAME")?></td>
									<td><?php echo $frm->getElement("branch_namekh");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SHOPNAME")?></td>
									<td><?php echo $frm->getElement("branch_nameen");?></td>
								</tr>
								<tr>
									 <td><?php echo $tr->translate("DESCRIPTION")?></td>
									 <td><?php echo $frm->getElement("description");?></td>								
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_NOTE")?></td>
									<td><?php echo $frm->getElement("branch_note");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_STATUS")?></td>
									<td><?php echo $frm->getElement("branch_status");?></td>
								</tr>
						</table>
					</fieldset>	
					<div style="text-align: center;">
						<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" id="" dojoType="dijit.form.Button"
                              iconClass="dijitIconClear" />
						  <input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton" dojoType="dijit.form.Button" 
		         		 iconClass="dijitEditorIcon dijitEditorIconSave"/>
					</div>
				</td>
				<td width="33%;" valign="top">
					 <fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("BRANCH_ADDRESS")?></strong></legend>
						 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
								<tr>
									<td><?php echo $tr->translate("PREFIX_CODE");?></td>
									<td><?php echo $frm->getElement("prefix_code");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE")?></td>
									<td><?php echo $frm->getElement("branch_tel");?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BRANCH_ADDRESS")?></td>
									<td><?php echo $frm->getElement("br_address");?></td>
								</tr>
						</table>
					</fieldset>	
					<fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("BRANCH_IMAGE")?></strong></legend>
							 <div class="account-image">
								<div class="image-box">
									<img id="profile_wiew" src="<?php echo $photo;?>" alt=""  />
								</div>
								<div class="button_browse">
								<div id='preview'></div>	
										<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
										<input class="btn_borwse_image" type="file" id="photo" name="photo" />
								</div>
							</div>
					</fieldset>	
				</td>
				
			</tr>
	</table>	
	</fieldset>
</form>
<script>
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#photo").change(function(){
    readURL(this);
});
</script>