<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Add Installment"));
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/TextBox","dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
		dojo.require("dojo.data.ItemFileWriteStore"); 
   </script>
<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
		   client = dijit.byId('member').get('value');
           branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}
  				selling_type = dijit.byId('selling_type').get('value');
				interest_rate = dijit.byId('interest_rate').get('value');
				duration = dijit.byId('duration').get('value');

				if(selling_type==2 && interest_rate<=0 && duration<=0){
					alert("រំលស់ អាត្រាការប្រាក់និង រយៈពេលត្រូវតែធំជាងសូន្យ");
					dijit.byId('duration').focus();
					return false;
				}
				dijit.byId('savenew').set('disabled',true);
			    dijit.byId('saveclose').set('disabled',true);
				return true;
			}else {
				return false;
			}
	</script>
<fieldset style="background: #e0ebff">
<table width="100%" style="margin-top:0px;" cellspacing="10">
     <legend class="mainblog" ><strong><?php echo $tr->translate("INSTALLMENT")?></strong></legend>
	<tr>
		<td width="25%;" valign="top">
			 <fieldset >
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
					        <td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
					    </tr>
					    <tr>
					 		<td style="white-space: nowrap;"><?php echo $tr->translate('INSTALLMENT_NO');?></td>
					 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="sale_no" id="sale_no" value="" type="text"></td>
					 	</tr>
					    <tr >
							<td><?php echo $tr->translate("CLIENT_NUM")?></td>
							<td><input id="customer_code" /></td>
						</tr>
						<tr>
							<td><strong><?php echo $tr->translate("CUSTOMER_NAME")?></strong></td>
							<td><input id="member" />
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td>
								<input dojoType="dijit.form.TextBox" class="fullside" name="note" id="note" >
							</td>
						</tr>
						<tr>
							<td></td>
							<td><input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/></td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="25%;" valign="top">
			<fieldset>
			<legend align="center" ><strong><?php echo $tr->translate("ITEMS_INFO")?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;white-space: nowrap;" cellspacing="5" >
			 	<tr>
			 		<td><strong><?php echo $tr->translate('CATEGORY');?></strong></td>
			 		<td><input id="category_id" /></td>
			 	</tr>
			 	<tr>
			 		<td><strong><?php echo $tr->translate('ITEM_NAME');?></strong></td>
			 		<td><input id="product_name" /></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('Power Engine');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="power" id="power" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('Color');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="color" id="color" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('Engine No');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="engine" id="engine" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('Frame No');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="frame" id="frame" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><strong><?php echo $tr->translate('Plates No');?></strong></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="frame_no" id="frame_no" value="" type="text"></td>
			 	</tr>
			 </table>			 
			</fieldset>
		</td>
		<td width="25%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("PAYMENT_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
					 		<td><strong><?php echo $tr->translate('SOLD_DATE');?></strong></td>
					 		<td><input onchange="setFirstPaymentAndDateLine();" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="date_sold" id="date_sold" ></td>
					 	</tr>
						<tr>
					 		<td><strong><?php echo $tr->translate('SELLING_PRICE');?></strong></td>
					 		<td><input onkeyup="calCulateBalane();" required="1" dojoType="dijit.form.NumberTextBox" class="fullside"  name="selling_price" id="selling_price" value="" type="text"></td>
					 	</tr>
						<tr>
					 		<td><?php echo $tr->translate('SALE_TYPE');?></td>
					 		<td>
					 			<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
					 				<option value="1"><?php echo $tr->translate('ទិញដាច់');?></option>
					 				<option value="2"><?php echo $tr->translate('បង់រំលស់');?></option>
					 			</select>
					 		</td>
					 	</tr>
					 	<tr>
					 		<td><strong><?php echo $tr->translate('PAID');?></strong></td>
					 		<td><input dojoType="dijit.form.NumberTextBox" required="1" class="fullside"  name="paid" id="paid" value="" type="text" onkeyup="calCulateBalane();" ></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('BALANCE');?></td>
					 		<td><input dojoType="dijit.form.NumberTextBox" class="fullside" readonly="readonly" name="balance" id="balance" value="" type="text"></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('INVOICE_NO');?></td>
					 		<td><input readonly dojoType="dijit.form.ValidationTextBox" class="fullside" required="1" name="invoice_no" id="invoice_no" ></td>
					 	</tr>
						<tr>
					 		<td><strong><?php echo $tr->translate('DAY_PAYMENT');?></strong></td>
					 		<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="paid_date" id="paid_date" ></td>
					 	</tr>
				</table>
			</fieldset>	
		</td>
		<td width="25%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("INFO_FUND")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;white-space: nowrap;" cellspacing="5"  >
					 	 <tr>
					 		<td><?php echo $tr->translate('INTEREST_RATE');?></td>
					 		<td><input onkeyup="setDefaultPaymentAmount();" dojoType="dijit.form.NumberTextBox" class="fullside"  name="interest_rate" id="interest_rate" required="1" value="0"></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('INSTALLMENT_DURATION')." (".$tr->translate('MONTH').")";?></td>
					 		<td><input onkeyup="setDefaultPaymentAmount();calCulateFirstPayment();" dojoType="dijit.form.NumberTextBox" class="fullside"  name="duration" id="duration" required="1" value="0" ></td>
					 	</tr>
					 	<tr>
					    	<td><strong><?php echo $tr->translate("REPAYMENT_TYPE")?></strong></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
					     </tr>
					     <tr>
					    	<td><?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?></td>
							<td><input readonly dojoType="dijit.form.NumberTextBox" class="fullside" name="fixed_payment" id="fixed_payment" ></td>
					     </tr>
					 	<tr>
					 		<td><?php echo $tr->translate('FIRST_PAYMENT');?></td>
					 		<td><input onchange="calCulateEndDate();" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="first_payment" id="first_payment" ></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('END_DATE');?></td>
					 		<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="date_line" id="date_line" ></td>
					 	</tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td align="center" colspan="4">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  
				 iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW_SCHEDULE")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		 <input type="button" onclick="showInvoice();" label="<?php echo $tr->translate("PREVIEW_INVOICE")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
</fieldset>
 <div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'វិក្ក័យបត្រ', onCancel:hideDialog" id="frmInvoice">
		<div style=" width:21cm; height:27cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="invoicePrint" class="print" style="text-align:center; widht:100% ">
			<style>
				.style {
					line-height: 18px;
					font-size: 12px !important;
				}
				th {
					padding: 3px;
				}
				td.bill-ship-bg {
					background: #ccc;
					padding: 3px 10px;
				}
				td.tel_header p {
					display: inline-block;
				}
				#boder-td{
					border: 1px solid #000;
				}
				span.labelBorderBottom {
				    border-bottom: dashed 1px #00f;
				    min-width: 30px;
				    display: inline-block;
					line-height: 9px;
					text-align: center;
				}
				pre {
				    background: none;
				    border: none;
				    font-size: inherit;
				    font-family: inherit;
				    line-height: inherit;
				}
				</style>
				<table  style="font-family: 'Times New Roman','Khmer OS Battambang'; text-align: center; margin:0 auto; width:100%; ">
					<tbody>
						<tr style="text-align:center;line-height:25px;font-size:16px; font-family:'Khmer OS Muol Light'; ">
							  <td align="center" valign="top" width="20%"><span><img src="<?php echo $this->baseUrl()?>/images/Filed other.zip.png" style="width: 80%;"></span></td>
							  <td align="center" valign="top" width="60%" ><span style="color: blue;">ព្រះរាជាណាចក្រកម្ពុជា<br>
							  	ជាតិ សាសនា ព្រះមហាក្សត្រ</span><br>
							  	<img src="<?php echo $this->baseUrl()?>/images/agreementsign.JPG" style="width: 100px;"><p/><span id="brNameShop" style="color: red; font-size: 16px;">ហាងម៉ូតូ យុក សុខហួង</span>
							  </td>
							  <td align="center" valign="top" width="20%" ><span><img src="<?php echo $this->baseUrl()?>/images/honda_dream_2017.png" style="width: 80%;"></span></td>
						</tr>
						<tr>
							<td colspan="3">
								<table  style=" text-align: center; width:100%;">
									<tbody>
										<tr style="text-align:center; line-height:16px; font-size:12px; font-family:'Khmer OS Muol Light';" >
											 <td align="left" valign="top" width="20%" >
												<span><img src="<?php echo $this->baseUrl()?>/images/honda_motorycles_st_blazey_mx.png" style="width: 70%; margin-top: 0px;"></span>
												<div>
													<label id="brPhone" style="line-height: 12px; font-size:12px; color: red;">
													<!-- <span style="white-space:nowrap;">Tel:&nbsp;012 72 74 04</span><br>
													<span style="white-space:nowrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0888 72 74 04</span><br>
													<span style="white-space:nowrap;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;095 75 38 44</span> -->
													</label>
												</div>
											 </td>
											  <td width="60%" valign="top">
												<span><pre id="brDescription" style="line-height: 20px;">មានលក់ម៉ូតូ គ្រប់ប្រភេទ និង មួកសុវត្ថិភាព<br>ជាពិសេសមាន សេវាកម្មបង់រំលស់ ម៉ូតូគ្រប់ប្រភេទ<br>YOUK SOKHOUNG Sell all kind of motorbike and helmet</pre></span>
											</td>
											  <td align="center" valign="middle" width="20%">
												<span style="color: red; font-size:12px; font-family:'Times New Roman','Khmer OS Battambang';" id="LBinvoice">&nbsp;00000</span>
											</td>
										</tr>
										<tr style="text-align:center; line-height:20px; color: red; font-size:12px; font-family:'Times New Roman','Khmer OS Battambang';">
											 <td colspan="3">
												<table  style=" text-align: left; width:100%;">
													<tr>
														<td width="35%" valign="top" style="line-height: 16px; font-size:10px !important; color: red;" >
															<span>អាសយដ្ឋាន: </span><span id="brAddress"></span>
															<!-- <span>អាសយដ្ឋាន: ភូមិស្លរក្រាម <br />សង្កាត់ស្លរក្រាម ក្រុងសៀមរាប <br /> ស្ពានហ្រ្គងអូតែល, ផ្លូវមាត់ស្ទឹង (ខាងកើតសណ្ឋាគារអាម៉ាន់សារ៉ា)</span> -->
														</td>
														<td align="center" valign="top"><span style="color: blue; font-size: 14px; text-decoration: underline; font-family: 'Khmer OS Muol Light';">វិក័យប័ត្រ<br />INVOICE</span></td>
														<td width="35%" valign="top">
															<table width="100%" border="1" cellspacing="0" align="right" style=" border-collapse:collapse; border:solid 1px #000; font-size: 12px; color: #000; ">
																<tr align="left">
																	<td style="width: 30%; font-size: 12px;">សៀវភៅលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;</td>
																</tr>
																<tr align="left">
																	<td style="width: 30%; font-size: 12px;">បង្កាន់ដៃពន្ឋលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;</td>
																</tr>
																<tr align="left">
																	<td style="width: 30%; font-size: 12px;">ស្លាកលេខ</td>
																	<td style="background-color: #D2B4DE  ; width: 70%;">&nbsp;<span id="lblframe_no"></span></td>
																</tr>
															</table>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="left"  style="line-height: 25px; font-size:14px; color: blue;">
							បានលក់ជូន អតិថិជនឈ្មោះ<span class="labelBorderBottom" style="min-width: 50%;"><span class="labelValue" id="LBclientName"></span></span>ភេទ​<span class="labelBorderBottom" style="min-width: 8%;"><span class="labelValue" id="LBclientGender">&nbsp;</span></span>អាយុ​<span class="labelBorderBottom" style="min-width: 8%;"><span class="labelValue" id="LBclientAge">&nbsp;</span></span>
							លេខអត្តសញ្ញាណប័ណ្ណ<span class="labelBorderBottom" style="min-width: 40%;"><span class="labelValue" id="LBclientNationID"></span></span>ភូមិ<span class="labelBorderBottom" style="min-width: 35%;"><span class="labelValue" id="LBclientVillage"></span></span>
							ឃុំ<span class="labelBorderBottom" style="min-width: 30%;"><span class="labelValue" id="LBclientComune"></span></span>ស្រុក<span class="labelBorderBottom" style="min-width: 30%;"><span class="labelValue" id="LBclientDistrict"></span></span>ខេត្ត<span class="labelBorderBottom" style="min-width: 27.5%;"><span class="labelValue" id="LBclientProvince"></span></span>
							លេខទូរស័ព្ទ<span class="labelBorderBottom" style="min-width: 87.5%;"><span class="labelValue" id="LBclientPhone"></span></span>
							</td>		
						</tr>
						<tr>
							<td colspan="3" style="text-align:left;">
								<table id="exportExcel" border="1"  style="border-collapse: collapse; border:solid 1px #000;font-size: 12px; white-space: normal;" width="100%" cellspacing="0">
									<thead>
										<tr class="style" align="center" style=" font-family:'Times New Roman','Khmer OS Muol Light'; background-color: #1E8449; color: #ffffff; padding: 2px 0px">
											<td style="font-size:14px !important;">&nbsp;បរិយាយ<br>DESCRIPTION&nbsp;</td>
											<td>&nbsp;ប្រភេទ<br>MODEL&nbsp;</td>
											<td>&nbsp;<span style="white-space: nowrap;">កម្លាំងម៉ាស៊ីន</span><br>POWER&nbsp;</td>
											<td>&nbsp;ពណ៌<br>COLOR&nbsp;</td>
											<td>&nbsp;<span style="white-space: nowrap;">លេខម៉ាស៊ីន</span><br>ENGNE N<sup>0</sup>&nbsp;</td>
											<td>&nbsp;លេខតួ<br><span style="white-space: nowrap;">FRAME N<sup>0</sup></span>&nbsp;</td>
											<td style="min-width: 100px;">&nbsp;តម្លៃ<br>PRICE&nbsp;</td>
										</tr>		
									</thead>
									<tbody>	
										<tr style="line-height:25px; font-size:12px;">
											<td align="center">&nbsp;<span id="LBDescription"></span>&nbsp;</td>
											<td align="center">&nbsp;<span id="LBModel"></span>&nbsp;</td>
											<td>&nbsp;<span id="LBPower"></span>&nbsp;</td>
											<td>&nbsp;<span id="LBColor"></span>&nbsp;</td>
											<td align="center">&nbsp;<span id="LBEngineNo"></span>&nbsp;</td>
											<td align="right" >&nbsp;<span id="LBFrameNo"></span>&nbsp;</td>
											<td align="right">&nbsp;<span id="LBPrice"></span>&nbsp;</td>
										</tr>
										 <tr style="line-height:25px; font-size:12px; " >
											<td align="center">&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
										</tr>
										<tr style="line-height:25px; font-size:12px;" >
											<td align="center">&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td>&nbsp;&nbsp;</td>
											<td align="center">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
											<td align="right">&nbsp;&nbsp;</td>
										</tr>
										<tr style="line-height:25px; font-size:12px; " >
											<td valign="top" colspan="4" rowspan="3" style="border-left: 1px solid #ffffff; border-bottom:#fff solid 1px; padding: 5px 3px;">
												<p style="font-size: 12px; text-align: left; line-height: 22px;  color: red;  font-family:'Times New Roman','Khmer OS Muol Light';">
												<span style="text-decoration: underline;">ចំណាំៈ</span>
												-អតិថិជនបានពិនិត្យ ត្រឹមត្រូវរួចហើយ
												<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-ទំនិញទិញហើយមិនអាចដូរវិញបានទេ
												<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-NO REFUND
												</p>
											</td>	
											<td colspan="2" align="right" style="font-size:12px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';">សរុប/TOTAL:$&nbsp;&nbsp;</td>
											<td align="right"  style="font-size:12px; line-height:30px; background-color: #D2B4DE;font-weight: bold;" >&nbsp;<span id="LBTotal"></span>&nbsp;</td>
										</tr>
										<tr style="line-height:30px; font-size:12px;">
											<td colspan="2" align="right" style=" font-size:12px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';">&nbsp;ប្រាក់កក់/DEPOSIT:&nbsp;</td>
											<td align="right" style="background-color: #D2B4DE;font-size: 12px;font-weight: bold;" >&nbsp;<span id="LBDeposit"></span>&nbsp;</td>
										</tr>	
										<tr style="line-height:28px; font-size:12px; ">
											<td colspan="2" align="right" style=" font-size:12px; border-bottom:#fff solid 1px; border-left:#fff solid 1px; color: blue; font-family:'Times New Roman','Khmer OS Muol Light';" >&nbsp;នៅខ្វះ/BALANCE DUE:$&nbsp;</td>
											<td align="right" style="background-color: #D2B4DE;font-size: 12px;font-weight: bold;" >&nbsp;<span id="LBBalance"></span>&nbsp;</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="right">
								<span style="color: blue; font-size: 12px; text-align: right; font-family:'Times New Roman','Khmer OS Battambang';"><p></p></span>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="center">
								<table  style=" text-align: center; width:100%;">
									<tr style="font-size: 12px;">
										<td style="width:50%; color: blue; text-align:center; font-size: 12px; font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;"><td>&nbsp;</td>
										<td style=" width:50%; color: blue; text-align:center; font-size: 12px; font-weight:200;">ថ្ងៃ ទី<span class="labelBorderBottom" style="min-width: 25%;"><span class="labelValue" id="LBDate"></span></span>ខែ<span class="labelBorderBottom" style="min-width: 25%;"><span class="labelValue" id="LBMonth"></span></span>ឆ្នាំ <span class="labelBorderBottom" style="min-width: 15%;"><span class="labelValue" id="LBYear"></span></span>
											<br /><br /><br /><br />
										</td>
								   </tr>
									<tr style="font-size: 12px;">
										<td style="width:50%; color: blue; text-align:center; font-size: 12px; font-family:'Times New Roman','Khmer OS Muol Light';font-weight:200;white-space: nowrap; ">ស្នាមមេដៃអ្នកទិញ  / <strong>CUSTOMER'S THUMB PRINT</strong><td>&nbsp;</td>
										<td style=" width:50%; color: blue; text-align:center; font-size: 12px; font-family:'Times New Roman','Khmer OS Muol Light';font-weight:200;">ហត្ថលេខាអ្នកលក់ / <strong>SELLER'S SIGNATURE</strong></td>
								   </tr>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div style="text-align: center;"><input type="button" onclick="doPrintInvoice();" label="<?php echo $tr->translate("SAVE_PRINT");?>" id='saveprintInvoice' name='saveprint' value='saveprint' dojoType="dijit.form.Button"
				iconClass="dijitIconNewTask"/></div>
		</div>
	</div>
 </div>
<div class="dijitHidden">
<style>
.print tr td{
	padding:2px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់', onCancel:hideDialog" id="frm_client" style="width:1000px">
	<div id="rpt_print" class="print" style="text-align:center;">
		<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='save_close' id='save_close' value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconDelete"/>
		<input type="button" onclick="showInvoice();" label="<?php echo $tr->translate("PREVIEW_INVOICE");?>" id='saveprint' name='saveprint' value='saveprint' dojoType="dijit.form.Button"
		iconClass="dijitIconNewTask"/>
		<div id="t_amountmoneytype" name="t_amountmoneytype"></div>
	</div>
</div>
</div>
</form>
<script type="text/javascript">	
var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );
function calCulateBalane(){
	selling_type = dijit.byId("selling_type").get("value");
	selling_price = dijit.byId("selling_price").get("value");
	paid = dijit.byId("paid").get("value");
	
	if(selling_type==1){
		dijit.byId("paid").attr("value",selling_price);
		dijit.byId("balance").attr("value",0);
	}else{
		if(selling_price-paid<0){
			alert("The Totoal paid can not bigger then selling price");
			dijit.byId("paid").attr("value",selling_price);
			dijit.byId("balance").attr("value",0);
		}else{
			dijit.byId("balance").attr("value",selling_price-paid);
		}
	}
	setDefaultPaymentAmount();
}
function showInvoice(){
	if(dijit.byId('frm_add_tran').validate()) {
		selling_type = dijit.byId('selling_type').get('value');
		interest_rate = dijit.byId('interest_rate').get('value');
		duration = dijit.byId('duration').get('value');

		if(selling_type==2 && interest_rate<=0 && duration<=0){
			alert("រំលស់ អាត្រាការប្រាក់និង រយៈពេលត្រូវតែធំជាងសូន្យ");
			dijit.byId('duration').focus();
			return false;
		}
		dojo.byId('LBinvoice').innerHTML=dijit.byId('sale_no').get('value');
		dojo.byId('LBDescription').innerHTML=dijit.byId('product_name').attr('displayedValue');
		dojo.byId('LBModel').innerHTML=dijit.byId('category_id').attr('displayedValue');
		dojo.byId('LBPower').innerHTML=dijit.byId('power').get('value');
		dojo.byId('LBColor').innerHTML=dijit.byId('color').get('value');
		dojo.byId('LBEngineNo').innerHTML=dijit.byId('engine').get('value');
		dojo.byId('LBFrameNo').innerHTML=dijit.byId('frame').get('value');
		dojo.byId('lblframe_no').innerHTML=dijit.byId('frame_no').get('value');
		//dojo.number.format(data.total_paymentpaid,{places:2});
		
		dojo.byId('LBPrice').innerHTML=dojo.number.format(dijit.byId('selling_price').get('value'),{places:2});
		dojo.byId('LBTotal').innerHTML=dojo.number.format(dijit.byId('selling_price').get('value'),{places:2});
		dojo.byId('LBDeposit').innerHTML=dojo.number.format(dijit.byId('paid').get('value'),{places:2});
		dojo.byId('LBBalance').innerHTML=dojo.number.format(dijit.byId('balance').get('value'),{places:2});
		release_date = dijit.byId('paid_date').get('value');
		var a = new Date(release_date);
	
		var mm = a.getMonth() + 1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		dojo.byId('LBDate').innerHTML=dd;
		dojo.byId('LBMonth').innerHTML=mm;
		dojo.byId('LBYear').innerHTML=y;
		dijit.byId("frmInvoice").show();
	}
}
	function hideInvoice(){
		dijit.byId("frmInvoice").hide();
	}
	function doPrintInvoice() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('invoicePrint').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
		dijit.byId('frm_add_tran').submit();
		hideInvoice();
	}
    function setDefaultPaymentAmount(){
    	dijit.byId('fixed_payment').attr('value',0);
    	dijit.byId("fixed_payment").set('readOnly',true);
        payment_method = dijit.byId('repayment_method').get('value');
        if(payment_method==4){
	    	amount_principal = dijit.byId('balance').get('value');    	
	    	term = dijit.byId('duration').get('value');
	    
			interest_rate=dijit.byId('interest_rate').get('value')/100;
			top_pow = Math.pow((1+interest_rate),term);
			bellow = Math.pow((1+interest_rate),(term))-1;
			amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
			amount_payment = parseInt(amount_payment);
			dijit.byId('fixed_payment').attr('value',amount_payment);
			dijit.byId("fixed_payment").set('readOnly',false);
        }
	}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    dijit.byId('frm_add_tran').submit();
	    hideDialog();
	}
var url_getreceipt = '<?php echo $this->url(array('module'=>'installment','controller'=>'index','action'=>'getreceiptnumber')); ?>';
function getReceiptbybranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
			    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('invoice_no').attr('value',data);
		},
		error: function(err) {
			alert("eror receipt");
		}
	});
}
var url_branchifo = '<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'getbranch')); ?>';
function getbranchinfo(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_branchifo,	
		content:{ 
			    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			//alert(data.phonebr);
			dojo.byId('brNameShop').innerHTML=data.branch_nameen;
			dojo.byId('brDescription').innerHTML=data.description;
			dojo.byId('brPhone').innerHTML=data.phonebr;
			dojo.byId('brAddress').innerHTML=data.br_address;
			//dijit.byId('invoice_no').attr('value',data);
		},
		error: function(err) {
			alert("eror receipt");
		}
	});
}
</script>
<script type="text/javascript">
dojo.require("dojo.html");
var client_store  = getDataStorefromJSON('id','name', [] );
var client_number_store  = getDataStorefromJSON('id','name', [] );
var pro_store  = getDataStorefromJSON('id','name');
require(["dojo/ready"], function(ready){
	 ready(function(){
		changeCollectType();
	  });
	new dijit.form.FilteringSelect({
	store: client_store,
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: true,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			window.open("<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>","_blank");
			}else{
			getLoanLevel(member);
			dijit.byId('customer_code').attr('value',member);
			getClientInfo();
		}
}
	}, "member");

	new dijit.form.FilteringSelect({
	store: client_number_store,
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
			getClientInfo();
		}
    }
	}, "customer_code");
	new dijit.form.FilteringSelect({
		store: cate_store,
		required: false,		           
		name: "category_id",
		id: "category_id",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			getAllProduct();
		}
	}, "category_id");
	new dijit.form.FilteringSelect({
		store: pro_store,
		required: true,		           
		name: "product_name",
		id: "product_name",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			getProductInfo();
		}
	}, "product_name");
});

var url_getproduct = '<?php echo $this->url(array('module'=>'installment','controller'=>'product','action'=>'getproductbycate')); ?>';
function getAllProduct(){
	category_id = dijit.byId("category_id").get("value");
	branch_id = dijit.byId('branch_id').get('value');
	if(category_id<0){
      return false;
	}
	if(branch_id<0){
	      return false;
	}
	dojo.xhrPost({
		url:url_getproduct,	
		content:{ 
		    'category_id':category_id,'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			pro_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('product_name').set('store', pro_store);
		    dijit.byId('product_name').reset();
		},
		error: function(err) {
		}
	});
}
function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
		dijit.byId('customer_code').reset();
		
		getAllClientByBranch(branch_id);
		getAllClientNumberByBranch(branch_id);
		getReceiptbybranch();
		getbranchinfo();
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclieninstallment')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getcliencodeinstallment')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
function chechPaymentMethod(){
	method_id = dijit.byId('repayment_method').get('value');
	dijit.byId("fixed_payment").set('readOnly',true);
	dijit.byId("fixed_payment").attr('value',0);
	if(method_id==4){
		setDefaultPaymentAmount();
	}else{
	}
}
function changeCollectType(){
	CalculateDate();
}
var getloan_level = '<?php echo $this->url(array('module'=>'installment','controller'=>'index','action'=>'get-loanlevel')); ?>';
function getLoanLevel(client_id){
	   if(client_id==''){
		   return false;}
		dojo.xhrPost({
	    url: getloan_level,	
	    content : { 
	    	'client_id': client_id,
	    	'type':1
		},	    
		handleAs:"json", 
		load: function(data) {	
			customer_code = dijit.byId("customer_code").attr('displayedValue');
			dijit.byId('sale_no').attr('value',customer_code+'-'+data);
		},
		error: function(err) {
		}
	});
}
</script>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_date = dijit.byId('duration').get('value');
	release_date = dijit.byId("first_payment").get('value');
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}
function CalculateDate(){
	pay_term = 3;//for month
	amount_date = dijit.byId('duration').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 3;
	amount_date = 1;
	release_date = dijit.byId("date_sold").get('value');
	var a = new Date(release_date);
	var month = a.getMonth()+amount_date+1;
	
	mm = month%12;
	var year = parseInt(month/12);
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+year;
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);

	amount_date = dijit.byId("duration").get('value');
	var month = a.getMonth()+amount_date+1;
	mm = month%12;
	var year = parseInt(month/12);
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+year;
	var epx_date = y + '-'+ mm + '-'+dd ;
	
	dijit.byId('date_line').attr('value',epx_date);
}
var url_previewloan = '<?php echo $this->url(array('module'=>'installment','controller'=>'index','action'=>'addloantest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		client = dijit.byId('member').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			alert('Please Select Branch Name!');
			dijit.byId('branch_id').focus();
			return false;
		}
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}
		selling_type = dijit.byId('selling_type').get('value');
		interest_rate = dijit.byId('interest_rate').get('value');
		duration = dijit.byId('duration').get('value');

		if(selling_type==2 && interest_rate<=0 && duration<=0){
			alert("រំលស់ អាត្រាការប្រាក់និង រយៈពេលត្រូវតែធំជាងសូន្យ");
			dijit.byId('duration').focus();
			return false;
		}
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";
				temp='';	fund_title=0;thead='';fund_title=0;
				 		temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						temp+='<tr style="background:#bcd5f0;"><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						temp+='<th><?php echo $tr->translate("ចំនួនថ្ងៃ");?></th></tr>';
				for(i=0;i<data.length;i++){
			        r++;
					    temp+='<tr><td align="center">'+r+'</td>';
						var myDate = new Date(data[i].date_payment);
						d = new Date(data[i].date_name);
						temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						temp+='<td>'+dojo.number.format(data[i].outstanding,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						temp+='<td><b>'+dojo.number.format(data[i].total_payment,2)+'<b></td>';
						temp+='<td><b>'+dojo.number.format((data[i].outstanding-data[i].principal_permonth),2)+'<b></td>';
						temp+='<td>'+data[i].amount_day+'</td></tr>';
				 }
				temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("frm_client").show();
			},
			error: function(err) {
				alert(err);
			document.getElementsByClassName("overlay")[0].style.display="none";
			alert("You can not preview this loan number!");
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
}
function showPopupclient(){
	if(dijit.byId('branch_id')!=''){
		dijit.byId("frmpop_client").show();
	}else{
		alert('Please Select Branch First!');
		dijit.byId('branch_id').focus();
		}
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function submitDataClose(type){
   client = dijit.byId('member').get('value');
   branch_id = dijit.byId('branch_id').get('value');
    if (branch_id=='' || branch_id==-1){
  	   alert('Please Select Branch Name!');
	   dijit.byId('branch_id').focus();
	   return false;
    }
	if (client=='' || client==-1){
		alert('Please Select Client Name !');
		dijit.byId('member').focus();
		return false;
	}
	if(dijit.byId('frm_add_tran').validate()){
		selling_type = dijit.byId('selling_type').get('value');
		interest_rate = dijit.byId('interest_rate').get('value');
		duration = dijit.byId('duration').get('value');

		if(selling_type==2 && interest_rate<=0 && duration<=0){
			alert("រំលស់ អាត្រាការប្រាក់និង រយៈពេលត្រូវតែធំជាងសូន្យ");
			dijit.byId('duration').focus();
			return false;
		}
		dijit.byId('saveprint').set('disabled',true);
		dijit.byId('saveclose').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('savenew').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'installment','controller'=>'index','action'=>'submitloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),	
			handleAs:"json",	    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				if(type==1){
					window.location.href ="<?php echo $this->baseUrl();?>/installment/index";
				}else{
				}
			},
			error: function(e) {
			}
		});
	}
}
function getRefreshGroup(){
	filterClient();
	loading();
	setTimeout(stopLoading, 1000);
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function stopLoading(){
	 document.getElementsByClassName("overlay")[0].style.display="none";
}
var urlClientInfo = '<?php echo $this->url(array('module'=>'installment','controller'=>'index','action'=>'getclientinsinfo')); ?>';
function getClientInfo(){
	clientID = dijit.byId('customer_code').get('value');
	if(clientID=='' || clientID==null){return false;}
	dojo.xhrPost({
		url:urlClientInfo,	
		content:{ 
		    'clientID':clientID
		},
		handleAs:"json",
		load: function(data) {
			dojo.byId('LBinvoice').innerHTML=dijit.byId('sale_no').get('value');
			dojo.byId('LBclientName').innerHTML=data.name_kh;
			dojo.byId('LBclientGender').innerHTML=data.sexKH;
			dojo.byId('LBclientNationID').innerHTML=data.nation_id;
			dojo.byId('LBclientVillage').innerHTML=data.villageKH;
			dojo.byId('LBclientComune').innerHTML=data.communeKH;
			dojo.byId('LBclientDistrict').innerHTML=data.districtKH;
			dojo.byId('LBclientProvince').innerHTML=data.provinceKH;
			dojo.byId('LBclientPhone').innerHTML=data.phone;
		},
		error: function(err) {
			alert(err);
		}
	});
}
var urlproductInfo = '<?php echo $this->url(array('module'=>'installment','controller'=>'product','action'=>'getprice')); ?>';
function getProductInfo(){
	product_id = dijit.byId('product_name').get('value');
	if(product_id==''){return false;}
	dojo.xhrPost({
		url:urlproductInfo,	
		content:{ 
		    'product_id':product_id
		},
		handleAs:"json",
		load: function(data) {
			dijit.byId("selling_price").attr("value",data.selling_price);
		},
		error: function(err) {
			alert(err);
		}
	});
  }
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>