<?php	
	$this->headTitle('Edit Loan IL'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	//print_r($this->datarow);
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
		   if(this.validate()) {
			  zone = dijit.byId('zone').get('value');
			  co_id = dijit.byId('co_id').get('value');
			  client = dijit.byId('member').get('value');
              branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}if(co_id=='' || co_id==-1){
				alert('Please Select CO Name !');
				dijit.byId('co_id').focus();
				return false;
			} if(zone=='' || zone==-1){
				alert('Please Select Zone !');
				dijit.byId('zone').focus();
				return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
			currency_type = dijit.byId('currency_type').get('value');
			if(currency_type==1){
				amount_loan = dijit.byId('total_amount').get('value');
				if(amount_loan<10000){
					alert('Loan Amount Must Than 10000 for Riel Currency!');
                }
            }
				return true;
			}else {
				return false;
			}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<fieldset style="background: #e0ebff">
<table width="100%" style="margin-top:0px;" cellspacing="10">
    <legend class="mainblog" ><strong><?php echo $tr->translate("IL_DISBURSE")?></strong></legend>
	<tr>
		<td width="25%;" valign="top">
			 <fieldset >
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						<tr>
					        <td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
					    </tr>
					    <tr>
					 		<td><?php echo $tr->translate('SALE_NO');?></td>
					 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="sale_no" id="sale_no" value="" type="text"></td>
					 	</tr>
					    <tr >
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /><?php //echo $frm->getElement('customer_code');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><input id="member" /> <?php //echo $frm->getElement('member');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td>
								<inut dojoType="dijit.form.TextBox" class="fullside" name="note" id="note" >
							</td>
						</tr>
						<tr>
							<td></td>
							<td><input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/>
							</td>
						</tr>
				</table>
			</fieldset>	
		</td>
		<td width="25%;" valign="top">
			<fieldset>
			<legend align="center" ><strong><?php echo $tr->translate("ពត៌មានទំនិញ")?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;white-space: nowrap;" cellspacing="5" >
			 	<tr>
			 		<td><?php echo $tr->translate('MODEL');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" name="model" id="model" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('Name');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" required="true" name="name" id="name" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('កម្លាំងម៉ាស៊ីន');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" required="true" name="power" id="power" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('ពណ៏');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside" required="true" name="color" id="color" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('លេខម៉ាស៊ីន');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="engine" id="engine" value="" type="text"></td>
			 	</tr>
			 	<tr>
			 		<td><?php echo $tr->translate('លេខតួ');?></td>
			 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="frame" id="frame" value="" type="text"></td>
			 	</tr>
			 </table>
			 
			</fieldset>
		</td>
		<td width="25%;" valign="top">
			 <fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("PAYMENT_INFO")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="5"  >
						
						<tr>
					 		<td><?php echo $tr->translate('តម្លៃលក់');?></td>
					 		<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  name="selling_price" id="selling_price" value="" type="text"></td>
					 	</tr>
						
						<tr>
					 		<td><?php echo $tr->translate('ប្រភេទទិញ');?></td>
					 		<td>
					 			<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
					 				<option value="1"><?php echo $tr->translate('ទិញដាច់');?></option>
					 				<option value="2"><?php echo $tr->translate('បង់រំលស់');?></option>
					 			</select>
					 		</td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('បានបង់');?></td>
					 		<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  name="paid" id="paid" value="" type="text"></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('BALANCE');?></td>
					 		<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  name="balance" id="balance" value="" type="text"></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('លេខវិក័យបត្រ');?></td>
					 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="invoice_no" id="invoice_no" ></td>
					 	</tr>
						
						<tr>
					 		<td><?php echo $tr->translate('ថ្ងៃបង់ប្រាក់');?></td>
					 		<td><input dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="paid_date" id="paid_date" ></td>
					 	</tr>
					    
				</table>
			</fieldset>	
		</td>
		<td width="25%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("INFO_FUND")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;white-space: nowrap;" cellspacing="5"  >
						 
						 <tr>
					 		<td><?php echo $tr->translate('ថ្ងៃខ្ចីប្រាក់');?></td>
					 		<td><input dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="installment_date" id="installment_date" ></td>
					 	 </tr>
					 	 <tr>
					 		<td><?php echo $tr->translate('អាត្រាការប្រាក់(%)');?></td>
					 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="interest" id="interest" ></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('រយះពេលខ្ចី(ខែ)');?></td>
					 		<td><input dojoType="dijit.form.TextBox" class="fullside"  name="duration" id="duration" ></td>
					 	</tr>
					 	<tr>
					    	<td><?php echo $tr->translate("REPAYMENT_TYPE")?></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
					     </tr>
					     
					 	<tr>
					 		<td><?php echo $tr->translate('ថ្ងៃបង់ប្រាក់ដំបូង');?></td>
					 		<td><input dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="first_payment" id="first_payment" ></td>
					 	</tr>
					 	<tr>
					 		<td><?php echo $tr->translate('ថ្ងៃបញ្ចប់');?></td>
					 		<td><input dojoType="dijit.form.DateTextBox" class="fullside" value="now" name="date_line" id="date_line" ></td>
					 	</tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	 
	<tr>
		<td align="center" colspan="4">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="button" onclick="submitDataClose(1);" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  
				 iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		 <input type="button" onclick="showInvoice();" label="<?php echo $tr->translate("PREVIEW INVOICE")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		
		</td>
	</tr>	
</table>
</fieldset>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់', onCancel:hideDialog" id="frm_client" style="width:1000px">
	<div id="rpt_print" class="print">
	<div id="t_amountmoneytype" name="t_amountmoneytype"></div>
	</div>
</div>
</div>
</form>
<script type="text/javascript">	
    function checkValidateDate(){
    	debt_term = dijit.byId('pay_every').get('value');
		if(debt_term==1){
			term_d =1; 
		}else if(debt_term==2){
			term_d =7; 
		}else{
			term_d =30; 
		}
		
		collect_term = dijit.byId('collect_termtype').get('value');
		if(collect_term==1){
			term_c =1; 
		}else if(collect_term==2){
			term_c =7; 
		}else{
			term_c =30; 
		}
		debt_amount = dijit.byId('period').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if((collect_amount*term_c)>(debt_amount*term_d)){
			alert('<?php echo $tr->translate("SMS_BORROW_FUND")?>');
			dijit.byId('collect_termtype').focus();
			return false;
		}
		/*method = dijit.byId('repayment_method').get('value');
		amount_collect = dijit.byId('amount_collect_pricipal').get('value');
		amount_principal = dijit.byId('total_amount').get('value');
		if(method==4 AND (debt_amount*term_d)/(collect_amount*term_c)*amount_collect>amount_principal ){
			
		}*/
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('total_amount').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	
    	collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		if(dijit.byId("currency_type").get('value')==1){
			amount_payment = amount_payment%100 > 0 ? (amount_payment-(amount_payment%100)+100) : amount_payment;
		}
		dijit.byId('amount_collect_pricipal').attr('value',amount_payment);
	}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		changeCollectType();
	  });
	 var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "<?php echo $this->datarow['branch_id'];?>"
	},            
	required: false,		           
	name: "member",
	id: "member",
	class:"fullside",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	value:"<?php echo $this->datarow['customer_id'];?>",	     
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			//showPopupclient();
			window.open("<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>","_blank");
			} 
		getClientInfo(2);
}
	}, "member");

	 var client_number = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient_number));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	query: {
		branch_id: "<?php echo $this->datarow['branch_id'];?>"
	},            
	required: false,	
	value:"<?php echo $this->datarow['customer_id'];?>",	           
	name: "customer_code",
	id: "customer_code",
	class:"fullside",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	onChange: function() {
		getClientInfo(1);
}
	}, "customer_code");
	 
	});
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
//dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
		dijit.byId('customer_code').reset();
		getLoanByBranch();
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';

function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	if(dijit.byId("branch_id").get("value")=='<?php echo $this->datarow['branch_id']?>'){
		dijit.byId("loan_code").attr("value",'<?php echo $this->datarow['loan_number']?>');
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			//alert(data);	
			dijit.byId('loan_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
function showloantype(){
	$('#loan_type').val('asdfsd');
	$('input[name="loan_type"]').val("10");
}
function calCulateAdminFee(){
	p_income="<?php echo $this->setting['adminfee']?>";
	t_admin=dijit.byId('total_amount').get('value');
	adminfee=(p_income*(t_admin/100));
	dijit.byId('loan_fee').attr('value',adminfee);
}
function CompareGraicePariod(){
	graice_pariod = dijit.byId('graice_pariod').get('value');
	period = dijit.byId('period').get('value');
	if(graice_pariod>=period){
		alert('<?php echo $tr->translate("AMOUNT_GRAICEPARIOD_THEN_AMOUNT_LOAN")?>');
		dijit.byId('graice_pariod').attr('value',(period-1));
	}
}
function chechPaymentMethod(){
	method_id = dijit.byId('repayment_method').get('value');
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?>";
	dijit.byId('amount_collect_pricipal').attr('value',0);

	dijit.byId("amount_collect").set('readOnly',false);
	dijit.byId("collect_termtype").set('readOnly',false);
	
	
	if(method_id==6){
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
		dijit.byId('amount_collect').attr('value',1);
		dijit.byId('amount_collect').set('readOnly',true);
		
	}else if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId("amount_collect").set('readOnly',true);
		dijit.byId("collect_termtype").set('readOnly',true);
		dijit.byId('amount_collect_pricipal').attr('value',2);
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').attr('value',1);
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
		dijit.byId('amount_collect_pricipal').attr('value','');
		dijit.byId('amount_collect_pricipal').focus();
		setDefaultPaymentAmount();
	}else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}
}

function changeCollectType(){
	get_id = dijit.byId('pay_every').get('value');
	dijit.byId('collect_termtype').attr('value',get_id);
	changeGraicePeroid();
	CalculateDate();
}
function changeGraicePeroid(){
	disp_value = dijit.byId('collect_termtype').attr('displayedValue');
	dojo.byId('graice_type').innerHTML=disp_value;
	calCulateFirstPayment();
	
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

/*
   function popupCheckClient(){
		if(dijit.byId('group_id').get('value')==-1){
			 dijit.byId('frm_client').show();
		}
	}
	function popupCheckCO(){
		if(dijit.byId('co_id').get('value')==-1){
			 dijit.byId('frm_co').show();
		}
	}
	function popupCheckZone(){
		if(dijit.byId('zone').get('value')==-1){
			 dijit.byId('frm_zone').show();
		}
	}
	function popupCheckDistrict(){
	if(dijit.byId('district').get('value')==-1){
		 dijit.byId('frm_district').show();
	}
}
function popupCheckCommune(){
	if(dijit.byId('commune').get('value')==-1){
		 dijit.byId('frm_commune').show();
	}
}
function popupCheckVillage(){
	if(dijit.byId('village').get('value')==-1){
		 dijit.byId('frm_village').show();
	}
}*/
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
	getLoanLevel(customer_code);
}
var getloan_level = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-loanlevel')); ?>';
function getLoanLevel(client_id){
		dojo.xhrPost({
	    url: getloan_level,	
	    content : { 
	    	'client_id': client_id,
	    	'type':1
		},	    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('level').attr('value',data);
		},
		error: function(err) {
		}
	});
}

var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add-newclient')); ?>';
function addNewClient(){
		dojo.xhrPost({
	    url: url_submit,	
		form: dojo.byId("form_client"),		    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('frm_client').reset(); 
			dijit.byId('frm_client').hide();
		},
		error: function() {
		alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
		     alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitzone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
		dojo.xhrPost({
	    url: url_submitzone,	
		form: dojo.byId("form_zone"),		    
		handleAs:"json",
		load: function(data) {	
			//alert(data);
			dojo.byId('form_zone').reset(); 
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
		}
	});
}
</script>
<?php 
// echo $this->frmpupopclient;
// echo $this->frmPopupCO;
 //echo $this->frmPopupZone;
 //echo $this->frmPopupCommune;
 //echo $this->frmPopupDistrict;
 //echo $this->frmPopupVillage;
 echo $this->frmpupoploantype;
?>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	//alert('date release'+date_release);
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	calCulateFirstPayment();
}
function calCulateEndDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		if(pay_term==3){//month
			mm = a.getMonth()+amount_date+1;
		}else if(pay_term==2){//week
			a.setDate(a.getDate() + (amount_date*7)); 
			var mm = a.getMonth() + 1;
		}else if(pay_term==1){
			a.setDate(a.getDate() + (amount_date)); 
			var mm = a.getMonth() + 1;
		}
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}

function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	//release_date = dijit.byId("release_date").get('value');//before 
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	//alert('date first'+release_date);
	
	if(isNaN(amount_date)){
		//alert('សូមបញ្ចលចំនួនរយៈពេល​ !');
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = dijit.byId('collect_termtype').get('value');
	amount_date = dijit.byId('amount_collect').get('value');
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
	if(pay_term==3){//month
		var month = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var month = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var month = a.getMonth() + 1;
	}else{
	}
	mm = month%12;
	var year = parseInt(month/12);
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+year;
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
////add preview loan
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloantest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		zone = dijit.byId('zone').get('value');
		co_id = dijit.byId('co_id').get('value');
		client = dijit.byId('member').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			alert('Please Select Branch Name!');
			dijit.byId('branch_id').focus();
			return false;
		}
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}if(co_id=='' || co_id==-1){
			alert('Please Select CO Name !');
			dijit.byId('co_id').focus();
			return false;
		}if(zone=='' || zone==-1){
			alert('Please Select Zone !');
			dijit.byId('zone').focus();
			return false;
		}
		rs = checkValidateDate();
		if(rs==false){
          return false;			
        }
		loading();	
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";
				temp='';	fund_title=0;thead='';fund_title=0;
				 		temp='<table class="collape tablesorter" style="font-size:13px;" id="table" width="100%">'
						temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						temp+='<th><?php echo $tr->translate("ចំនួនថ្ងៃ");?></th></tr>';
				for(i=0;i<data.length;i++){
			        r++;
					    temp+='<tr><td align="center">'+r+'</td>';
					    var myDate = new Date(data[i].date_payment);
						d = new Date(data[i].date_name);
						temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_principal,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						temp+='<td><b>'+dojo.number.format(data[i].total_payment,2)+'<b></td>';
						temp+='<td><b>'+dojo.number.format((data[i].total_principal-data[i].principal_permonth),2)+'<b></td>';
						temp+='<td>'+data[i].amount_day+'</td></tr>';
				 }
				temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("frm_client").show();
			},
			error: function(err) {
				alert(err);
			alert("You can not preview this loan number!");
			}
	   });
	}
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}

function hideDialog() {		
	dijit.byId("frm_client").hide();
}

function getRefreshGroup(){
	filterClient();
	getAllCo();
	loading();
	setTimeout(stopLoading, 1000);
}

var url_co = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-coname')); ?>';
function getAllCo(){
	dojo.xhrPost({
		url:url_co,	
		content:{ 
		    //'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			 alert(data);
			var co_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('co_id').set('store', co_store);
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function getAddCoNew(){
	co_id = dijit.byId('co_id').get('value');
	if(co_id==-1){
		window.open("<?php echo $this->url(array('module'=>'loan','controller'=>'co','action'=>'add')); ?>","_blank");
	}else{
	}
}

function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

function stopLoading(){
	 document.getElementsByClassName("overlay")[0].style.display="none";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>