<?php
	$this->headTitle('Add Loan IL'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<script language="javascript">
function createTable() {
    // Get the data
	var excelData = document.getElementById('csv').value;
    // split into rows
    excelRow = excelData.split(String.fromCharCode(10));
    // split rows into columns
    for (i=0; i<excelRow.length; i++) {
        excelRow[i] = excelRow[i].split(String.fromCharCode(9));
    }
	// start to create the HTML table
	var myTable = document.createElement("table");
	var myTbody = document.createElement("tbody");
	// Loop over the rows
    for (i=0; i<excelRow.length - 1; i++) {
		// create a row in the HTML table
		var myRow = document.createElement("tr");
		// Loop over the columns and add TD to the TR
		for (j=0; j<excelRow[i].length; j++) {
			// Loop over the row columns
			if (excelRow[i][j].length != 0) {
					var myCell = document.createElement("td");
					var myCell = document.createElement("input");
					myCell.setAttribute("type", "text");
					myCell.setAttribute("name", 'score_'+i+"_"+j);
					myCell.setAttribute("id", 'score_'+i+"_"+j);
					myCell.setAttribute("dojoType", 'dijit.form.NumberTextBox');
					myCell.setAttribute("value", excelRow[i][j]);
            }			
			myRow.appendChild(myCell);			
		}
		myTbody.appendChild(myRow);	
	}
	myTable.appendChild(myTbody);
    document.body.appendChild(myTable);
}
</script>
<textarea id="csv" placeholder="Paste XLSX content here" style="width: 300px; height: 100px;"></textarea><br/>
<input type="button" value="Ganerate" onclick="createTable()" >
</html>