  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  $rpt_loanrelease=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-disburse'), null, true);
  $rpt_loanoustading=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-outstanding'), null, true);
  $rpt_loanoustadingvillage=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-outstandingvillage'), null, true);
  $rpt_collectfromco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco'), null, true);
  $rpt_loancollect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect'), null, true);
  $rpt_dailypayment=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment'), null, true);
  $rpt_loanincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-income'), null, true);
  $rpt_loan_late=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late'), null, true);
  $rpt_total_collect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-total-collect'), null, true);
  $rpt_writoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-writoff'), null, true);
  $rpt_paymenthistory=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment-history'), null, true);
  $rpt_reschedule=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-reschedule-loan'), null, true);
  $rpt_payoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-payoff'), null, true);
  $rpt_expectincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-expect-income'), null, true);
  $rpt_exchangemoney=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-xchange'), null, true);

  $rpt_commission=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-commission'), null, true);
  $rpt_loandialy=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-dailyloan'), null, true);
  
  $rpt_loandisburseco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-disburse-co'), null, true);
  $rpt_npl=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-npl'), null, true);
  $rpt_transferloan=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-trasfer'), null, true);
  $rpt_clientco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-clientco'), null, true);
  $rpt_transfer=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-transfer'), null, true);
  $rpt_expense  =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-expense'), null, true);
  
  $rpt_parco  =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-parbyco'), null, true);
  $rpt_area =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loanarea'), null, true);
  $rpt_dialypayment =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-dailypayment'), null, true);
  $rpt_transferzone =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-trasferzone'), null, true);
  $rpt_incomestatement =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-incomestatement'), null, true);
  $rpt_revenue = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-income'), null, true);
  
  $session_user=new Zend_Session_Namespace('authloan');
  $url_report=$session_user->report_url;

  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 60px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  	<?php
  	$db_user=new Application_Model_DbTable_DbUsers();
  	$url_report=$db_user->getAclReport(1);
  	 if(!empty($url_report)){
  		foreach($url_report as $rs){
  			if($rs['action']=='rpt-paymentschedules' || $rs['action']=='index'){continue;}
  		?>
  		<li><a href="<?php echo $this->url(array("module"=>'report',"controller"=>'loan','action'=>$rs['action']));?>"><?php echo $tr->translate(strtoupper($rs['label']));?></a></li>
  		<?php 
		}	
	}	?>
  	</ul>
  </div>
  <div style="clear: both;"></div>