<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$end_dat=$this->date_show;
$session_user=new Zend_Session_Namespace('authloan');
$level = $session_user->level;
//print_r($this->LoanCollectionco_list);
?>
<style>
.hover:hover{ background: #ccc;}
</style>
<title><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content'; width:29cm;margin:0 auto;" >
	  <tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			
   	  </tr>
   	 <tr>
   	 		<td><?php echo $frm->getElement('paymnet_type');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	  </tr>
</table>
</form>
<div style="width:100%; margin:0 auto; clear:both;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
                	 $co_id = null;
                ?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("D-d-M-Y",strtotime($this->start_date)).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->date_show));?></li>
                		</ul>
                	</td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
</table>
<div id="exportExcel">
<table  width="100%" border="1" style="border-collapse:collapse; border: 1px solid #000;" cellspacing="0">
		    <thead>
		        <tr class="style" bgcolor="#ccc" align="center" style="font-weight:bold; line-height: 24px; font-size:10px; white-space: nowrap; ">
			      <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("LOAN_NO");?></td>	  
	                    <td rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></td>                  
	                    <td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("INTEREST_RATE");?></td>
	                    <?php 
							$colspan=5;
	                    if($level==1){$colspan=5;}?>
	                    <td colspan="<?php echo $colspan;?>"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>    
	                    <td rowspan="2" style="white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></td>
	                    <!-- <td rowspan="2"><?php //echo $tr->translate("PAYMENTED");?></td> -->
	                    <!--<td><?php //echo $tr->translate("RETURN_AMOUNT");?></td>-->
	                    <td rowspan="2"><?php echo $tr->translate("BALANCE");?></td>
			   	</tr>
			   	<tr class="style" style="white-space: nowrap;text-align: center;">
	                	<td ><?php echo $tr->translate("PRINCIPLE");?></td>                   
	                   <?php if($level==1){?>                 
	                    <td><?php echo $tr->translate("INTEREST");?></td>
	                    <?php }?>
	                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
	                    <td><?php echo $tr->translate("SERVICE CHARGE");?></td>
	                    <td><?php echo $tr->translate("TOTAL");?></td>
	                </tr>
	             </thead>
<?php 
$is_set =0 ;if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){?>
	<?php 
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['principal_amount'];
		               		$amt_r2 = $amt_r2+$rs['total_interest'];
		               		$amt_r3 = $amt_r3+$rs['penelize_amount'];
		               		$amt_r5 = $amt_r5+$rs['service_charge'];
		               		$total_r=$amt_r1+$amt_r2+$amt_r3+$amt_r5;
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['principal_amount'];
							$amt_d2 = $amt_d2+$rs['total_interest'];
							$amt_d3 = $amt_d3+$rs['penelize_amount'];
							$amt_d5 = $amt_d5+$rs['service_charge'];
							$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
		               }else{
		               		$amn_b1 = $amn_b1+$rs['principal_amount'];
							$amn_b2 = $amn_b2+$rs['total_interest'];
							$amn_b3 = $amn_b3+$rs['penelize_amount'];
							$amn_b5 = $amn_b5+$rs['service_charge'];
							$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
		               }
               ?>
     <?php if($co_id!=$rs["co_id"]){ ?>
				<tr>
					<td colspan="16" style="font-size: 12px;padding-left:4px; font-weight:500; background:#CADEE3;"><b><?php echo $rs["co_name"];?></b></td>
				</tr>
					<?php 
               } $co_id = $rs["co_id"];?>
			   	<tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
               		<td style="font-size: 10px;padding:0px 2px;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo $rs["branch"];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo $rs["client_code"];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo $rs["client_name"];?></td>
               		<!-- <td style="font-size: 10px; white-space: nowrap;"><?php //echo $rs["phone"];?></td> -->
               		<!--<td style="font-size: 10px;"><?php //echo number_format( $rs["capital"],2).' '.$rs['currency_type'];?></td> -->
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo $rs["interest_rate"];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo number_format($rs['principal_amount'],2).' '.$rs['currency_type'];?></td>  
               		<?php if($level==1){?>
	               		<td style="font-size: 10px;padding:0px 2px;">&nbsp;
	               		<?php echo number_format($rs['total_interest'],2).' '.$rs['currency_type'];?>
	               		&nbsp;</td>
               		<?php }?>           		
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo number_format($rs['penelize_amount'],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo number_format($rs['service_charge'],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 10px;padding:0px 2px;"><?php echo number_format($rs['recieve_amount'],2);?></td>
               		<td style="font-size: 10px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_payment"]));?></td>
               		<td style="font-size: 10px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_input"]));?></td>
               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
               		<td style="font:bolder 11px Arial;">&nbsp;<?php 
               		$balance=$rs["amount_recieve"]-$rs["return_amount"]-$rs["payment"];
               		if($rs["amount_recieve"]-$rs["return_amount"]>=$rs["payment"]){echo 0;}else {echo number_format(-$balance,2);}; echo $rs['currency_type'];?>&nbsp;</td>
                </tr>
<?php  }?>
</table><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td style="font-size: 12px;">ប្រភេទប្រាក់</td>
                   <?php if($level==1){?>    
	                    <td><?php echo $tr->translate("PRINCIPAL");?></td>                    
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
                    <?php }?>
                    <td style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
                    <td style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></td>
                    <td style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <?php }?>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
              </table>
	            <br />
	            <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
</div>
</div>
</div>
</div>
