<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
.hover:hover{background: #ccc;}</style>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></title>
<form method="post">
	<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
			<td><?php echo $filter->getElement('member');?></td>
		</tr>
		<tr>
			<td><?php echo $filter->getElement('pay_every');?></td>
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td>
				<select class='fullside' name="status" id="status" dojoType="dijit.form.FilteringSelect">
					<option value="-1" <?php if($this->statusopt==-1){echo "selected";}?>>ជ្រើសរើសការបង់ប្រាក់</option>
					<option value="1" <?php if($this->statusopt==1){echo "selected";}?>>បានបង់ដាច់</option>
					<option value="0" <?php if($this->statusopt==0){echo "selected";}?>>មិនទាន់បង់ដាច់</option>
				</select>
			</td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	</form>
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold; list-style-type: none;}
td ul li{list-style: none; }

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}
</style>
<div style="clear: both;"></div>
<div  style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm;">
<div id="divPrint" style="width: 100%;">
<table id="exportExcel" style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="list-style:none; text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="list-style:none;text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></li>
                			<li style="list-style:none;text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                    </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                   <?php  
                    $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
                    $co_id='';$other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
                    $all_total_r=0;$all_total_b=0;$all_total_d=0;$num=1;
                    $count_ld = 0;$count_lr=0;$count_lb=0;$tcount_ld=0;$tcount_lr=0;$tcount_lb=0;
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){
               ?>
               <?php if($row['curr_type']==1){
               	$all_total_r=$all_total_r+$row["total_capital"];
               	$tcount_lr=$tcount_lr+1;
               	
               }elseif($row['curr_type']==2){
               		$all_total_d=$all_total_d+$row["total_capital"];
               		
               		$tcount_ld=$tcount_ld+1;
               }else{
               		$all_total_b=$all_total_b+$row["total_capital"];
               		$tcount_lb=$tcount_lb+1;
               };
               ?>
                <?php 
                if($co_id!=$row['co_id']){
                	$num=1;
                ?>
                <?php if($key>0){?>
               
                <tr>
                	<td style="background: #8494B5;" class="style" colspan="11">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
                </tr>
	            <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px;">
                    <td style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</td>
                    <td style="padding:5px 0px;">&nbsp;​<?php echo $tr->translate("ចំនួនកម្ចី");?>&nbsp;</td>
                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_FEE");?>&nbsp;</td>
                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("OTHER_FEE");?>&nbsp;</td>
                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
	            </tr>
	           
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                    <td>&nbsp;<?php echo $count_ld;?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo  number_format($other_fee_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lr);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo  number_format($other_fee_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lb);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                   <td colspan="2">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo  number_format($other_fee_b,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
                </table>
                    <br />
                <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                
                <?php  $count_ld=0;$count_lr=0;$count_lb=0; } 
	                $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
	                $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
                ?>
             <?php ?>
                <thead>
                <tr>
                	<td colspan="16" class="style" style="background:#8494B5;">&nbsp;<span style="text-align:center;"><?php //echo $tr->translate("CO_NAME");?> </span><?php  echo $row['co_code'].' , '.$row['co_name'].' - '.$row['co_name_en'].' '//.($row['sex']=1?'ភេទ ប្រុស':'ភេទ  ស្រី'); ?></td>
                </tr>
                 <tr bgcolor="#ccc" align="center" class="style" style="font-weight:bold; line-height: 18px; font-size:12px;white-space:nowrap;">
                   <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_LEVEL");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>%&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("AMIN_FEE");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_TYPE");?>&nbsp;</td>
                </tr>
                </thead>
                <?php }
              
                $co_id = $row['co_id'];
                ?>
               <?php 
               if($row['curr_type']==1){
               		$amt_r = $amt_r+$row['total_capital'];
               		$amn_r = $amn_r+$row['admin_fee'];
               		$other_fee_r=$other_fee_r+$row['other_fee'];
               		$total_r=$amt_r+$amn_r+$other_fee_r;
               		
               		$count_lr=$count_lr+1;
               		//$count_lr=$count_lr+1;
               		
               }elseif($row['curr_type']==2){
               		$amt_d = $amt_d+$row['total_capital'];
               		$amn_d = $amn_d+$row['admin_fee'];
               		$other_fee_d=$other_fee_d+$row['other_fee'];
               		$total_d=$amt_d+$amn_d+$other_fee_d;
               		//$count_ld=$count_ld+1;
               		$count_ld=$count_ld+1;
               		
               }else{
               		$amt_b = $amt_b+$row['total_capital'];
               		$amn_b = $amn_b+$row['admin_fee'];
               		$other_fee_b=$other_fee_b+$row['other_fee'];
               		$total_b=$amt_b+$amn_b+$other_fee_b;
               		//$count_lb=$count_lb+1;
               		
               		$count_lb=$count_lb+1;
               }
               ?>
					<tr align="center" class="hover">
						<td>&nbsp;<?php echo $num; $num++;?>&nbsp;</td>
						<td style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['client_number']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['client_khname']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['level'];?>&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
						<td >&nbsp;<?php echo $row['interest_rate']; ?>&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['admin_fee'],2).' '.$row['currency_type']?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['total_duration'].$row['name_en'];?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['loan_type'];?>&nbsp;</td>
						
					</tr>
				<?php } //echo $a;?>
            	 <tr>
                	<td  style="background: #8494B5;" colspan="11">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
                </tr>
                  <tr bgcolor="#ccc" class="style" style="font-weight:bold;font-weight:bold; line-height: 24px; text-align: center;" >
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</td>
	                    <td style="padding:5px 0px;">&nbsp;​<?php echo $tr->translate("ចំនួនកម្ចី");?>&nbsp;</td>
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_FEE");?>&nbsp;</td>
	                    <td style="padding:5px 0px;"colspan="2">&nbsp;<?php echo $tr->translate("OTHER_FEE");?>&nbsp;</td>
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
	                </tr>
                 <tr class="style" style=" font-weight:bold;line-height: 24px; font-size:12px;font-family: 'Khmer OS Content';">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($count_ld,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($other_fee_d,2);?>&nbsp;</td>
					<td colspan="2">&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td> 
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:12px;font-family: 'Khmer OS Content';">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($count_lr,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
                  	<td colspan="2">&nbsp;<?php echo number_format($other_fee_r,2);?>&nbsp;</td>
                  	<td colspan="2">&nbsp;<?php echo number_format($other_fee_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" font-weight:bold;line-height: 24px; font-size:12px;font-family: 'Khmer OS Content';">
                   <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;<?php echo number_format($count_lb,2);?>&nbsp;</td>
                   <td colspan="2">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                   <td colspan="2">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
                   <td colspan="2">&nbsp;<?php echo number_format($other_fee_b,2);?>&nbsp;</td>
                   <td colspan="2">&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td> 
                </tr>
              </table>
             <div style="border:1px dashed #000;margin:10px 0px; "><strong>Total Only Loan Disbursed</strong></div>
    	</td>
    </tr>
     	<tr><td>
              <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
              		 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px; " >
	                    <td  style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</td>
	                    <td style="padding:5px 0px;">&nbsp;​<?php echo $tr->translate("ចំនួនកម្ចី");?>&nbsp;</td>
	                    <td  style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
	                </tr>
	                <tr class="style" style="font-weight:bold; line-height: 24px; font-size:12px;">
                    	<td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                    	<td>&nbsp;<?php echo ($tcount_ld);?>&nbsp;</td>
                   		 <td colspan="2">&nbsp;<?php echo number_format($all_total_d,2);?>&nbsp;</td>
                	</tr>
                	<tr class="style" style="font-weight:bold; line-height: 24px; font-size:12px;">
                    	<td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                    	<td>&nbsp;<?php echo ($tcount_lr);?>&nbsp;</td>
                   		<td colspan="2">&nbsp;<?php echo number_format($all_total_r,2);?>&nbsp;</td>
                	</tr>
                	<tr class="style" style="font-weight:bold; line-height: 24px; font-size:12px;">
                    	<td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?></td>
                    	<td>&nbsp;<?php echo $tcount_lb;?>&nbsp;</td>
                   		<td colspan="2">&nbsp;<?php echo number_format($all_total_b,2);?>&nbsp;</td>
                	</tr>
              </table>
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
        </td>
       </tr>       
</table>
</div>
</div>
