<?php $frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
</style>
<title><?php echo $tr->translate("LOAN_OUTSTADING");?></title>
 <form method="post">
<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
	<tr>
   		<td><?php echo $frm->getElement("adv_search");?></td>
   		<td><?php echo $frm->getElement('branch_id');?></td>
   		<td><?php echo $frm->getElement('pay_every');?></td>
   		<td><?php echo $frm->getElement('member');?></td>
   	</tr>
   	<tr>
   		<td><?php echo $frm->getElement('co_id');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement('status');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LOAN_OUTSTADING_VILLAGE");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date('D-d-m-Y',strtotime($this->fordate));?></li>
                		</ul></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table border="1"? style="border-collapse:collapse;border:1px solid #000; font-size:12px; white-space: nowrap;" width="100%" cellspacing="0">
               <thead>
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; padding: 2px 0px;background:#ccc;">
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("CO_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;"> &nbsp;<?php echo $tr->translate("RELEASE_DATE");?>&nbsp;</td>
                    <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
                    <td style="padding:2px 0px;font-size: 8px;"><?php echo $tr->translate("FOR_LOAN_TYPE");?></td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("PERCENTAGE");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("NOT_TO_REPAY");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("PROVINCE_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("DISTRICT_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("COMMUNE_NAME");?>&nbsp;</td>
                    <td style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("VILLAGE_NAME");?>&nbsp;</td>
                </tr>
               </thead>
               <?php 
               $dbvillage = new Application_Model_DbTable_DbGlobal();
               $vill = $dbvillage->getClientByType(null,$clientid=1,$row=1);
               $db = new Report_Model_DbTable_DbLoan();
               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;$result_b=0;$result_r=0;$result_d=0;
               if(!empty($this->outstandloan)) foreach($this->outstandloan as $key =>$row){?>
               <?php 
	               $total_receive = $row['total_payment'];//$db->getAmountReceiveByLoanNumber($row['loan_number']);
	               if($row['curr_type']==1){
	               		$amt_r = $amt_r+$row['total_capital'];
	               		$amn_r = $amn_r+$total_receive;
	               		$result_r=number_format(($amn_r/$amt_r)*100,2).' %';
	               }elseif($row['curr_type']==2){
	               		$amt_d = $amt_d+$row['total_capital'];
	               		$amn_d = $amn_d+$total_receive;
	               		$result_d=number_format(($amn_d/$amt_d)*100,2).' %';
	               }else{
	               		$amt_b = $amt_b+$row['total_capital'];
	               		$amn_b = $amn_b+$total_receive;
	               		$result_b=number_format(($amn_b/$amt_b)*100,2).' %';
	               }
               ?>
					<tr align="center" class="hover">
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td style="line-height: 12px; white-space: nowrap;">&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
						<td align="left" style="font-size:9px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_kh']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['co_name'];?>&nbsp;</td>
						<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
						<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_line']));?>&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
						<td style="white-space: nowrap;">&nbsp;<?php echo number_format($row['total_duration']).$row['pay_term'];?>&nbsp;</td>
						<td align="left">&nbsp;<?php 
							if ($row['loantype']==1){echo 'indi';}
							else {
								echo 'group';
							}
							; ?>&nbsp;
						</td>	
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($total_receive,2).' '.$row['currency_type'];?>&nbsp;</td>
						<td>&nbsp;<?php 
								echo (round(($total_receive/$row['total_capital']),2)*100).' %';
						?>&nbsp;</td>
						<td>&nbsp;<?php echo number_format(($row['total_capital']-$total_receive),2).' '.$row['currency_type'];?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['province_en_name']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['district_name']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo str_replace("Commune", "", $row['commune_name']); ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['village_name']; ?>&nbsp;</td>
					</tr>
				<?php }?>
            </table>
            <br />
             <table border="1"? style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;">
                    <td style="padding:2px 0px;"><?php echo $tr->translate("CURRENT_TYPE");?></td>
                    <td style="padding:2px 0px;"><?php echo $tr->translate("LOAN_AMOUNT");?></td>
                    <td style="padding:2px 0px;"><?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?></td>
                    <td style="padding:2px 0px;"><?php echo $tr->translate("PERCENTAGE");?></td>
                    <td style="padding:2px 0px;"><?php echo $tr->translate("NOT_TO_REPAY");?></td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_d;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_d-$amn_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_r;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_r-$amn_r);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_b;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_b-$amn_b);?>&nbsp;</td>
                </tr>
              </table>
              <br />
              <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>