<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលោះប្រាក់ដើម",4=>"បង់ផ្តាច់");
$session_user=new Zend_Session_Namespace('authloan');
$level = $session_user->level;
?>
<title><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>   			
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>   			
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint">
<style type="text/css">
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
.style1:hover{ background: #ccc; }
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<table width="100%">
	<tr>
    	<td align="center" valign="top">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';"style="margin:0;padding:0;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="80px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                   </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%" cellpadding="0" cellspacing="0">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel"><strong style="font-family: 'Khmer OS Content';">តារាងទំលាក់ទុនប្រចាំថ្ងៃ</strong>
             <?php $r1=0; $r2=0;$d1=0;$d2=0;$b1=0;$b2=0;
				$disburse_dollar = 0;$disburse_reil = 0;$disburse_bath = 0;
				$saving_amountr = 0;$saving_amountd = 0;$saving_amountb = 0;
             ?>
            <?php if(!empty($this->LoanFee_list)){?>
            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; font-size:10px;" cellspacing="0">
            	<thead>
            	<tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; padding:5px 0px; ">
                  <th><?php echo $tr->translate("NUM");?></th>
                  <th><?php echo $tr->translate("BRANCH_NAME");?></th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</th>
                  <th style="padding:5px 0px;"> &nbsp;<?php echo $tr->translate("RELEASE_DATE");?>&nbsp;</th>
                  <th>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</th>
                  <th><?php echo $tr->translate("AMIN_FEE");?></th>                    
                  <th><?php echo $tr->translate("OTHER_FEE");?></th>
                  <th style="padding:5px 0px;font-size: 8px;"><?php echo $tr->translate("FOR_LOAN_TYPE");?></th>
                </tr>
                </thead>
                <?php if(!empty($this->LoanFee_list)) foreach ($this->LoanFee_list as $key => $row){ ?>
                <?php 
                if($row['curr_type']==1){
		               		$r1 = $r1+$row['admin_fee'];
		               		$r2 = $r2+$row['other_fee'];
		               		$disburse_reil=$disburse_reil+$row['total_capital'];
		               }elseif($row['curr_type']==2){
							$d1 = $d1+$row['admin_fee'];
							$d2 = $d2+$row['other_fee'];
							$disburse_dollar=$disburse_dollar+$row['total_capital'];
		               }else{
		               		$b1 = $b1+$row['admin_fee'];
							$b2 = $b2+$row['other_fee'];
							$disburse_bath=$disburse_bath+$row['total_capital'];
		               }
		         ?>
                <tr class="styleover">
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $row["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $row["loan_number"];?></td>
					<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
					<td align="left" style="font-size:9px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_khname']; ?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_line']));?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo number_format( $row["admin_fee"],2).' '.$row['currency_type'];?></td>               		
               		<td >&nbsp;&nbsp;<?php echo number_format($row["other_fee"],2).' '.$row['currency_type'];?></td>
               		<td style="font-size: 8px;">&nbsp;<?php 
							if ($row['loantype']==1){echo 'indi';}
							else {
								echo 'group';
							}
							; ?>&nbsp;</td>
                </tr>
                <?php }?>
            </table>
            <?php }?>
            <strong style="font-family: 'Khmer OS Content';">តារាងប្រមូលប្រាក់ប្រចាំថ្ងៃ</strong> 
            <table  width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
	                <tr bgcolor="#ccc" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
	                    <td rowspan="2" align="center"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("LOAN_NO");?></td>	  
	                    <td rowspan="2" align="center"><?php echo $tr->translate("CLIENT_NUM");?></td>                  
	                    <td rowspan="2" align="center"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("CO_NAME");?></td>
	                    <?php 
                          $colspan=5;?>
	                    <td colspan="<?php echo $colspan;?>"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>    
	                    <td rowspan="2" style="text-align:center;white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("INPUT_DATE");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("RECIEPT_NO");?></td>
	                    <td rowspan="2" align="center"><?php echo $tr->translate("PAYMENT_OPTION");?></td>
	                    <!-- <td rowspan="2"><?php //echo $tr->translate("BALANCE");?></td>-->
	                </tr>
	                <tr class="style" style="white-space: nowrap;text-align: center;">
	                	<td><?php echo $tr->translate("PAID_PRINCIPAL");?></td>  
	                	<?php if($level==1){?>                 
	                    <td><?php echo $tr->translate("INTEREST");?></td>
	                    <?php }?>
	                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
	                    <td><?php echo $tr->translate("SERVICE CHARGE");?></td>	
	                    <td><?php echo $tr->translate("TOTAL");?></td>
	                </tr>
                <?php $amt_r1 = 0; $amn_r2 = 0; $amn_r3 = 0;$amt_r4 = 0;$amn_r5 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
                	 $i=1;$oldloan_number='';
                	 $total_d=0;$total_b=0;$total_r=0;
                ?>
                <?php $is_set =0; if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
                
               <?php 
               $interest=0;
               ?>
               <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['principal_paid'];
		               		$amn_r2 = $amn_r2+$rs['interest_paid'];
		               		$amn_r3 = $amn_r3+$rs['penalize_paid'];
		               		$amn_r5 = $amn_r5+$rs['service_paid'];
		               		$total_r=$amt_r1+$amn_r2+$amn_r3+$amn_r5;
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['principal_paid'];
							$amt_d2 = $amt_d2+$rs['interest_paid'];
							$amt_d3 = $amt_d3+$rs['penalize_paid'];
							$amt_d5 = $amt_d5+$rs['service_paid'];;
							$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
		               }else{
		               		$amn_b1 = $amn_b1+$rs['principal_paid'];
							$amn_b2 = $amn_b2+$rs['interest_paid'];
							$amn_b3 = $amn_b3+$rs['penalize_paid'];
							$amn_b5 = $amn_b5+$rs['service_paid'];
							$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
		               }
               ?>
                <tr class="style style1" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>                 		
               		<td>&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['principal_paid'],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>               		
               		<?php if($level==1){?>
	               		<td align="center" style="font:bolder 11px Arial;">&nbsp;
	               		<?php echo number_format($rs['interest_paid'],2).' '.$rs['currency_typeshow'];?>
	               		&nbsp;</td>
               		<?php }?>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['penalize_paid'],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['service_paid'],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['total_paymentpaid'],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
               		<td style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_input"]));?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
               		<td style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo @$opt[$rs["payment_option"]];?>&nbsp;</td>
                </tr>
                <?php }?>
            </table>
             <strong style="font-family: 'Khmer OS Content';">តារាងចំណូល</strong> 
              <table  border="1"​ style="font-family: 'Khmer OS Content';border-collapse:collapse;border:1px solid #000; font-size:10px; white-space: nowrap;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; border:1px solid #000; line-height: 20px; font-size:10px; padding:5px 0px; ">
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DESCRIPTION");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CURRENT_TYPE");?></td>
					<td style="padding:5px 0px;"><?php echo $tr->translate("Invoice No.");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("​AMT_PAY");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DATE");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NOTE");?></td>
                </tr>
                <?php $amt_d = 0;$amt_b3 = 0;
                $total_rr=0;$total_dd=0;$total_bb=0;
                ?>
                <?php if(!empty($this->rsincome)) foreach ($this->rsincome as $key => $rs){ ?>
                <?php 
	                if($rs['curr_type']==1){
	                	$total_rr = $total_rr+$rs["total_amount"];
	                }elseif($rs['curr_type']==2){
	                	$total_dd = $total_dd+$rs["total_amount"];
	                }else{
	                	$total_bb = $total_bb+$rs["total_amount"];
	                }
               ?>
                <tr class="styleover">
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["account_id"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["currency_type"];?></td>
					<td >&nbsp;&nbsp;<?php echo $rs["invoice"];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["total_amount"],2);?></td>
               		<td >&nbsp;&nbsp;<?php echo date("d-M-Y",strtotime($rs["date"]));?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["disc"];?></td>
                </tr>
                <?php }?>
            </table><strong style="font-family: 'Khmer OS Content';">តារាងចំណាយ</strong>
              <table  border="1"​ style="border-collapse:collapse;border:1px solid #000;    font-family: 'Khmer OS Content' !important; font-size:10px; white-space: nowrap;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; border:1px solid #000; line-height: 20px; font-size:10px; padding:5px 0px; ">
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DESCRIPTION");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CURRENT_TYPE");?></td>
					<td style="padding:5px 0px;"><?php echo $tr->translate("Invoice No.");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("​AMT_PAY");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DATE");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NOTE");?></td>
                </tr>
                <?php $amt_r = 0;$amt_d = 0;$amt_b3 = 0;
                ?>
                <?php if(!empty($this->rsexpense)) foreach ($this->rsexpense as $key => $rs){ ?>
                <?php 
	                if($rs['curr_type']==1){
	                	$amt_r = $amt_r+$rs["total_amount"];
	                }elseif($rs['curr_type']==2){
	                	$amt_d = $amt_d+$rs["total_amount"];
	                }else{
	                	$amt_b3 = $amt_b3+$rs["total_amount"];
	                }
               ?>
                <tr class="styleover">
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["account_id"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["currency_type"];?></td>
					<td >&nbsp;&nbsp;<?php echo $rs["invoice"];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["total_amount"],2);?></td>
               		<td >&nbsp;&nbsp;<?php echo date("d-M-Y",strtotime($rs["date"]));?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["disc"];?></td>
                </tr>
                <?php }?>
            </table><br />
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td rowspan="2"><?php echo $tr->translate("CURRENT_TYPE");?></td>
                    <?php 
                        $colspan=3;
	                    if($level==1){$colspan=4;}?>
                    <td colspan="<?php echo $colspan;?>"><?php echo $tr->translate("ចំណូលពីការប្រមូលសរុប");?></td>
                    <th colspan="2"><?php echo $tr->translate("INCOME_FROMLOAN_DISBURSE");?></th>
                    <td rowspan="2"><?php echo $tr->translate("ចំណូល-ចំណាយ");?></td>
                    <td rowspan="2"><?php echo $tr->translate("TOTAL");?></td>
                </tr>
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate("ប្រាក់ដើម");?></td>
                    <?php if($level==1){?>
                    <td><?php echo $tr->translate("ប្រាក់ការសរុប");?></td>
                    <?php }?>
                    <td><?php echo $tr->translate("ប្រាក់ពិន័យសរុប");?></td>
                    <td align="center"><?php echo $tr->translate("ប្រាក់សន្សំ");?></td>	
                    <th><?php echo $tr->translate("AMIN_FEE");?></th>
                    <th><?php echo $tr->translate("OTHER_FEE");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <?php if($level==1){?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($saving_amountd,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_dd-$amt_d,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($saving_amountd+$d1+$d2+$total_d+$total_dd-$amt_d-$disburse_dollar,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <?php if($level==1){?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($saving_amountr,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_rr-$amt_r,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($saving_amountr+$r1+$r2+$total_r+$total_rr-$amt_r-$disburse_reil,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <?php if($level==1){?>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <?php }?>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($saving_amountb,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_bb-$amt_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($saving_amountb+$b1+$b2+$total_b+$total_bb-$amt_b3-$disburse_bath,2);?>&nbsp;</td>
                </tr>
              </table>
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>