<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$xchange= $this->Loanxchange_list;
$frm = $this->frm_search;
$client = $this->client;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("Report Transfer-Withdrawal");?></title>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content';width:28.2cm;margin:0 auto;" >
	<tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
        <td><?php echo $frm->getElement('status');?></td>
   		<td><?php echo $frm->getElement('currency_type');?></td>
   </tr>
   <tr>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   </tr>
</table>
</form>
<div style=" width:26cm;min-height:20cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	     <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Transfer-Withdrawal Report");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));?></li>
                		</ul>
                	</td>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 24px;font-size:10px; font-family: 'Khmer OS Content'">
                    <td ><?php echo $tr->translate("NUM");?></td>
                    <td ><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td ><?php echo $tr->translate("ឈ្មោះ​អ្នក​ផ្ញើរ");?></td>
                    <td ><?php echo $tr->translate("លេខអ្នកផ្ញើរ");?></td>
                    <td ><?php echo $tr->translate("លេខ​​​អ្នក​ទទួល");?></td>
                    <td ><?php echo $tr->translate("ប្រភេទ​ប្រតិបត្តិការណ៍");?></td>
                    <td ><?php echo $tr->translate("ប្រភេទ​ប្រាក់");?></td>
                    <td ><?php echo $tr->translate("ចំនួនទឺកប្រាក់");?></td>
                    <td ><?php echo $tr->translate("កម្រៃជើងសារ");?></td>
                    <td ><?php echo $tr->translate("កម្រៃជើងសារសរុប");?></td>
                    <td ><?php echo $tr->translate("ថ្ងៃ​ប្រតិបត្តិ");?></td>
                    
                </tr>
                <?php
					$commision_dollar=0;$commision_riel=0;
					$tcommision_dollar=0;$tcommision_riel=0;
					$tcommision_bath=0;$commision_bath=0;
					$dollar_transfer=0;$dollar_widthdraw=0;
					$riel_transfer=0;$riel_widthdraw=0;
					$bath_transfer=0;$bath_widthdraw=0;
					 $i=1;
                if(!empty($xchange))foreach ($xchange as $row){?>
               <tr style="font-size: 11px;" align="left">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<td>&nbsp;<?php ?></td>
               		<td>&nbsp;<?php echo $row['sender_name']?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['sender_tel']?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['reciever_tel'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['tran_type'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['currencty_type'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo number_format($row['amount_tranfer'],2);?>&nbsp;</td>
					<td>&nbsp;<?php echo number_format($row['commission'],3);?>&nbsp;</td>
					<td>&nbsp;<?php echo number_format($row['total_commission'],3);?>&nbsp;</td>
               		<td>&nbsp;<?php echo date('d-m-Y',strtotime($row['send_date']))?>&nbsp;</td>
               </tr>
               <?php 
               if($row['curr_type']==1){//kh
               		$commision_riel=$commision_riel+$row['commission'];
               		$tcommision_riel=$tcommision_riel+$row['total_commission'];
               		
               		if($row['transaction_type']==0){//transfer
               			$riel_transfer=$riel_transfer+$row['amount_tranfer'];
               		}else{//widthdraw
               			$riel_widthdraw=$riel_widthdraw+$row['amount_tranfer'];
               		}
               		
               }elseif($row['curr_type']==2){//dollar
               		$commision_dollar=$commision_dollar+$row['commission'];
               		$tcommision_dollar=$tcommision_dollar+$row['total_commission'];
               		
               		if($row['transaction_type']==0){//transfer
               			$dollar_transfer=$dollar_transfer+$row['amount_tranfer'];
               		}else{//widthdraw
               			$dollar_widthdraw=$dollar_widthdraw+$row['amount_tranfer'];
               		}
               		
			   }else{//bath
				   	$commision_bath=$commision_bath+$row['commission'];
				   	$tcommision_bath=$tcommision_bath+$row['total_commission'];
				   	
				   	if($row['transaction_type']==0){//transfer
				   		$bath_transfer=$bath_transfer+$row['amount_tranfer'];
				   	}else{//widthdraw
				   		$bath_widthdraw=$bath_widthdraw+$row['amount_tranfer'];
				   	}
			   }
              }
?>
            </table>
       		<br />
       		<table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;text-align:center;" width="100%" cellspacing="0">
                <tr​ bgcolor="#ccc" style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                	 <td align="center"><?php echo $tr->translate("CURRENT_TYPE");?></td>
                	 <td><?php echo $tr->translate("Transfer");?></td>
                	 <td><?php echo $tr->translate("Withdrawal");?></td>
                	 <td style=" border-right: 3px double #000;"><?php echo $tr->translate("កម្រៃជើងសារ");?></td>
                	 <td><?php echo $tr->translate("កម្រៃជើងសារសរុប");?></td>
                </tr>
                <tr style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <td><?php echo $tr->translate("DOLLAR");?></td>
                    <td><?php echo number_format($dollar_transfer,2);?></td>
                    <td><?php echo number_format($dollar_widthdraw,2);?></td>
                    <td><?php echo number_format($commision_dollar,2);?></td>
                    <td><?php echo number_format($tcommision_dollar,2);?></td>
                </tr>
                <tr style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <td><?php echo $tr->translate("REILS");?></td>
                    <td><?php echo number_format($riel_transfer,2);?></td>
                    <td><?php echo number_format($riel_widthdraw,2);?></td>
                    <td><?php echo number_format($commision_riel,2);?></td>
                    <td><?php echo number_format($tcommision_riel,2);?></td>
                </tr>
                <tr style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <td><?php echo $tr->translate("BATH");?></td>
                    <td><?php echo number_format($bath_transfer,2);?></td>
                    <td><?php echo number_format($bath_widthdraw,2);?></td>
                    <td><?php echo number_format($commision_bath,2)?></td>
                    <td><?php echo number_format($tcommision_bath,2);?></td>
                </tr>
              </table>
       		 <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>