<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$end_dat=$this->date_show;
	$session_user=new Zend_Session_Namespace('authloan');
	$level = $session_user->level;
	$dbloan  = new Report_Model_DbTable_DbLoan();
?>
<style>
.hover:hover{ background: #ccc;}
</style>
<title><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<div style="width:100%; margin:0 auto; clear:both;">
	<div style=" width:28cm;padding:0px 0.5cm">
		<form method="post">
			<table style="font-family: 'Khmer OS Content'; width:100%;" >
				  <tr>
			   			<td><?php echo $frm->getElement("advance_search");?></td>
			   			<td><?php echo $frm->getElement('branch_id');?></td>
			   			<td><?php echo $frm->getElement('client_name');?></td>
			   			<td><?php echo $frm->getElement('co_id');?></td>
			   	  </tr>
			   	 <tr>
			   	 		<td><?php echo $frm->getElement('paymnet_type');?></td>
			   			<td><?php echo $frm->getElement('start_date');?></td>
			   			<td><?php echo $frm->getElement('end_date');?></td>
			   			<td><?php echo $frm->getElement('status');?></td>
			   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			   	  </tr>
			</table>
		</form>
	</div>
</div>
<div style="width:100%; margin:0 auto; clear:both;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
                	 $co_id = null;
                ?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></li>
                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->start_date)){?><?php echo date("D-d-M-Y",strtotime($this->start_date)).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->date_show));}?></li>
                		</ul>
                	</td>
                    <td width="20%"></td>
                </tr> 
            </table>
        </td>
    </tr>
</table>
<div id="exportExcel">
<table  width="100%" border="1" style="border-collapse:collapse; border: 1px solid #000;" cellspacing="0">
		    <thead>
		        <tr class="style" bgcolor="#ccc" align="center" style="text-align:center;font-weight:bold; line-height: 24px; background:#ccd9ff;  font-size:12px; white-space: nowrap; ">
			     	 <th rowspan="2"><?php echo $tr->translate("NUM");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("LOAN_NO");?></th>	  
	                 <th rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></th>                  
	                 <th rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("INTEREST_RATE");?></th>
	                 <?php $colspan=5; ?>
	                 <th colspan="<?php echo $colspan;?>"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>    
	                 <th rowspan="2" style="white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></th>
	                 <th rowspan="2"><?php echo $tr->translate("BALANCE");?></th>
			   	</tr>
			   	<tr class="style"  bgcolor="#ccc" style="text-align:center;font-weight:bold; line-height: 24px; background:#ccd9ff;  font-size:12px; white-space: nowrap; ">
	                <td><?php echo $tr->translate("PRINCIPLE");?></td>                   
	                <td><?php echo $tr->translate("INTEREST");?></td>
	                <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
	                <td><?php echo $tr->translate("SERVICE CHARGE");?></td>
	                <td><?php echo $tr->translate("TOTAL");?></td>
	             </tr>
	        </thead>
	        <?php 
	        
	        	$coamt_r1 = 0;
	        	$coamt_r2 = 0;
	        	$coamt_r3 = 0;
	        	$coamt_r5 = 0;
	        	
	        	$coamt_d1 = 0;
	        	$coamt_d2 = 0;
	        	$coamt_d3 = 0;
	        	$coamt_d5 = 0;
	        	
	        	$coamn_b1 = 0;
	        	$coamn_b2 = 0;
	        	$coamn_b3 = 0;
	        	$coamn_b5 = 0;
	        	
	        	
	        	$cototal_b=0;
	        	$cototal_d=0;
	        	$cototal_r=0;
	        	
	        	$coaTotalWithdminfeer = 0;
	        	$coaTotalWithadminfeed = 0;
	        	$coaTotalWithadminfeeb = 0;
	        ?>
<?php 
$is_set =0 ;if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){?>
	<?php 
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['principal_paid'];
		               		$amt_r2 = $amt_r2+$rs['interest_paid'];
		               		$amt_r3 = $amt_r3+$rs['penalize_paid'];
		               		$amt_r5 = $amt_r5+$rs['service_paid'];
		               		$total_r=$amt_r1+$amt_r2+$amt_r3+$amt_r5;
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['principal_paid'];
							$amt_d2 = $amt_d2+$rs['interest_paid'];
							$amt_d3 = $amt_d3+$rs['penalize_paid'];
							$amt_d5 = $amt_d5+$rs['service_paid'];
							$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
		               }else{
		               		$amn_b1 = $amn_b1+$rs['penalize_paid'];
							$amn_b2 = $amn_b2+$rs['interest_paid'];
							$amn_b3 = $amn_b3+$rs['penalize_paid'];
							$amn_b5 = $amn_b5+$rs['service_paid'];
							$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
		               }
		               
               ?>
     <?php if($co_id!=$rs["co_id"]){
     	?>
     		 <?php if ($key>0){?>
     		 <?php $adminfeer = $dbloan->getAdminfeeloanByCO($co_id, 1, $this->search);
     		 		$adminfeed = $dbloan->getAdminfeeloanByCO($co_id, 2, $this->search);
     		 		$adminfeeb = $dbloan->getAdminfeeloanByCO($co_id, 3, $this->search);
     		 		
     		 		$totalwithAdminr = $cototal_r +$adminfeer['admin_fee'];
     		 		$totalwithAdmind = $cototal_d +$adminfeed['admin_fee'];
     		 		$totalwithAdminb = $cototal_b +$adminfeeb['admin_fee'];
     		 ?>
				<tr class="style hover" style="font-family: 'Khmer OS Content';white-space: nowrap;background: #cadee3;">
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php //echo $tr->translate("TOTAL");?>&nbsp;</td>
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("TOTAL_COLLECT");?>&nbsp;</td>
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("ADMIN_FEE");?>&nbsp;</td>
					<td colspan="9" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
				</tr>
				<tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_r,2)." ៛";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeer['admin_fee'],2)." ៛";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdminr,2)." ៛";?>&nbsp;</td>
                </tr>
               <tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_d,2)." $";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeed['admin_fee'],2)." $";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdmind,2)." $";?>&nbsp;</td>
                </tr>
                <tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2"  style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_b,2)." ฿";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeeb['admin_fee'],2)." ฿";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdminb,2)." ฿";?>&nbsp;</td>
                </tr>
                <tr >
					<td colspan="15" style=" border-left: solid 1px #fff; border-right: solid 1px #fff;">&nbsp;</td>
				</tr>
                 <?php 
		        	$coamt_r1 = 0;
		        	$coamt_r2 = 0;
		        	$coamt_r3 = 0;
		        	$coamt_r5 = 0;
		        	
		        	$coamt_d1 = 0;
		        	$coamt_d2 = 0;
		        	$coamt_d3 = 0;
		        	$coamt_d5 = 0;
		        	
		        	$coamn_b1 = 0;
		        	$coamn_b2 = 0;
		        	$coamn_b3 = 0;
		        	$coamn_b5 = 0;
		        ?>
				<?php }?>
				<tr>
					<td colspan="16" style="font-size: 12px;padding-left:4px; font-weight:500; background:#CADEE3;"><b><?php echo $rs["co_name"];?></b></td>
				</tr>
					<?php 
               } $co_id = $rs["co_id"];?>
			   	<tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
               		<td style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo $rs["branch"];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo $rs["client_code"];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo $rs["client_name"];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo $rs["interest_rate"];?></td>
               		<td style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($rs['principal_paid'],2).' '.$rs['currency_type'];?></td>  
               		<td style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($rs['interest_paid'],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo number_format($rs['penalize_paid'],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo number_format($rs['service_paid'],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 12px;padding:0px 2px;"><?php echo number_format($rs['total_paymentpaid'],2);?></td>
               		<td style="font-size: 12px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_payment"]));?></td>
               		<td style="font-size: 12px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_input"]));?></td>
               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
               		<td style="font:bolder 12px Arial;">&nbsp;<?php echo number_format(@$rs['total_payment']-@$rs['total_paymentpaid'],2);echo $rs['currency_type'];?>&nbsp;</td>
                </tr>
                <?php if($rs['curr_type']==1){
		               	$coamt_r1 = $coamt_r1+$rs['principal_paid'];
		               	$coamt_r2 = $coamt_r2+$rs['interest_paid'];
		               	$coamt_r3 = $coamt_r3+$rs['penalize_paid'];
		               	$coamt_r5 = $coamt_r5+$rs['service_paid'];
		               	$cototal_r=$coamt_r1+$coamt_r2+$coamt_r3+$coamt_r5;
		               	
		               }elseif($rs['curr_type']==2){
		               	$coamt_d1 = $coamt_d1+$rs['principal_paid'];
		               	$coamt_d2 = $coamt_d2+$rs['interest_paid'];
		               	$coamt_d3 = $coamt_d3+$rs['penalize_paid'];
		               	$coamt_d5 = $coamt_d5+$rs['service_paid'];
		               	$cototal_d=$coamt_d1+$coamt_d2+$coamt_d3+$coamt_d5;
		               	
		               }else{
		               	$coamn_b1 = $coamn_b1+$rs['penalize_paid'];
		               	$coamn_b2 = $coamn_b2+$rs['interest_paid'];
		               	$coamn_b3 = $coamn_b3+$rs['penalize_paid'];
		               	$coamn_b5 = $coamn_b5+$rs['service_paid'];
		               	$cototal_b=$coamn_b1+$coamn_b2+$coamn_b3+$coamn_b5;
		               	
		               }?>
               
<?php  }?>
<?php if (!empty($co_id)){?>
 			<?php 	$adminfeer = $dbloan->getAdminfeeloanByCO($co_id, 1, $this->search);
     		 		$adminfeed = $dbloan->getAdminfeeloanByCO($co_id, 2, $this->search);
     		 		$adminfeeb = $dbloan->getAdminfeeloanByCO($co_id, 3, $this->search);
     		 		$totalwithAdminr = $cototal_r +$adminfeer['admin_fee'];
     		 		$totalwithAdmind = $cototal_d +$adminfeed['admin_fee'];
     		 		$totalwithAdminb = $cototal_b +$adminfeeb['admin_fee'];
     		 ?>
				<tr class="style hover" style="font-family: 'Khmer OS Content';white-space: nowrap;background: #cadee3;">
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php //echo $tr->translate("TOTAL");?>&nbsp;</td>
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("TOTAL_COLLECT");?>&nbsp;</td>
					<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("ADMIN_FEE");?>&nbsp;</td>
					<td colspan="9" style="font-size: 12px;padding:0px 2px; font-weight: 700;">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
				</tr>
				<tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2" style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_r,2)." ៛";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeer['admin_fee'],2)." ៛";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdminr,2)." ៛";?>&nbsp;</td>
                </tr>
               <tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2"  style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_d,2)." $";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeed['admin_fee'],2)." $";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdmind['admin_fee'],2)." $";?>&nbsp;</td>
                </tr>
                <tr class="style hover" style="font-family: 'Khmer OS Content'; white-space: nowrap;">
                	<td colspan="2"  style="font-size: 12px;padding:0px 2px; font-weight: 700;" colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($cototal_b,2)." ฿";?>&nbsp;</td>
                	<td colspan="2" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($adminfeeb['admin_fee'],2)." ฿";?>&nbsp;</td>
                	<td colspan="9" style="font-size: 12px;padding:0px 2px;">&nbsp;<?php echo number_format($totalwithAdminb,2)." ฿";?>&nbsp;</td>
                </tr>
                <?php }?>
</table><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                <thead>
				<tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px;background:#ccd9ff;  text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <th style="font-size: 12px;">ប្រភេទប្រាក់</th>
                   <?php if($level==1){?>    
	                    <th><?php echo $tr->translate("PRINCIPAL");?></th>                    
	                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <?php }?>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
				</thead>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <?php }?>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <?php if($level==1){?>   
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <?php }?>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
              </table>
	            <br />
	            <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
		</table>
</div>
</div>
</div>
</div>
