<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('REPORT_LOAN_WRITE_OFF'));
 $frm = $this->frm_loan;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style=" width:34cm;margin:0 auto;" >
	<tr>
		<td><?php echo $frm->getElement('adv_search');?></td>
		<td><?php echo $frm->getElement('branch');?></td>
		<td><?php echo $frm->getElement('client_name');?></td>
		<td><?php echo $frm->getElement('co_id');?></td>
		<td><?php echo $frm->getElement('Term');?></td>
	</tr>
	<tr>
		<td><?php echo $frm->getElement('cash_type');?></td>
		<td><?php echo $frm->getElement('start_date');?></td>
		<td><?php echo $frm->getElement('end_date');?></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		<td><?php //echo $frm->getElement('status');?></td>
		<td></td>
	</tr>
</table>
</form>
<div style="width:100%; margin:0 auto;">
<div style=" width:34cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.25cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
.hover:hover{ background:#ccc;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<table width="100%" >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	    <ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_WRITE_OFF");?></li>
                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                    </td>
                    <td width="20%"></td>
                </tr> 
               
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
                <?php 
                	  $amt_r1 = 0;$amt_r2 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;
                	  $amn_b1 = 0; $amn_b2 = 0;
					  $co_id=0;
					  $count_d = 0;$count_r=0;$count_b=0;
					  $count_ld = 0;$count_lr=0;$count_lb=0;
					  $tcount_ld=0;$tcount_lr=0;$tcount_lb=0;
					  $amt_r = 0;$amt_d = 0;$amt_b = 0;
                ?>
                <?php $record = 0; if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php  if($co_id!=$rs['co_id']){ $record=0;
                if($key>0){
                ?>
                <thead>
                <tr class="style" align="center" style="floafont-weight:bold; background:#ccd9ff; line-height: 14px;font-size:10px; padding:5px 0px;">
					<th style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</th>
					<th style="padding:5px 0px;">&nbsp;​<?php echo $tr->translate("ចំនួនកម្ចី");?>&nbsp;</th>
					<th style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</th>
	            </tr>
	            </thead>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                    <td>&nbsp;<?php echo $count_ld;?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lr);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lb);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                </tr>
            </table>
                 <table width="100%" border="1" style="margin-top:5px;border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
                <?php } $count_ld=0;$count_lr=0;$count_lb=0; 
                $amt_r = 0;$amt_d = 0;$amt_b = 0;
                ?>
				<thead>
				<tr class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:10px; padding:10px 0px; ">
					<th colspan="15">&nbsp; ឈ្មោះមន្ត្រីឥណទាន <?php echo $rs['co_name']; ?></th>
				</tr>
				<tr class="style" align="center" style="font-weight:bold; line-height: 20px; background:#ccd9ff; font-size:10px; padding:10px 0px; ">
                    <th ><?php echo $tr->translate("NUM");?></th>
                    <th ><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th ><?php echo $tr->translate("LOAN_NO");?></th>
                    <th style="font-size: 10px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
					<th style="font-size: 10px;"><?php echo $tr->translate("PHONE");?> / <?php echo $tr->translate("ADDRESS");?></th> 
                    <th style="font-size: 10px;"><?php echo $tr->translate("LOAN_AMOUNT");?></th> 
                    <th style="font-size: 10px;"><?php echo $tr->translate("INTEREST_RATE");?></th>
                    <th style="font-size: 10px;"><?php echo $tr->translate("LOAN_PERIOD");?></th>
                    <th>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</th>
                    <th>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</th>
                    <th style="font-size: 10px;"><?php echo $tr->translate("ចំនួនប្រាក់ខូច");?></th> 
                    <th style="font-size: 10px;"><?php echo $tr->translate("TOTAL_INTEREST");?></th> 
                    <!--<th style="font-size: 10px;"><?php //echo $tr->translate("INTEREST_RECEIVEABLE");?></th>
                    <th style="font-size: 10px;"><?php //echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?></th>--> 
                    <th style="font-size: 10px;"><?php echo $tr->translate("LOSS_DATE");?></th>
                    <th style="font-size: 10px;"><?php echo $tr->translate("STATUS");?></th>
                </tr>
				</thead>
				<?php } $record  = $record +1; $co_id=$rs['co_id'];?>
                <?php 
                  if($rs["curr_type"]==1){//reil
                  	$amt_r1 = $amt_r1+$rs["total_amount"];
                  	$amt_r = $amt_r+$rs["total_amount"];
                  	$count_r=$count_r+1;
                  	$count_lr = $count_lr+1;
                  }elseif($rs["curr_type"]==2){
                  	$amt_d1 = $amt_d1+$rs["total_amount"];
                  	$amt_d = $amt_d+$rs["total_amount"];
                  	$count_d=$count_d+1;
                  	$count_ld = $count_ld+1;
                  }else{
                  	$amn_b1 = $amn_b1+$rs["total_amount"];
                  	$amt_b = $amt_b+$rs["total_amount"];
                  	$count_b=$count_b+1;
                  	$count_lb = $count_lb+1;
                  }
                ?>
                <tr class="style hover" style="font-family: 'Khmer OS Content'; line-height:15px; ">
               		<td style="font-size: 11px; text-align: center;">&nbsp;<?php echo $record; ?>&nbsp;</td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["client_number"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["client_name"];?></td>
               		<td style="font-size: 9px; max-width: 200px; white-space:normal;">&nbsp;&nbsp;<?php echo $rs["phone"];?><?php echo $rs['village_name'].",".$rs['village_name'].",".str_replace("Commune","",$rs['commune_name']).",".$rs['district_name'].",".$rs['province_en_name'];?></td>
					<td style="font:bolder 11px Arial ;text-align: center;​">&nbsp;&nbsp;<?php echo number_format($rs["loan_amount"],2).''.$rs['currency_type'];?></td>
               		<td style="font-size: 11px;text-align: center;">&nbsp;&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
               		<td style="font-size: 11px;text-align: center;">&nbsp;<?php echo $rs['total_duration'].$rs['termborrow'];//$rs['pay_term'];?>&nbsp;</td>
               		<td style="font-size: 11px;text-align: center; white-space:nowrap; ">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
               		<td style="font-size: 11px;text-align: center; white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
               		<td style="font:bolder 11px Arial ;text-align: center;background:#eeeeee;"><?php echo number_format($rs["total_amount"],2).''.$rs['currency_type'];?></td>
               		<td style="font:bolder 11px Arial ;text-align: center;background:#eeeeee;"><?php echo number_format($rs["interest_amount"],2).''.$rs['currency_type'];?></td>
               		<td>&nbsp;<?php echo date("d-m-Y",strtotime($rs["loss_date"]));?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo $rs["condition_term"];?></td>
                </tr>
                <?php }?>
				<thead>
                <tr class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; background:#ccd9ff;  padding:5px 0px;">
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</th>
	                    <th style="padding:5px 0px;">&nbsp;​<?php echo $tr->translate("ចំនួនកម្ចី");?>&nbsp;</th>
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbspthtd>
	            </tr>
				</thead>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
                    <td>&nbsp;<?php echo $count_ld;?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lr);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;<?php echo ($count_lb);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                </tr>
                 </table>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                 <thead>
				 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px;background: #ccd9ff; text-align: center;">
                    <th><?php echo $tr->translate("CURRENT_TYPE");?></th>
                    <th>&nbsp;<?php echo $tr->translate("ចំនួនឥណទាន");?></th>                 
                    <th><?php echo $tr->translate("TOTAL_PRINCEPLE");?></th>
                  <thead>  
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;<?php echo $count_d;?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;<?php echo $count_r;?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($count_b,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
<br />
<table align="center" width="100%">
	<thead>
	   <tr style="font-size: 12px;">
			<th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			<th></th>
			<th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			<th></th>
			<th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
	   </tr>
	</thead>
</table>
</div>
</div>
</div>