<?php $tran = $this->tran_schedule;
$client = $this->client;
$filter = $this->form_filter;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url_barcode = $this->url(array("module"=>"loan","controller"=>"ilpayment","action"=>"generatebarcode","loan_code"=>$client['loan_number']),null,true);																							

?>
<title><?php echo $tr->translate('REPORT WEEK');?></title>
<style>
td p{ margin-top:0px !important;}
</style>
<div style=" width:21cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
	<div id="divPrint">
	<style type="text/css">
	.style{
		line-height: 20px;font-size: 11px;
		font-family: 'Khmer OS Battambang';
	}
	.font_bold{
		font-family:'Khmer MEF2';
		font-size: 12px;
	}
	td p{ margin-top:-12px;}
	</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<?php // if($client['pay_term']==2){ ?>
					<?php //}else{?>
					<tr>
	                	  <td style="text-align: center;" valign="top"><img src="<?php echo $this->baseUrl();?>/images/letterhead.jpg" />  
	                	</td>
	                </tr>
	                <tr>
	                	<td colspan="3" align="center">
	                		<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><?php //echo $tr->translate('rpt-paymentschedule');?> <?php echo ($client['loan_type']==1)?$tr->translate('RPT_ILLOAN'):$tr->translate('RPT_GROULOAN') ;?></h2>
	               		</td>
	                </tr> 
					<?php //}?>
	                <?php $db = new Application_Model_DbTable_DbGlobal();
	                	  $row = $db->getClientByType(null,$client['client_id'],1);
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%" >
			                	<tr class='style'>
				                   <td width="35%">
				                   		<p> <?php echo "<strong>". $tr->translate('CLIENT_NO')."</strong> : ".$client['client_number']?></p>
				                	    <p><b><?php echo $tr->translate('CUSTOMER_NAME');?></b>: <?php echo ($client['displayclient']==1)? $client['client_name_kh']: $client['client_name_en'] ;?> </p>
				                	    
				                		<p><?php echo "<strong>",$tr->translate("TEL")."</strong>";?> : <?php echo $client['client_phone'];?></p>
				                		<p><b><?php echo $tr->translate("ADDRESS");?></b>:<?php echo $row['village_name'];?> ,<?php echo $row['commune_name'];?> <br /><?php echo $row['district_name'];?> ,  <?php echo $row['province_en_name'];?>
				                	</td>
				                    <td valign="top" style="" width="33%">
				                        
				                        <p><?php echo $tr->translate("សងរំលោះ");?> : <?php echo $client['total_duration']." ".Application_Model_DbTable_DbGlobal::getPaymentTermById($client['pay_term']); ?></p>
				                        <p><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម ");?> : <?php echo date('d-m-Y',strtotime($client['date_release']));?> </p>
				                    	<p><?php echo $tr->translate("FIRST_PAYMENT");?> : <?php echo date('d-m-Y',strtotime($client['first_payment'])); ?></p>
				                     </td>
				                    <td valign="top">
				                   	  <p><?php echo $tr->translate("LOAN_NO");?> : <b><?php echo $client['loan_number'];?></b></p>
				                      <p><?php //echo $tr->translate("INTEREST")." : ".$client['interest_rate']." %"?> </p>
				                      <p><?php echo $tr->translate("LOAN_AMOUNT");?>  : <?php echo number_format($client['total_capital'],(!strrpos($client['total_capital'],". "))? 0 : 2);echo '&nbsp;'.$client['currency_type'];?></p>
				                      <p><?php echo $tr->translate("LEVEL");?> : <?php echo $client['level'];?></p>
				                    </td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%">
	                 <tr class="style" align="center" style="font-weight:bold; line-height: 40px;">
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td><?php echo $tr->translate("DAY_PAYMENT");?></td>
	                    <td><?php echo $tr->translate("ថ្ងៃ-ខែ ឆ្នាំ");?></td>
	                    <td><?php echo $tr->translate("OS");?></td>
	                    <td><?php echo $tr->translate("AMOUNT");?></td>
	                    <?php if($client['pay_term']!=1){?>
	                    <td>បង់ផ្ដាច់ត្រូវពិន័យ</td>
	                    <?php }?>
	                    <td>អ្នកទទួល</td>
	                    <td><?php echo $tr->translate("OTHER");?></td>
	                </tr>
	               <?php 
	               $is_panelty=0;
	               if(!empty($tran)) foreach($tran as $key =>$row){?>
	               	<tr align="center" style="font-weight:bold; height: 20px;<?php if($key>0 AND $is_panelty==0 AND $row['penelize_service']<=0 AND $client['pay_term']!=1){echo'background:#b0d5f3';}?>" class="style">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    <td align="right">&nbsp;<?php echo $day_as_khmer.'-'.$str_day; ?>&nbsp;&nbsp;&nbsp;</td>
	                    <td align="center"><?php echo date('d-m-Y',strtotime($row['date_payment']));//echo$row['date_payment']?></td>
	                   <!--  <td><?php //echo $row['is_completed']?></td> 
	                    <td><?php //echo str_replace('.00', '', number_format($row['total_principal'],2));?></td>-->
	                    <!-- <td><?php //echo str_replace('.00', '', number_format($row['principal_permonth'],2));?></td> -->
	                    <!--<td><?php //echo str_replace('.00', '', number_format($row['total_interest'],2));?></td> -->
	                    <?php $remain = $row['total_principal']-$row['principal_permonth']
	                    ?>
	                    <td><?php echo number_format($remain,(!strrpos($remain,"."))? 0 : 2);?></td>
	                    
	                    <td ><?php echo str_replace('.00', '', number_format($row['total_payment'],2)); ?></td>
	                    <?php if($client['pay_term']!=1){?> <td><?php if($key>0 AND $is_panelty==0 AND $row['penelize_service']<=0){echo'fini';$is_panelty=1;}?><?php echo ($row['penelize_service']>0)?$row['penelize_service']:"";?></td><?php }?>
	                    <td></td>
	                    <td></td>
	                </tr>
	                
	               <?php }
	               	if(!empty($record))for($record = $key;$record<11;$record++){
	               ?>
	               		<tr>
	               			<td>&nbsp;</td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			 <?php if($client['pay_term']!=1){?><td></td><?php }?>
	               			<td></td>
	               			<td></td>
	               		</tr>
	               <?php }?>
	            </table>
	            <table>
	            	<tr>
	            		<td align="left" style="font-size: 12px;" ><u>បញ្ជាក់:</u> ការសងប្រាក់ប្រព្រឹត្តទៅតាមកិច្ចសន្យាខ្ចីប្រាក់និងតារាងសងប្រាក់នៅការិយាល័យរុងរឿងឫនៅផ្ទះអតិថិជន
	            		<p style="padding-top:10px;">លេខទូរស័ព្ទការិយាល័យ 096 9 595 201</p>
	            		</td>
	            	</tr>
	            </table>
	            <table width="100%" cellpadding="3">
	            	<tr class="font_bold" style="height:25px;">
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol'"><?php echo $tr->translate('ACCOUNTING_SIGN');?></td>
	            		<td align="center" valign="bottom"><?php echo $tr->translate('ភ្នាក់ងារឥណទាន'); ?></td> 
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol'"><?php echo $tr->translate('BORROWER');?></td>
	            	</tr>
	            	<tr class="font_bold">
	            		<td align="center" height="80px" valign="bottom"><?php echo $client['user_name'];?></td>
	            		<td align="center"  valign="bottom">
	            			<?php echo $client['co_khname'];?>
	            			<p><?php echo $tr->translate("TEL");?>  : <?php echo $client['tel'];?></p>   
	            		</td>
	            		<td align="center" height="75px" valign="bottom">
	            			<?php echo ($client['displayclient']==1)? $client['client_name_kh']: $client['client_name_en'] ;?></td>
	            	</tr>
	            </table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>