<?php 
$tran = $this->tran_schedule;
$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
$db = new Report_Model_DbTable_DbLoan();

$tran = $this->tran_schedule;
$client = $this->client;											
?>
<?php  
	$end_dat=$this->date_show;
?>
<?php 
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$key_code= $db_keycode->getSystemSetting(9);
	$free_day=$key_code['value'];
	
	$keyvalue = $db_keycode->getKeyCodeMiniInv();
	$interest_penalty = $keyvalue['interst_late'];
?>
<style>
.hover:hover{background: #ccc;}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
 <div style="height: auto; min-midth:29cm; margin: 0 auto;">
 <form method="post">
	<table width="100%">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	</form>
 </div>
<div style="min-width:33cm; min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 5px;">
	<div id="divPrint">
	<style>
.style{
	line-height: 20px;font-size: 13px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<div >
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></li>
                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("D-d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                    </td>
	                    <td width="20%"><strong style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label id="lbl_customer"></label></strong></td>
	                </tr>
	                <?php 
	                ?> 
	               
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%">
	             <thead>
	                 <tr class="style" align="center" bgcolor="#ccc" style="white-space: nowrap; background: #ccd9ff;">
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("NUM");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("LOAN_NO");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("PHONE")." / ".$tr->translate("ADDRESS");?></th>
	                    <!-- <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("RELEASE_DATE");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("LIFE_LOAN");?></th>
	                    <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("TOTAL_AMOUNT");?></th>
	                    <th rowspan="2" ><?php //echo $tr->translate("INTEREST RATE");?></th>
	                    <th rowspan="2" ><?php //echo $tr->translate("LOAN_PERIOD");?></th> 
	                    <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("PAY_DATE");?></th>-->
	                    <th rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("PAID_TIME");?></th>
	                    <th colspan="3" style="padding:0px 2px;"><?php echo $tr->translate("PAYMENT");?></th>
	                    <th rowspan="2" style="text-align:center ;padding:0px 2px;"><strong><?php echo $tr->translate("TOTAL_PAYMENT");?></strong></th>
	                    <th rowspan="2"><?php echo $tr->translate("LATE_DAY");?></th>
	                 ​​​	<th rowspan="2"><?php echo $tr->translate("LATE");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("PAY_DATE");?></th>
	                </tr>
	                <tr class="style" bgcolor="#ccc" style="white-space: nowrap; background: #ccd9ff;">
	                    <th style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("OS_AMOUNT");?></th>
	                    <th style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("INTEREST");?></th>
	                    <th  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
	                 </tr>
	               </thead> 
	                <?php 
	                $amt_r1 = 0;$tir = 0;
	                $amt_r2 = 0;
	                $amt_r3 = 0;
	                $amt_r4 = 0;
	                $amt_r5 = 0;
	                $total_r=0;
	                $amt_d1 = 0;$amt_d2 = 0;
	                $amt_d3 = 0;$amt_d4 = 0;
	                $amt_d5 = 0;$total_b=0;
	                $amn_b1 = 0;
	                $amn_b2 = 0;$amt_b1=0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
	                $saving_r=0;$saving_b=0;$saving_d=0;
	                $result=0;
	                ?>
	                <?php 
                     
                	 $amt_d1 = 0;$amt_d2 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; 
                	 $pene_amr=0; $pene_amb=0;$pene_amd=0;
                	 $serv_amr=0;$serv_amb=0;$serv_amd=0;
                	 $saving_r=0; $saving_b=0; $saving_d=0;
                	 $result=0;
                ?>
                <?php $i=1; $currentlate = 0;?>
               <?php if(!empty($this->loanlate_list))foreach ($this->loanlate_list as $index => $rs){ ?>
               		<?php $end_dat = $this->list_end_dates;
	               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
// 	               			if ($rs['last_pay_date']==null or $rs['last_pay_date']==""){
	               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
	               				$amount_lateday=$total_day/(60*60*24)-$free_day;
	               				$total_late_day=$total_day/(60*60*24);
// 	               			}else {
// 	               				$total_day=strtotime($end_dat)-strtotime($rs['last_pay_date']);
// 	               				$total_late_day=$total_day/(60*60*24);
// 	               				$amount_lateday=$total_day/(60*60*24);
// 	               			}
	               			$currentlate =$total_day/(60*60*24);
	               			$pay_term=$rs['collect_typeterm'];
	               			if($amount_lateday<0){
	               				$amount_lateday=0;
	               				$result=0;
	               			}
// 	               			else {
	               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
	               				if ($pay_term==1){
	               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/1)*($amount_lateday);
	               				}
	               				if ($pay_term==2){
	               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/7)*($amount_lateday);
	               				}
	               				if ($pay_term==3){
	               					$result=$total_pay*($interest_penalty*(($rs['interest_rate']/100)/30))*($amount_lateday);
	               				}
// 	               			}
	               			$penelize = $db->roundhundred($rs['penelize']+$result, $rs['curr_type']);
	               			$total_payment =$rs['principle_after']+$rs['total_interest_after'];
               			?>
               <?php //if($currentlate>0){?>
                <tr class="style hover" style=" line-height: 24px; font-size:11px; font-family: 'Khmer OS Content'; white-space: nowrap;">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["phone"].",".$rs['village_name'].",".str_replace("Commune","",$rs['commune_name']).",".$rs['district_name'].",".$rs['province_en_name'];?>&nbsp;</td>
               		<!-- <td align="right" style="white-space: nowrap;">&nbsp;<?php //echo date("d/m/Y",strtotime($rs["date_release"]));?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php //echo number_format($rs["total_capital"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td>&nbsp;<?php //echo $rs["interest_rate"];?>&nbsp;</td>
               		<td>&nbsp;<?php //echo $rs["total_duration"]." ".$rs["Term Borrow"];?>&nbsp;</td> -->
               		<td align="center">&nbsp;&nbsp;<?php echo $rs['times']."/".$rs['total_duration'];?> &nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
               		<td align="right" style="white-space: nowrap;">&nbsp;<?php //echo $penelize.' '.$rs['currency_type'];?>&nbsp;</td> 
               		<td align="right" style="white-space: nowrap;"><strong style="font-family:'arial';">&nbsp;<?php echo number_format($total_payment,2).' '.$rs['currency_type'];?></strong>&nbsp;</td>
               		<td align="center">&nbsp;&nbsp;<?php echo number_format($total_late_day,0)." Days";?> &nbsp;</td>
               		<td align="center">&nbsp;&nbsp;<?php echo $rs["amount_late"]." ដង";?> &nbsp;</td>
               		
               		<td align="center">&nbsp;&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
                </tr>
                <?php //}?>
                <?php 
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['principle_after'];
		               		$amt_r3 = $amt_r3+$rs['total_interest_after'];
		               		$pene_amr=$pene_amr+$penelize;
		               		$amt_r4 = $amt_r4+$total_payment;
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['principle_after'];
							$amt_d3 = $amt_d3+$rs['total_interest_after'];
							$pene_amd=$pene_amd+$penelize;
							$amt_d4 = $amt_d4+$total_payment;
		               }else{
							$amt_b1 = $amt_b1+$rs['principle_after'];
							$amn_b3 = $amn_b3+$rs['total_interest_after'];
							$pene_amb= $pene_amb+$penelize;
							$amn_b4 = $amn_b4+$total_payment;
		               }
		               $amount_days = strtotime($this->list_end_dates)-strtotime($rs["date_payment"]);
		               $amount_days =  floor($amount_days/(60*60*24));
               ?>
                <?php }?>
	            </table>
	           
	    	</td>
	    </tr>
	</table>
	<table width="100%">
		<tr>
    	<td style="font-family:'khmer os battambang';">
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">				 
				 <thead>
				 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; background: #ccd9ff; font-size:9px;font-family: 'Khmer OS Content';">
                     <th><?php echo $tr->translate('CURRENT_TYPE');?></th>    
                    <th><?php echo $tr->translate("TOTAL_PRINCIPLE");?></th>
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <!-- <th><?php //echo $tr->translate("PENALIZE AMOUNT");?></th>-->
                    <th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
                </tr>
				</thead>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <!--<td>&nbsp;&nbsp;<?php echo number_format($pene_amd,2);?>&nbsp;</td> -->
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <!--<td>&nbsp;&nbsp;<?php //echo number_format($pene_amr,2);?>&nbsp;</td>-->
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amt_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                    <!--<td>&nbsp;&nbsp;<?php echo number_format($pene_amb,2);?>&nbsp;</td>-->
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                </tr>
              </table> 
               <table align="center" width="100%">
			   <thead>
				   <tr style="font-size: 14px;">
			        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
				</thead>
			</table>
    	</td>
    </tr>
</table>
</div>
<script>
dojo.require("dojo.html");
	dojo.ready(function(){		
		co_id = dijit.byId('co_id').get('value');
		if(co_id>0){
			document.getElementById('lbl_customer').innerHTML=dijit.byId('co_id').attr('displayedValue');;
		}
	});
function popupCheckCO(){
}
</script>