<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LIST_LOAN_INCOME"));
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-expense')); ?>" dojoType="dijit.form.Form" method="post">
  <table style=" width:28.5cm;margin:0 auto; padding:0px">
   <tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
        <td><?php echo $frm->getElement('status');?></td>
   		<td><?php echo $frm->getElement('currency_type');?></td>
   </tr>
   <tr>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   </tr>
</table>
</form>

<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
.styleover:hover{ background: #ccc; }
table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}

table { page-break-inside:auto }
  tr{ page-break-inside:avoid; page-break-after:auto; }
#header {
  display: table-header-group;
  page-break-inside:avoid; page-break-after:auto;
}

</style>
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_EXPENSE");?></li>
                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
                		</ul>
                </td>
                    <td width="20%"></td>
                </tr> 
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel">
            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px; white-space: nowrap;" width="100%" cellspacing="0">
                 <thead>
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; border:1px solid #000; background:#ccd9ff; line-height: 20px; font-size:10px; padding:5px 0px; ">
                    <th style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("DESCRIPTION");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("CURRENT_TYPE");?></th>
					<th style="padding:5px 0px;"><?php echo $tr->translate("INVOICE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("TOTAL_EXPENSE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("DATE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("NOTE");?></th>
                </tr>
                </thead>
                <?php $amt_r = 0;$amt_d = 0;$amt_b3 = 0;
                ?>
                <?php if(!empty($this->rs)) foreach ($this->rs as $key => $rs){ ?>
                <?php 
	                if($rs['curr_type']==1){
	                	$amt_r = $amt_r+$rs["total_amount"];
	                }elseif($rs['curr_type']==2){
	                	$amt_d = $amt_d+$rs["total_amount"];
	                }else{
	                	$amt_b3 = $amt_b3+$rs["total_amount"];
	                }
               ?>
                <tr class="styleover">
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["account_id"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["currency_type"];?></td>
					<td >&nbsp;&nbsp;<?php echo $rs["invoice"];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["total_amount"],2);?></td>
               		<td >&nbsp;&nbsp;<?php echo date("d-M-Y",strtotime($rs["date"]));?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["disc"];?></td>
                </tr>
                <?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                <thead>
				<tr bgcolor="#ccc" style="font-weight:bold; background:#ccd9ff;  line-height: 30px; font-size:14px; padding:5px 0px; ">
                    <th align="center"><?php echo $tr->translate("DOLLAR");?></th>
                    <th align="center"><?php echo $tr->translate("REILS");?></th>
                    <th align="center"><?php echo $tr->translate("BATH");?></th>
                </tr>
				</thead>
                 <tr style="font-weight:bold; line-height: 30px; font-size:14px; padding:5px 0px; ">
                    <td align="center"><?php echo number_format($amt_d,2);?></td>
                    <td align="center"><?php echo number_format($amt_r,2);?></td>
                    <td align="center"><?php echo number_format($amt_b3,2);?></td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
<br />
 <table align="center" width="100%">
			<thead>
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			  </thead>
		</table>
</div>
</div>
</div>
