<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:128px !important;} 
.tds{width:114px !important;}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				 
				dijit.byId("save_close").set("disabled",true);
				dijit.byId("save_new").set("disabled",true);
				return true;
			}else {
               
				return false;
			}
</script>
<fieldset>
<table cellspacing="10" class='fullside'>
		 <legend><strong>Form Add Interest</strong></legend>
	<tr><td colspan="4" bgcolor="#dbe7ff">តារាងអាត្រាការប្រាក់</td></tr>
	<tr>
		<td width="25%;" valign="top">
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td class="tds">Interest Label 1</td>
							<td><?php echo $frm->getElement('inter_one')?></td>
						</tr>
						<tr>
							<td class="tds">Interest Value 1</td>
							<td><?php echo $frm->getElement('interest1')?></td>
						</tr>
				</table>
		</td>
		<td width="25%;" valign="top">
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							 <td class="tds">Interest Label 2</td>
							<td><?php echo $frm->getElement('inter_two')?></td>
						</tr>
						<tr>
							<td class="tds">Interest Value 2</td>
							<td><?php echo $frm->getElement('interest2')?></td>
						</tr>
				</table>
		</td>
		<td width="25%;" valign="top">
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td class="tds">Interest Label 3</td>	
							<td><?php echo $frm->getElement('inter_three')?></td>
						</tr>
						<tr>
							<td class="tds">Interest Value 3</td>	
							<td><?php echo $frm->getElement('interest3')?></td>
						</tr>
				</table>
		</td>
		<td width="25%;" valign="top">
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td class="tds">Interest Label 4</td>
							<td><?php echo $frm->getElement('inter_four')?></td>
						</tr>
						<tr>
							<td class="tds">Interest Value 4</td>
							<td><?php echo $frm->getElement('interest4')?></td>
						</tr>
				</table>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="4">
			<input type="reset" label="សម្អាត" dojoType="dijit.form.Button" 
			 iconClass="dijitIconClear" /> 
			<input type="button" onclick="submitDataClose()" value="បិទ" label="រក្សាទុកបិទ" name="save_close" id="save_close" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<input type="submit" value="រក្សាទុកថ្មី" label="រក្សាទុកថ្មី" name="save_new" id="save_new" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	dijit.byId('dollar_current').set('readOnly',true);
	dijit.byId('bath_current').set('readOnly',true);
	dijit.byId('reil_current').set('readOnly',true);
});

var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capitaltransfer','action'=>'getamountbybranceid'));?>'; 
function getAmounts(){
	var brance_id = dijit.byId('brance').get('value');
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance').get('value'),
		},	
		handleAs:"json",
		load: function(respone) {
			for(i=0;i<respone.length;i++){
				if(respone[i].account_id==1){
					dijit.byId('dollar_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bath_current').attr('value',respone[i].amount_bath);
					dijit.byId('reil_current').attr('value',respone[i].amount_riel);
				}else{
					dijit.byId('dollarbank_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bathbank_current').attr('value',respone[i].amount_bath);
					dijit.byId('reilbank_current').attr('value',respone[i].amount_riel);
					}
		   }
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function statusCheck(){
	var status = dijit.byId('status').get('value');
	if(status == -1){
		alert("សូមមេត្តាជ្រើសរើសស្ថានភាពយ៉ាងហោចមួយ!!");
	}
}

function submitDataClose(){
	if(dijit.byId('frm_add').validate()) {
		dijit.byId("save_close").set("disabled",true);
		dijit.byId("save_new").set("disabled",true);
		var url_submit = '<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/capital/interest";
			},
			error: function(e) {
			}
		});
	}
}

</script>
