<?php
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();	
    echo $this->headTitle($tr->translate('TRANSFER_CLIENT_CO')); 
	$frm = $this->frm_transfer;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoclient','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
   if(this.validate()) {
    if(dijit.byId('branch_name').get('value')==''){
     alert('Please Select Branch');
     dijit.byId('branch_name').focus();
     return false;
   	}
    if(dijit.byId('name_co').get('value')==''){
     alert('Please Select Name Co');
     dijit.byId('name_co').focus();
     return false;
   	}
	if(dijit.byId('customer_code').get('value')==''){
     alert('Please Select Customer Code');
     dijit.byId('customer_code').focus();
     return false;
   	}
	if(dijit.byId('member').get('value')==''){
     alert('Please Select Customer Name');
     dijit.byId('member').focus();
     return false;
   	}
    return true;
   }else {
    return false;
   }
</script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<fieldset style="background: #e0ebff">
<table cellspacing="10" class='fullside'>
	<legend class="mainblog" align="center"><strong><?php echo $tr->translate('EDIT_TRANSFER_CLIENT_CO');?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('CUSTOMER_INFO');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr >
					<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
					<td><?php  echo $frm->getElement('customer_code');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
					<td><?php  echo $frm->getElement('member');?></td>
				</tr>
				<tr>
			    	 <td><?php echo $tr->translate("NOTE")?></td>
					 <td><?php  echo $frm->getElement('Note');?></td>
			    </tr>
			</table>
		 </fieldset>
		</td>
		<td width="33%;" valign="top">
		 <fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
					<td><?php echo $tr->translate("BRANCH_NAME")?></td>
					<td><?php  echo $frm->getElement('branch_name');?></td>
			    </tr>
			    <tr>
			  		<td><?php echo $tr->translate("TO_CO")?></td>
					<td><?php  echo $frm->getElement('name_co');?></td>
			    </tr>
			    <tr>
					 <td><?php echo $tr->translate("DATE")?></td>
					 <td><?php  echo $frm->getElement('Date');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("STATUS")?></td>
					<td><?php  echo $frm->getElement('status');?></td>
			    </tr>
			</table>	
		  </fieldset>
		</td>
	</tr>
		<tr>
		<td align="center" colspan="2">
			<input type="submit" value="រក្សាទុក" name="btn_save" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("member").get('value');
			dijit.byId("customer_code").attr('value',id);
		}else if(type==2){
			id = dijit.byId("customer_code").get('value');
			dijit.byId("member").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("name_client").get('value');		
			dijit.byId("code_client").attr('value',to);
			dijit.byId("name_client").attr('value',to);
		}else if(type==4){
			to = dijit.byId("code_client").get('value');
			dijit.byId("code_client").attr('value',to);
			dijit.byId("name_client").attr('value',to);
		}
	}
</script>
