<?php
	$this->headTitle('Add IL Payment'); 
	echo $this->headTitle();
	$frm = $this->frm_ilpayment;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$graiceperiod = $this->graiceperiod;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog",
		         "dijit/layout/TabContainer"]);
		dojo.require("dojo.NodeList-manipulate");
		dojo.require("dojo.html");
	    dojo.require("dojo.data.ItemFileWriteStore"); 
		dojo.require("dojo.data.ObjectStore");
   </script>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<form id='frm_add_group_pay' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'payment','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
				receive_amount = dijit.byId('amount_receive').get('value');
				option_pay = dijit.byId('option_pay').get('value');
				total_payments = dijit.byId('total_payment').get('value');
                os = dijit.byId('os_amount').get('value');
			if(option_pay==1){
					if(receive_amount<os){
						alert('Payoff Payment Must Biger Than Principal Amount!');
						dijit.byId('amount_receive').focus();
						return false;
					}
				}
			if(receive_amount<0){
					alert('Please fill Recieve Amount');
					dijit.byId('amount_receive').focus();
					return false;
			}
			client = dijit.byId('client_id').get('value');
           	branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('client_id').focus();
				return false;
			}
			dijit.byId('submitButton').set('disabled',true); 
      		dijit.byId('submit_close').set('disabled',true);
			return true;
		}else {
			return false;
		}
</script>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.center tr{text-align:left;}
</style>
<table width="100%" >
	<tr>
		<td>
				<fieldset style="margin-top:0px">
					<legend><strong>ព៌ត័មាន បង់រំលោះទ្រពដាក់បញ្ចាំ</strong></legend>
	
					<table class="center" cellspacing="2" >
						<tr>
							<td width="144"><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td width="210"><?php echo $frm->getElement('branch_id');?></td>
							<td width="144"><?php echo $tr->translate("TOTAL_AMOUNT")?></td>
							<td width="210"><?php echo $frm->getElement('total_amount_loan');?> </td>
							<td width="144"><?php echo $tr->translate('START_DATE');?></td>
							<td width="210"><?php echo $frm->getElement('start_date');?></td>
						</tr>                        
                       
                       <tr>
							<td><?php echo $tr->translate("PAWN_CODE")?></td>
							<td><?php //echo $frm->getElement('loan_number');?><input dojoType="dijit.form.TextBox" class="fullside" id="pawn_number" name="pawn_number" type="hidden"><input id="loan_number" /> </td>
          					<td><?php echo $tr->translate("CURRENCY")?></td>
							<td><?php echo $frm->getElement('currency_type');?> </td>                            
							<td><?php echo $tr->translate('END_DATE');?></td>
							<td><?php  echo $frm->getElement('end_date');?></td>                            
						</tr>
                        
                        
					  <tr>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><?php //echo $frm->getElement('client_code');?><input id="client_id"></td>
							<td><?php echo $tr->translate("TERM_CODITION")?></td>
							<td><?php echo $frm->getElement('payment_term');?></td>
							<td><?php echo $tr->translate("ប្រភេទ​​ទ្រព្យដាក់បញ្ចាំ")?></td>
							<td><?php echo $frm->getElement('product_id');?></td>
						</tr>
                        
                   		<tr>                        
                    		<td><?php echo $tr->translate("CLIENT_NUM")?></td>
							<td><?php //echo $frm->getElement('client_code');?> <input id="client_code"></td>
                        	<td><?php echo $tr->translate("INTEREST_RATE")?></td>
							<td><?php  echo $frm->getElement('interest_rate');?></td>						
							<td></td>
							<td></td>
						</tr>
                          <tr>                                
                            <td><?php echo $tr->translate("LOAN_DATE")?></td>
							<td><?php echo $frm->getElement('release_date');echo $frm->getElement('old_release_date');?></td>
                           	<td><?php echo $tr->translate("LOAN_PERIOD")?></td>
							<td><?php echo $frm->getElement('loan_period');?></td>                            
							<td></td>
							<td></td>					
						
						</tr>    
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc; text-align:left;"><strong><?php echo $tr->translate("ព៌ត័មាន ពីការបង់ប្រាក់")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("COLLECT_DATE");?></td>
							<td><?php echo $frm->getElement('collect_date');?></td>							
							<td><?php echo $tr->translate("RECIEPT_NO")?></td>
							<td><?php echo $frm->getElement('reciept_no');?></td>
                            <td colspan="2"><?php echo $tr->translate("NOTE")?></td>						
						</tr>
                        <tr>
							<td><?php echo $tr->translate("TOTAL_PRINCIPLE")?></td>
							<td><?php echo $frm->getElement('os_amount');?></td>							
							<td>ប្រាក់រំលស់ដើម</td>
							<td><?php echo $frm->getElement('rapture_amount');?></td>
                            <td colspan="2" rowspan="5" style="    vertical-align: top;"><?php echo $frm->getElement('note');?></td>
						</tr>                        
                        <tr>
							<td><?php echo $tr->translate("PAYMENT_OPTION")?></td>
							<td><?php  echo $frm->getElement('option_pay');?></td>  							
							<td style="color:red;"><?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT")?></td>
							<td style="font-weight: bold;"><?php echo $frm->getElement('total_payment');?><input type="hidden" dojoType="dijit.form.TextBox" name="oldTotalPay" id="oldTotalPay" /></td>
						</tr>
                          	<tr>
							<td><?php echo $tr->translate("TOTAL_INTEREST")?></td>
							<td><?php echo $frm->getElement('total_interest');?></td>							
							<td style="color:red;"><?php echo $tr->translate("TOTAL_RECIEPT")?></td>
							<td style="font-weight: bold;"><?php echo $frm->getElement('amount_receive');?></td>
						</tr>
                        <tr>
							<td><?php echo $tr->translate("TOTAL_PENELIZE")?></td>
							<td><?php echo $frm->getElement('penalize_amount');?><?php echo $frm->getElement('old_penelize');?><input type="hidden" name="new_penelize" id="new_penelize"></td>
							<td><?php echo $tr->translate("RETURN_AMOUNT")?></td>
							<td><?php  echo $frm->getElement('amount_return');?></td>                          
						</tr>
                        <tr>
							<td><?php echo $tr->translate("SERVICE CHARGE")?></td>
							<td align="left"><?php echo $frm->getElement('more_interest');?></td>						<td><?php echo $tr->translate("REMAIN")?></td>
							<td><?php echo $frm->getElement('remain');?></td>
						<tr>
							<td></td>
							<td></td>
							<td><?php echo $frm->getElement('installment_date');?></td>
							<td><?php echo $frm->getElement('amount_payment_term');?></td>
							<td></td>
							<td></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
			<td align="center">
			  <input type="submit" value="រក្សាទុក & បិទ" label="<?php echo $tr->translate('SAVECLOSE');?>" name="saveclose" id="submit_close" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave"  />
			    <input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave" />
			</td>
		</tr>
		
</table>

<input type="hidden" dojoType="dijit.form.TextBox" name="identity" id="identity">
<input type="hidden" dojoType="dijit.form.TextBox" name="curr" id="curr">

</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បោះពុម្ភ វិក័យបត្រ', onCancel:hideDialog" id="frm_client" style="width:25cm">
	<div id="rpt_print" class="print" style="padding: 0; width:25cm;">
	<style type="text/css">
		td.border {
			border-bottom: 1px dotted #1D1D1D;
			border-top: none;
			border-left: none;
			border-right: none;
			padding:0;
			margin:0;
		}
         table table tr td ul li{text-align: center;list-style: none;line-height: 20px; font-weight: bold;}
	</style>
		<table cellpadding="0" cellspacing="0" style="width:25cm;max-height:14.85cm; white-space:nowrap; font-family:'Khmer OS Battambang'; font-size: 10px;margin:-8px -20px -8px -8px;">
				 <tr valign="top">
					<td align="center" colspan="6" valign="top" height="80">	
						   <table  cellpadding="0" cellspacing="0" style="font-family: 'Khmer OS Battambang';padding:0; width:100%;background:rgb(85, 85, 174) none repeat scroll 0% 0% ;white-space:nowrap;">
						   		<tr style="line-height:10px;">
						   			<td width="28%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px" style="padding-left: 8px;"></td>
						   			<td valign="top" style="color: #fff;">
							   			<ul style="padding-top: 5px;">
				                			<li style="text-align:center; font-size:16px !important; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
				                			<li style="text-align:center; font-size:14px !important; font-family:'Khmer MEF2'"><?php echo $tr->translate("PAYMENT_RECEIPT");?></li>
				                			<li style="text-align:center; font-size:12px !important;font-family:sans-serif; font-weight: bold;">PAYMENT RECEIPT</li>
				                		</ul>
					                </td>
					                <td width="28%">
					                </td>
					               <td>
					               </td>
								</tr>
								<tr>
	                			<td colspan="3">
			                    </td>
			                   </tr>  
					</table>
				</td>
		    </tr> 
		    <tr>
		    		<td align="center" colspan="6" valign="top" height="80">	
					   <table  cellpadding="0" cellspacing="0" style="font-family: 'Khmer OS Battambang' ;font-size:12px !important;white-space:nowrap; width:24cm; margin: 0 auto;">
							<tr class="fontsize">
									<td class="fontsize" valign="top"></td>
									<td width="17%"></td>
									<td></td>
									<td width="17%"></td>
									<td><span style="font-family:'Khmer MEF2'">កាលបរិច្ឆេទ</span><div class="height">Date</div></td>
									<td class="border" width="17%"><strong class="fonttel" style="font-size:12px;"><?php echo date('d/m/Y H:i:s');?></strong></td>
							</tr>
							<tr class="fontsize">
									<td class="fontsize" valign="top" width="17%"></td>
									<td></td>
									<td></td>
									<td></td>
									<td><span style="font-family:'Khmer MEF2'">បង្កាន់ដៃលេខ</span><div class="height">Receipt N<super>o</super></div></td>
									<td class="border"><strong class="fonttel" style="font-size:12px;"><label style="color:rgb(89, 89, 167)" id="lbl_reciept_no"></label></strong></td>
							</tr>
							<tr class="fontsize">
									<td class="fontsize" valign="top" width="17%">សាខា <div class="height">Branch Name</div></td>
									<td class="border"><label id="lbl_branch_id"></label></td>
									<td>លេខឥណទាន<div class="height">Loan Number</div></td>
									<td class="border">
										<strong class="fonttel" style="font-size:12px;"><label style="color:rgb(89, 89, 167)" id="lbl_loan_number"></label></strong>
									</td>
									<td>ឈ្មោះអតិថិជន<div class="height">Client's Name</div></td>
									<td class="border"><label id="lbl_group_member"></label></td>
							</tr>
							<tr class="fontsize">
									<td>ប្រាក់ដើមគ្រានៅសល់ <div class="height">Principal​ Remain</div></td>
									<td class="border"><label style="color:red" id="lbl_priciple_amount"></label></td>
									<td>ប្រាក់ដើម ត្រូវបង់<div class="height">Principal​ Amount</div></td>
									<td class="border"><label style="color:red" id="lbl_os_amount"></label></td>
									<td>ការប្រាក់<div class="height">Interest Amount</div></td>
									<td class="border"><label id="lbl_total_interest"></label></td>
							</tr>
							<tr class="fontsize">
									<td>ប្រាក់ផាកពិន័យ <div class="height">Penalty</div></td>
									<td class="border"><label style="color:red" id="lbl_penalize_amount"></label></td>
									<td>ថ្លៃសេវា<div class="height">Service Charge</div></td>
									<td class="border"><label style="color:red" id="lbl_service_charge"></label></td>
									<td>ចំនួនប្រាក់ត្រូវបង់សរុប<div class="height">Payment Amount</div></td>
									<td class="border"><label style="color:red" id="lbl_total_payment"></label></td>
							</tr>
							<tr class="fontsize">
									<td>ថ្ងៃបានបង់ប្រាក់<div class="height">Payment Date</div></td>
									<td class="border"><label style="color:red" id="lbl_collect_date"></label></td>					
									<td>ប្រាក់បានទទួល<div class="height">Receive Amount</div></td>
									<td class="border"><label style="color:red" id="lbl_amount_receive"></label></td>
									<td>ប្រាក់អាប់<div class="height">Return Amount</div> </td>
									<td class="border"><label style="color:red" id="lbl_amount_return"></label></td>
							</tr>
							<tr class="fontsize">
									<td>ឈ្មោះមន្រ្តីឥណទាន<div class="height">CO Name</div></td>
									<td class="border"><label id="lbl_co_id"></label></td>
									<td>សំគាល់<div class="height">Note</div></td>
									<td colspan="3"><label id="lbl_note"></label></td>
							</tr >
							<tr class="fontsize">
									<td colspan="3" align="center" style="padding-top:25px;font-family:'Khmer MEF2'">បេឡាករ<div class="height">Cashier</div></td>
									<td colspan="3" align="center" style="padding-top:25px;font-family:'Khmer MEF2'">ហត្ថលេខា និងឈ្មោះអតិថិជន<div class="height">Customer's signature& full name</div></td>
							</tr>
							<tr class="fontsize" style="margin-top:20px;line-height: 20px">
									<td colspan="3" align="center">
										<strong class="fonttel" style="font-size:10px;"><?php //print($this->user_name);?></strong>
									</td>
									<td colspan="3" align="center"></td>
							</tr>
						</table>
					</td>
				</tr>
		</table>
		</div>
		<input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" 
				   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="print();"/>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>

<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script type="text/javascript">
function submitDataClose(){
	var url_submit = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'payment','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_group_pay"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/pawnshop/payment";
			},
			error: function(e) {
			}
		});
}
function submitData(){
	var url_submit = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'payment','action'=>'add')); ?>';
	loading();
	dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_group_pay"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/pawnshop/payment/add";
			},
			error: function(e) {
				//alert("Your message could not be sent, please try again!.");
			}
		});
}
function showReciept(){
	var client_id = dijit.byId('client_id').get('value');
	if(client_id==""){
		alert("No Result To Show! Please Choose Client and Try again");
	}else{
		curr_type = dijit.byId('currency_type').get('value');
		if(curr_type==1){
			symbal =" ៛";
		}else if(curr_type==2){
			symbal =" $";
		}else{
			symbal =" B";
		}
		document.getElementById('lbl_group_member').innerHTML = dijit.byId('client_id').attr('displayedValue');
		document.getElementById('lbl_reciept_no').innerHTML = dijit.byId('reciept_no').attr('displayedValue');
		document.getElementById('lbl_loan_number').innerHTML = dijit.byId('loan_number').attr('displayedValue');
		document.getElementById('lbl_branch_id').innerHTML = dijit.byId('branch_id').attr('displayedValue');
		document.getElementById('lbl_co_id').innerHTML = dijit.byId('co_id').attr('displayedValue');
		document.getElementById('lbl_collect_date').innerHTML = dijit.byId('collect_date').attr('displayedValue');
		document.getElementById('lbl_priciple_amount').innerHTML = dijit.byId('priciple_amount').attr('displayedValue')+symbal;
		document.getElementById('lbl_os_amount').innerHTML = dijit.byId('os_amount').attr('displayedValue')+symbal;
		document.getElementById('lbl_total_interest').innerHTML = dijit.byId('total_interest').attr('displayedValue')+symbal;
	 	document.getElementById('lbl_penalize_amount').innerHTML = dijit.byId('penalize_amount').attr('displayedValue')+symbal;
	 	document.getElementById('lbl_total_payment').innerHTML = dijit.byId('total_payment').attr('displayedValue')+symbal;
	 	document.getElementById('lbl_note').innerHTML = dijit.byId('note').attr('displayedValue');
	 	document.getElementById('lbl_amount_receive').innerHTML = dijit.byId('amount_receive').attr('displayedValue')+symbal;
	 	document.getElementById('lbl_amount_return').innerHTML = dijit.byId('amount_return').attr('displayedValue')+symbal;
		dijit.byId('frm_client').show();
	}
}
dojo.ready(function(){	
		var loan_data = new dojo.store.Memory({
		    data: <?php print_r(Zend_Json::encode($this->loan_number));?>
		});
		new dijit.form.FilteringSelect({
			store: dojo.data.ObjectStore({objectStore: loan_data}),
			autoComplete: true,
			query: {
				branch_id: "-1"
			},            
			required: false,		           
			name: "loan_number",
			id: "loan_number",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				getLaonHasPayByLoanNumber();
			}
		}, "loan_number");
		
	var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->client));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "client_id",
	id: "client_id",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
	   }
}
	}, "client_id");

	var clientCode_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->clientCode));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: clientCode_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "client_code",
	id: "client_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
		}
	}
	}, "client_code");

    not_submit = 0;
	document = dojo.byId("loan_number");
	dojo.connect(document, "onkeyup", function(event) {
		key_number = (event.keyCode);
		if(key_number==13){
			not_submit = 1;
			getLaonHasPayByLoanNumber();
			getLaonPayment(1);
			getAllLaonPayment(1);
		}
	});	
});

function filterLoanNumber(){
	 dijit.byId('loan_number').query.branch_id = dijit.byId('branch_id').get('value');
}
is_change=0;
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_id').query.branch_id = branch_id;
	dijit.byId('client_code').query.branch_id = branch_id;
	if(is_change==0){
		dijit.byId('client_id').reset();
		dijit.byId('client_code').reset();
	}
}
    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
	function print(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
		submitData();
	}
	function hideDialog() {		
		dijit.byId("frm_client").hide();
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('frm_client').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	}
</script>
<script type="text/javascript">
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

dojo.ready(function(){
	loan_number = dijit.byId('loan_number').focus();
	dijit.byId('currency_type').attr('readOnly','readOnly');
	dijit.byId('payment_term').attr('readOnly','readOnly');
	dijit.byId('interest_rate').attr('readOnly','readOnly');
});



var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-il-loan-Detail')); ?>';
function getLaonPayment(type){
	try{
	tem='';	is_set=0;
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('client_id').get('value');
	}
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(respone) {
			},
			error: function(e) {
				//alert(e);
			}
		});
	}catch(err){
		//alert(err);
	}	
}
function getLoan(){
}
function getAllLaonPayment(types){
	if(types==1){
		var loan_numbers = dijit.byId('loan_number').get('value');
	}else if(types==2){
		var loan_numbers = dijit.byId('client_code').get('value');
	}else if(types==3){
		var loan_numbers = dijit.byId('client_id').get('value');
	}
	var url_submits = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-all-il-loan-Detail')); ?>';
		dojo.xhrPost({
		    url: url_submits,
		    content : { 
			    'loan_numbers':loan_numbers,
			    'types':types,
			},	
			handleAs:"json",
			load: function(data) {
			},
			error: function(e) {
				//alert(e);
			}
		});
}
function getLaonHasPayByLoanNumber(){
	try{
		var loan_number = dijit.byId('loan_number').get('value');
		var url_submits = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'payment','action'=>'getsavingpayment')); ?>';
			dojo.xhrPost({
			    url: url_submits,
			    content : { 
				    'pawnid':loan_number,
				},	
				handleAs:"json",
				load: function(data) {
					dijit.byId('client_id').attr('value',data.client_id);
					dijit.byId('client_code').attr('value',data.client_id);
					dijit.byId('load_level').attr('value',data.level);
					
					dijit.byId('total_amount_loan').attr('value',data.release_amount);
					dijit.byId('currency_type').attr('value',data.currency_type);
					dijit.byId('payment_term').attr('value',data.term_type);

					dijit.byId('interest_rate').attr('value',data.interest_rate);
					dijit.byId('loan_period').attr('value',data.period);
					dijit.byId('release_date').attr('value',data.saving_date);
					dijit.byId('total_interest').attr('value',data.total_interest);
					dijit.byId('os_amount').attr('value',data.release_amount);
					dijit.byId('end_date').attr('value',data.saving_close);
					dijit.byId('product_id').attr('value',data.product_id);
					dijit.byId('pawn_number').attr('value',data.saving_number);
					
					document.getElementById('description').innerHTML =data.product_description;
					
					calculateAmount();
				},
				error: function(e) {
					//alert(e);
				}
			});
	}catch(err){
	}
}
function payOption(){
	calculateAmount();
}
function calculateAmount(){
	dijit.byId("total_payment").attr("value",0);
	dijit.byId("amount_receive").attr("value",0);
	os_amount = dijit.byId("os_amount").get('value');
	total_interest = dijit.byId("total_interest").get('value');
	more_interest = dijit.byId("more_interest").get('value');
	penalize_amount= dijit.byId("penalize_amount").get('value');
	if(dijit.byId('option_pay').get('value')==2){//pay interest only
		amount= total_interest+more_interest+penalize_amount;
	}else{
		amount= os_amount+total_interest+more_interest+penalize_amount;
	}
	dijit.byId("total_payment").attr("value",amount);
	dijit.byId("amount_receive").attr("value",amount);
	totalReturn();
}
function totalReturn(){
	receive_amount = dijit.byId('amount_receive').get('value');
	total_payment = dijit.byId('oldTotalPay').get('value');
	option_pay = dijit.byId('option_pay').get('value');
	total_amount =  parseFloat(total_payment);
	total_payments = dijit.byId('total_payment').get('value');
	amonut_return = parseFloat(receive_amount)-parseFloat(total_payments);
	remain_amount = parseFloat(total_payments)-parseFloat(receive_amount);
	if(amonut_return<0){
		dijit.byId('amount_return').attr('value',0);
	}else{
		dijit.byId('amount_return').attr('value',amonut_return.toFixed(2));
	}
	if(remain_amount>0){
		dijit.byId('remain').attr('value',remain_amount.toFixed(2));
	}else{
		dijit.byId('remain').attr('value',0);
	}
}
function calculateTotal(index){
	try{
	}catch(err){
		alert(err);
	}
}
function getdataPaymentToForm(data){//use
	
}
function getDayString(num){
	var days= ["ច័ន្ទ", "អង្គារ", "ពុធ", "ព្រហ","សុក្រ","សៅរ៏","អាទិត្យ"];
	return days[num];
}
function getCurrencyType(type){
	var option=["៛","$","B"];
	return option[type-1];
}
function adminfee(){
}
function doTotalBypene(){
}

function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function roundhundred(n){
	cu_type = dijit.byId('currency_type').get('value');
	if(cu_type==1){
		var x= n%100 > 0 ? (n-(n%100)+100) : n;
	}else{
		total = parseFloat(n);
		x = total.toFixed(2);
	}
    
    return x;
  }
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
