<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL_PAYMENT"));
$frm = $this->frm_search;

$url_delete = $this->baseUrl()."/pawnshop/payment/delete/id/";
$url_receipt = $this->baseUrl()."/report/pawn/recieptpayment/id/";

?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'payment','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table style="width: 100%">
   		<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			
   			<td><?php //echo $frm->getElement('paymnet_type');?></td>
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   		</tr>
   </table>
</form>
<?php echo $this->list;?>

<script>
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			indexkey="";
			var m = "clicked: " + key;
			 if(key=="delete"){
				url='<?php echo $url_delete;?>';
				indexkey = 'delete';
			 }else if(key=="receipt"){
					url='<?php echo $url_receipt;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"receipt": {name: "<?php  echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-print"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash-o", accesskey: "c o p y"},
			
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_blank');
	}
}
</script>