<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	dojo.require("dijit.Dialog");
</script>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 110px;
    border-radius: 60%;
    height: 110px;
    margin-top: 10px;
    border: solid 1px #eee;
}
.button_browse {
    margin-top: 10px;
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 150px;
}
</style>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
				alert('Please Select Branch');
				dijit.byId('branch_id').focus();
				return false;
			}
			if(dijit.byId('province').get('value')==0){
				alert('Province required');
				dijit.byId('province').focus();
				return false;
			}
            if(dijit.byId('situ_status').get('value')==''){
				alert('Province situ_status');
				dijit.byId('situ_status').focus();
				return false;
			}
			dijit.byId('save_new').set('disabled',true);
			dijit.byId('save_close').set('disabled',true);
			return true;
	}else {
		return false;
	}
</script>
<fieldset>
<table width="100%" style="margin-top:-5px;" >
		<legend  class="mainblog"><strong><?php echo $tr->translate("ADD_CLIENT");?></strong></legend>
	<tr>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME");?></td>
							<td><?php echo $frm->getElement('branch_id');?>
								<?php echo $frm->getElement('is_group');?>
								<?php echo $frm->getElement('group_code');?>
								<?php echo $frm->getElement('group_id');?>
							</td> 
						</tr>
						<!-- <tr>
							<td><?php //echo $tr->translate("IS_GROUP")?></td>
							<td>
							</td>
						</tr>
						<tr>
						    <td><?php //echo $tr->translate("GROUP_CODE")?></td>
							<td></td>
						</tr>
						<tr>
							<td><?php //echo $tr->translate("GROUP_NAME")?></td>
							<td></td>
					    </tr> -->
					    <tr>
							<td><?php echo $tr->translate("CLIENT_NO")?></td>
							<td> <?php echo $frm->getElement('client_no');?> </td>
					    </tr>
					    <tr>
					        <td><strong><?php echo $tr->translate("NAME_KHMER")?>*</strong></td>
					        <td><?php echo $frm->getElement('name_kh');?> </td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("NAME_ENG")?></td>
							<td><?php echo $frm->getElement('name_en');?></td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php echo $frm->getElement('sex');?></td>
						</tr>
						 <tr>
							<td><?php echo $tr->translate("DOB")?></td>
							<td><?php echo $frm->getElement('dob_client');?></td>
					    </tr>
						<tr>
							<td><strong><?php echo $tr->translate("PHONE")?></strong></td>
							<td><?php echo $frm->getElement('phone');?></td>
						</tr>
				</table>	
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_DOCUMENT")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						
						<tr>
						    <td><strong><?php echo $tr->translate("NATIONAL_ID")?></strong></td>
							<td><input id="client_d_type" required="true"/></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("N_O")?></td>
							<td><?php  echo $frm->getElement('national_id');?></td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("SITU_STATUS")?></td>
							<td><?php  echo $frm->getElement('situ_status');?></td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("JOB_TYPE")?></td>
							<td><?php echo $frm->getElement('job');?></td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("PHOTO")?></td>
							<td><?php //echo $frm->getElement('photo');?>
								<div class="account-image">
									<div class="image-box">
										<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
									</div>
									<div class="button_browse">
									<div id='preview'></div>	
											<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
											<input class="btn_borwse_image" type="file" id="photo" name="photo" />
									</div>
								</div>
							</td>
					    </tr>
				</table>
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_ADDRESS")?></strong></legend>
				 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("HOUSE")?></td>
							<td><?php  echo $frm->getElement('house');?></td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("STREET")?></td>
							<td><?php  echo $frm->getElement('street');?></td>
						</tr>
						<tr>
						    <td><strong><?php echo $tr->translate("PROVINCE")?>*</strong></td>
							<td><?php echo $frm->getElement('province');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISTRICT")?></td>
							<td><input id="district" required="true" ></td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("COMMUNE")?></td>
							<td><input id="commune" ></td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("VILLAGE")?></td>
							<td><input id="village" ></td>
					    </tr>
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td colspan="6" bgcolor="#dbe7ff"><strong><?php echo $tr->translate("JOIN_ACCOUNT_INFO")?></strong></td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
			       <td><?php echo $tr->translate("JOIN_WITH")?></td>
					<td><?php  echo $frm->getElement('join_with');?></td>
			    </tr>
			    <tr>
			    	<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
					<td><?php  echo $frm->getElement('relate_with');?></td>	
			    </tr>
			</table>	
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				<tr>
					<td><?php echo $tr->translate("NATIONAL_ID")?></td>
					<td><input id="join_d_type" /></td>
				</tr>
				<tr>
					<td style="width:30%;"><?php echo $tr->translate("N_O")?></td>
					<td><?php echo $frm->getElement('join_nation_id');?></td>					
				</tr>
			</table>
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
			  		<td ><?php echo $tr->translate("TEL")?></td>
					<td><?php  echo $frm->getElement('relate_tel');?></td>	
			    </tr>
				<tr>
					<td><?php echo $tr->translate("DOB")?></td>
					<td><?php  echo $frm->getElement('dob_join_acc');?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="6"  bgcolor="#dbe7ff"><strong><?php echo $tr->translate("GUARANTOR_INFO")?></strong></td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
			        <td><?php echo $tr->translate("SPOUSE_NAME")?></td>
					<td><?php echo $frm->getElement('spouse');?></td>
			    </tr>
			    <tr>
			        <td valign="top"><?php echo $tr->translate("NATIONAL_ID")?></td>
					<td valign="top"><input id="guarantor_d_type" /></td>
			    </tr>
			    <tr>
			        <td valign="top"><?php echo $tr->translate("N_O")?></td>
					 <td valign="top"><?php echo $frm->getElement('spouse_nationid');?></td>
			    </tr>
			    
			</table>	
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr>
					<td valign="top" style="width: 30%;"><?php echo $tr->translate("DOB")?></td>
					<td valign="top"><?php  echo $frm->getElement('dob_guarantor');?></td>						
				</tr>
				<tr>
					<td valign="top"><?php echo $tr->translate("TEL")?></td>
					<td valign="top"><?php  echo $frm->getElement('guarantor_tel');?></td>
				</tr>
			    <tr>
					<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
					<td><?php  echo $frm->getElement('guarantor_with');?></td>
				</tr>
			</table>
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				<tr>
			  		<td valign="top"><?php echo $tr->translate("ADDRESS")?></td>
					<td valign="top"><?php  echo $frm->getElement('guarantor_address');?></td>
			    </tr>
				<tr>
					<td valign="top"><?php echo $tr->translate("NOTE")?></td>
					<td><?php  echo $frm->getElement('desc');?></td>						
				</tr>
				<tr>
				   	<td valign="top"><?php echo $tr->translate("STATUS")?></td>
					<td valign="top"><?php  echo $frm->getElement('status');?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td valign="top"><?php echo $tr->translate("AUTO_COLLATERAL")?>&nbsp;&nbsp;&nbsp;&nbsp;
    		<?php  echo $frm->getElement('chackcall');?>
    	</td>
    </tr>
	<tr>
		<td colspan="6" align="center">
		<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
			 iconClass="dijitIconClear" /> 
		 <input type="button" onclick="submitDataClose()" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
			 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
		<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
			 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		</td>
	</tr>
</table>	
</fieldset>
</form>
<table>
<tr>
</tr>
</table>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog"  id="frm_jobtype" >
			<form id="form_job" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td><?php echo $tr->translate("JOB_TITLE")?></td>
						<td>
							<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="job_name" name="job_name" value="" type="text"></td>
					</tr>
					<tr>
						<td colspan="2" align="center">
						<input type="button" value="Save" label="<?php echo $tr->translate("SAVECLOSE")?>" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addjob();"/>
						</td>
					</tr>
				</table>
		</form>
	</div>
</div>
<?php 
	echo $this->frm_popup_district;
	echo $this->frm_popup_village;
	echo $this->frm_popup_comm;
	echo $this->frm_popup_clienttype;
?>
<script type="text/javascript">
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#photo").change(function(){
    readURL(this);
});
function popupJobOption(){
	job = dijit.byId('job').get('value');
	if(job==-1){
		dijit.byId('frm_jobtype').show();
	}
}
url_job = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'addjob'));?>';
function addjob(type){
	 if(dijit.byId('form_job').validate()){
		labeljob = dijit.byId('job_name').get('value');
		$('#job').val(labeljob);
		$('input[name="job"]').val(labeljob);				
		dijit.byId('frm_jobtype').hide();
	}
}
	var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
	var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	try{
	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete: true,
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
		}  
	}, "district");
	 
	new dijit.form.FilteringSelect({
	store: commune,
	autoComplete: true,
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			commune = dijit.byId('commune').get('value');
			if(commune==-1){
				showPopupCommune();
			}
			else{
				filterVillage();
			}
  }
	}, "commune");
	 
	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete: true,
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			vill = dijit.byId('village').get('value');
			if(vill==-1){
				showPopupVillage();
			}
		}
	}, "village");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,          
		required: false,		           
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					doc_type=1;
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,           
		required: false,		           
		name: "join_d_type",
		id: "join_d_type",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('join_d_type').get('value');
				if(client_d_type==-1){
					doc_type=2;
					showPopupclientdtype();
				}
			}
		}, "join_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,
		required: false,		           
		name: "guarantor_d_type",
		id: "guarantor_d_type",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('guarantor_d_type').get('value');
				if(client_d_type==-1){
					doc_type=3;
					showPopupclientdtype();
				}
			}
		}, "guarantor_d_type");
	
	}catch(e){
		alert(e);
	}
	filterDistrict();
});

url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village').set('store', village_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_group = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getgroupcode'));?>';
function getGroupCode(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch First');
		dijit.byId('branch_id').focus();
		return false;
	}
	group_id=dijit.byId('group_id').get('value');
	if(group_id==''){group_id=0;}
	if(dijit.byId('is_group').checked ==true){
		is_group=1;
		dijit.byId('group_code').attr('value','');
		dijit.byId('group_id').set('readOnly', true);
	}else{
		is_group=0;	
		dijit.byId('group_id').set('readOnly', false);
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
		    'group_id':group_id,
		    'is_group':is_group,
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('group_code').attr('value',data);
		},
		error: function(err) {
		}
	});
}
client_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientcode'));?>';
function getFunction(){
		getGroupCode();
		branch_id = dijit.byId('branch_id').get('value');
		dojo.xhrPost({
			url:client_submit,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {	
				dijit.byId('client_no').attr('value',data);
			},
			error: function(err) {
			}
		});
}
client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()) {
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelen = dijit.byId('village_name').get('value');
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name:labelkh+' - '+labelen,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name:dijit.byId('pop_district_namekh').get('value') +' - '+dijit.byId('pop_district_name').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communeen = dijit.byId('commune_nameen').get('value');
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name:communekh +' - '+communeen,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	if(dijit.byId('frm_clienttype').validate()){
	dojo.xhrPost({
		url:document_type_url,	
		content:{ 
		    'title_en':dijit.byId('clienttype_nameen').get('value'),
		    'title_kh':dijit.byId('clienttype_namekh').get('value'),
		    'type':23,
		},
		handleAs:"json",
		load: function(data) {	
			clienttypeen = dijit.byId('clienttype_nameen').get('value');
			clienttypekh = dijit.byId('clienttype_namekh').get('value');
			if(doc_type==1){
				document_type = dijit.byId('client_d_type');
				
			}else if(doc_type==2){
				document_type = dijit.byId('join_d_type');
			}else{
				document_type = dijit.byId('guarantor_d_type');
			}

			 var myNewItem1 = {					
						id: data,
						name: clienttypekh+'-'+clienttypeen
				};			
				addDataToSelectbox(document_type, d_datastore, myNewItem1, data);		
				 
			dijit.byId('frm_clienttype').reset();
			dijit.byId('frm_clienttype').hide();
		},
		error: function(err) {
			alert(err);
		}
	});	
	}
}
function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
function submitDataClose(){
	if(dijit.byId('branch_id').get('value')==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
    }
	if(dijit.byId('province').get('value')==0){
		alert('Province required');
		dijit.byId('province').focus();
		return false;
    }
    if(dijit.byId('situ_status').get('value')==''){
		alert('Province situ_status');
		dijit.byId('situ_status').focus();
		return false;
    }
	if(dijit.byId('add_client').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_client"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/group/index";
			},
			error: function(e) {
			}
		});
	}
}
</script>