<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('BAD_LOAN'));
$frm = $this->frm_loan;
?>
<form id="add_province" action="<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
    	if(dijit.byId('branch').get('value')==''){
     		alert('Please Select Branch');
     		dijit.byId('branch').focus();
     		return false;
   		}
		if(dijit.byId('client_nameadd').get('value')==''){
     		alert('Please Select Client Name');
     		dijit.byId('client_codeadd').focus();
     		return false;
   		}
		
    	return true;
   		}else {
    	return false;
   	}
	</script>
<fieldset>
<table cellspacing="10" class='fullside' >
<legend><strong><?php echo $tr->translate('BAD_LOAN');?></strong></legend>
<tr>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('BRANCH_INFO');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
					<?php echo $frm->getElement('idclient');?>
					<?php echo $frm->getElement('id');?>
					<td><?php echo $tr->translate("BRANCH_NAME")?></td>
					<td><?php echo $frm->getElement('branch');?></td>
			    </tr>
			    <tr>
					<td><?php echo $tr->translate("LOAN_NO")?></td>
					<td><?php echo $frm->getElement('loannumber');?></td>
				</tr>
				<tr >
					<td><?php echo $tr->translate("INTEREST")?></td>
					<td><?php echo $frm->getElement('interest_rate');?></td>
				</tr>
			</table>
		</fieldset>	
		</td>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('CUSTOMER_INFO');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr>
					<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
					<td><?php echo $frm->getElement('client_code');?></td>
				</tr>
			 	<tr>
					<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
					<td><?php echo $frm->getElement('client_name')?></td>
				</tr>
			 	<tr >
					<td><?php echo $tr->translate("LOAN_LEVEL")?></td>
					<td><?php  echo $frm->getElement('load_level');?></td>	
				</tr>
				<tr>
					<td><?php echo $tr->translate("LOAN_AMOUNT")?></td>
					<td><?php echo $frm->getElement('total_amount_loan')?></td>
				</tr>
			</table>
		</fieldset>
		</td>
		<td width="33%;" valign="top">
		<fieldset>
		     <legend align="center"><strong><?php echo $tr->translate('TERM_INSTALL');?></strong></legend>
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				<tr>
					<td><?php echo $tr->translate("TERM_INSTALL")?></td>
					<td><?php echo $frm->getElement('payment_term')?></td>			
				</tr>
				<tr>
					<td><?php echo $tr->translate("TERM_BORROW")?></td>
					<td><?php  echo $frm->getElement('loan_period');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("RELEASE_DATE")?></td>
					<td><?php echo $frm->getElement('release_date');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("LIFE_LOAN")?></td>
					<td><?php  echo $frm->getElement('end_date');?></td>
				</tr>
				
			</table>
		</fieldset>
		</td>
	</tr>
	<tr>
		<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព៌ត័មាន កម្ចីខូច</strong></td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			<table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			    <tr>
					<td><?php echo $tr->translate("OS")?></td>
					<td><?php echo $frm->getElement('Total_amount');?></td>
			    </tr>
			    <tr>
					<td><?php echo $tr->translate("TOTAL_INTEREST")?></td>
					<td><?php echo $frm->getElement('Interest_amount');?></td>
				</tr>
			    <tr>
					<td><?php echo $tr->translate("CURRENCY")?></td>
					<td><?php  echo $frm->getElement('cash_type');?></td>
				</tr>
			
			</table>
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
			 	<tr>
					<td><?php echo $tr->translate("TERM")?></td>
					<td><?php  echo $frm->getElement('Term');?></td>
				</tr>
			 	<tr >
					<td><?php echo $tr->translate("LOSS_DATE")?></td>
					<td><?php echo $frm->getElement('date_loss')?></td>								
				</tr>
				<tr >
					<td><?php echo $tr->translate("DATE")?></td>
					<td><?php echo $frm->getElement('Date');?></td>
				</tr>
			</table>
		</td>
		<td width="33%;" valign="top">
			 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
				<tr>
					<td><?php echo $tr->translate("NOTE")?></td>
					<td><?php  echo $frm->getElement('Note');?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("STATUS")?></td>
					<td><?php echo $frm->getElement('status');?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<input type="submit" name="save_close"​​ value="កែប្រែ  + ចាកចេញ" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitBtn" dojoType="dijit.form.Button"
			iconClass="dijitIconEdit"/>
		</td>
	</tr>	
</table>
</fieldset>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

require(["dojo/ready"], function(ready){
	 ready(function(){
		 getClientInfo(2);
	  });
});

	
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'getloaninfo')); ?>';
function getClientInfo(type){
	if(type==1){
		values = dijit.byId("client_name").get('value');
	}else if(type==2){
		values = dijit.byId("client_code").get('value');
	}else{
		values = dijit.byId("client_code").get('value');
	} 
	dijit.byId('Total_amount').attr('value',0);
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'loan_id':values,
		},	
		handleAs:"json",
		load: function(data) {
			
			dijit.byId('Total_amount').attr('value',data.total_principal);
			dijit.byId('Interest_amount').attr('value',data.total_interest);
			dijit.byId('loannumber').attr('value',data.loan_number);
			dijit.byId('load_level').attr('value',data.level);
			dijit.byId('interest_rate').attr('value',data.interest_rate);
			dijit.byId('payment_term').attr('value',data.pay_term);
			dijit.byId('loan_period').attr('value',data.total_duration);
		    dijit.byId('release_date').attr('value',data.date_release);
		    dijit.byId('end_date').attr('value',data.date_line);
		    dijit.byId('total_amount_loan').attr('value',data.total_capital);
		    dijit.byId('date_loss').attr('value',data.date_payment);
		    dijit.byId('cash_type').attr('value',data.currency_type);
		    dijit.byId("cash_type").set('readOnly',true);
		    
		    /*dijit.byId("client_nameadd").attr('value',values);

		   */
		},
		error: function(err) {
			alert(err);
		//alert("Your message could not be sent, please try again!.");
		}
	});
	
}

/*function getClientInfo(type){
	//alert(9);
	if(type==1){
	     id = dijit.byId("client_name").get('value');
	}else if(type==2){
		id = dijit.byId("number_code").get('value');
	}else{
		id = dijit.byId("client_code").get('value');
	}
	
	dijit.byId("client_code").attr('value',id);
	dijit.byId("client_name").attr('value',id);
	dijit.byId("number_code").attr('value',id);
    } 

    */

</script>